-- StarUniv inline admin editor migration.
-- Idempotent: safe to run repeatedly after supabase/setup.sql.

-- ---------------------------------------------------------------------------
-- Stable schedule color keys
-- ---------------------------------------------------------------------------
create or replace function public.staruniv_schedule_color_key(p_color text)
returns text
language plpgsql
immutable
as $$
declare
  c text := lower(trim(coalesce(p_color,'')));
  h text;
  r integer; g integer; b integer;
  best text := 'light_gray';
  best_d bigint := 9223372036854775807;
  pr integer; pg integer; pb integer;
  item record;
begin
  if c in ('red','orange','yellow','green','blue','indigo','purple','light_gray') then
    return c;
  end if;

  if c ~ '^#[0-9a-f]{3}$' then
    h := '#' || substr(c,2,1)||substr(c,2,1)||substr(c,3,1)||substr(c,3,1)||substr(c,4,1)||substr(c,4,1);
  elsif c ~ '^#[0-9a-f]{6}$' then
    h := c;
  else
    return 'light_gray';
  end if;

  r := ('x'||substr(h,2,2))::bit(8)::int;
  g := ('x'||substr(h,4,2))::bit(8)::int;
  b := ('x'||substr(h,6,2))::bit(8)::int;

  for item in
    select * from (values
      ('red',255,37,56),('orange',255,138,0),('yellow',255,212,59),('green',22,199,91),
      ('blue',22,119,255),('indigo',51,70,181),('purple',124,58,237),('light_gray',229,231,235)
    ) as p(k,rr,gg,bb)
  loop
    pr := r-item.rr; pg := g-item.gg; pb := b-item.bb;
    if (pr::bigint*pr + pg::bigint*pg + pb::bigint*pb) < best_d then
      best_d := pr::bigint*pr + pg::bigint*pg + pb::bigint*pb;
      best := item.k;
    end if;
  end loop;
  return best;
end;
$$;

update public.calendar_events
set color = public.staruniv_schedule_color_key(color)
where coalesce(color,'') not in ('red','orange','yellow','green','blue','indigo','purple','light_gray');

alter table public.calendar_events
  drop constraint if exists calendar_events_color_key_check;
alter table public.calendar_events
  add constraint calendar_events_color_key_check
  check (color is null or color in ('red','orange','yellow','green','blue','indigo','purple','light_gray'));

-- ---------------------------------------------------------------------------
-- Minimal audit log for destructive and bulk admin actions
-- ---------------------------------------------------------------------------
create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid references auth.users(id),
  action text not null,
  entity text not null,
  entity_id text,
  details jsonb not null default '{}'::jsonb
);
alter table public.admin_audit_log enable row level security;

drop policy if exists admins_read_audit_log on public.admin_audit_log;
create policy admins_read_audit_log
on public.admin_audit_log for select to authenticated
using (public.is_admin());

revoke all on public.admin_audit_log from public, anon;
grant select on public.admin_audit_log to authenticated;

create or replace function public.admin_write_audit(
  p_action text,
  p_entity text,
  p_entity_id text default null,
  p_details jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare v_id bigint;
begin
  if not public.is_admin() then raise exception 'admin only'; end if;
  insert into public.admin_audit_log(user_id,action,entity,entity_id,details)
  values(auth.uid(),p_action,p_entity,p_entity_id,coalesce(p_details,'{}'::jsonb))
  returning id into v_id;
  return v_id;
end;
$$;
revoke all on function public.admin_write_audit(text,text,text,jsonb) from public;
grant execute on function public.admin_write_audit(text,text,text,jsonb) to authenticated;

-- ---------------------------------------------------------------------------
-- Atomic bulk tier edits with audit
-- ---------------------------------------------------------------------------
create or replace function public.admin_bulk_update_tier_members(
  p_ids bigint[],
  p_affiliation text default null,
  p_tier text default null
)
returns integer
language plpgsql
security definer
set search_path=public
as $$
declare v_count integer;
begin
  if not public.is_admin() then raise exception 'admin only'; end if;
  if coalesce(array_length(p_ids,1),0)=0 then return 0; end if;
  if p_affiliation is null and p_tier is null then raise exception 'nothing to update'; end if;

  update public.tier_members
  set affiliation=coalesce(p_affiliation,affiliation),
      tier=coalesce(p_tier,tier),
      modified_at=to_char(timezone('Asia/Seoul',now()),'YYYY-MM-DD HH24:MI:SS')
  where id=any(p_ids);
  get diagnostics v_count = row_count;

  perform public.admin_write_audit(
    'bulk_update','tier_members',array_to_string(p_ids,','),
    jsonb_build_object('affiliation',p_affiliation,'tier',p_tier,'count',v_count)
  );
  return v_count;
end;
$$;
revoke all on function public.admin_bulk_update_tier_members(bigint[],text,text) from public;
grant execute on function public.admin_bulk_update_tier_members(bigint[],text,text) to authenticated;

-- Keep site config shape backwards compatible while establishing inline-editor defaults.
insert into public.site_config(config_key,config_value,updated_at)
values (
  'nav',
  jsonb_build_object(
    'hidden','[]'::jsonb,
    'order','["schedule","members","records","tier","video","stats","tools"]'::jsonb,
    'subtabs','{}'::jsonb,
    'heroDescriptions','{}'::jsonb,
    'homeCarousel','{}'::jsonb,
    'homeSections','{"live":true,"notices":true}'::jsonb
  ),
  now()
)
on conflict (config_key) do update
set config_value =
    jsonb_build_object(
      'hidden', coalesce(site_config.config_value->'hidden','[]'::jsonb),
      'order', coalesce(site_config.config_value->'order','["schedule","members","records","tier","video","stats","tools"]'::jsonb),
      'subtabs', coalesce(site_config.config_value->'subtabs','{}'::jsonb),
      'heroDescriptions', coalesce(site_config.config_value->'heroDescriptions','{}'::jsonb),
      'homeCarousel', coalesce(site_config.config_value->'homeCarousel','{}'::jsonb),
      'homeSections', coalesce(site_config.config_value->'homeSections','{"live":true,"notices":true}'::jsonb),
      'statsTabs', coalesce(site_config.config_value->'statsTabs','[]'::jsonb)
    ),
    updated_at=site_config.updated_at;
