-- StarUniv 운영 콘텐츠/미디어 하이브리드 전환
-- 1) 운영 메타데이터는 DB, 업로드 파일은 Storage, 디자인 고정 자산은 Git에 둔다.
-- 2) 이 파일은 재실행해도 기존 운영 수정값을 덮어쓰지 않는다.

alter table public.members add column if not exists avatar_path text;
alter table public.teams add column if not exists logo_path text;

create table if not exists public.history_entries (
  id text primary key,
  entry_kind text not null default 'manual' check (entry_kind in ('manual','override')),
  event_date date, event_type text, title text, description text,
  members jsonb not null default '[]'::jsonb, youtube_url text, image_path text,
  sort_order integer, hidden boolean not null default false, updated_at timestamptz not null default now()
);
alter table public.history_entries enable row level security;

-- 공개 Storage 버킷. URL은 공개지만 쓰기/삭제는 관리자만 가능하다.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('staruniv-media','staruniv-media',true,10485760,array['image/jpeg','image/png','image/webp','image/gif'])
on conflict (id) do update set public=excluded.public, file_size_limit=excluded.file_size_limit, allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "staruniv_media_public_read" on storage.objects;
create policy "staruniv_media_public_read" on storage.objects for select to public using (bucket_id='staruniv-media');
drop policy if exists "staruniv_media_admin_insert" on storage.objects;
create policy "staruniv_media_admin_insert" on storage.objects for insert to authenticated with check (bucket_id='staruniv-media' and public.is_admin());
drop policy if exists "staruniv_media_admin_update" on storage.objects;
create policy "staruniv_media_admin_update" on storage.objects for update to authenticated using (bucket_id='staruniv-media' and public.is_admin()) with check (bucket_id='staruniv-media' and public.is_admin());
drop policy if exists "staruniv_media_admin_delete" on storage.objects;
create policy "staruniv_media_admin_delete" on storage.objects for delete to authenticated using (bucket_id='staruniv-media' and public.is_admin());

-- 현재 history.json 메타데이터를 최초 1회 시드한다. 운영 DB에 이미 같은 id가 있으면 건드리지 않는다.
insert into public.history_entries (id,entry_kind,event_date,event_type,title,description,members,youtube_url,image_path,sort_order,hidden) values
('h-founding', 'manual', '2024-07-08', 'founding', '츠캄 몬스타즈 창단', '', '["김윤환(감독)", "이경민(감독)"]'::jsonb, 'https://youtu.be/AUVSbE3CJPk?si=sp0XotYnl7vMNuY2', null, 1, false),
('h-mu6xzcc5', 'manual', '2024-09-01', 'broadcast', '츠캄 몬스타즈 창단식', '', '["김윤환", "이경민", "디임", "졈니", "앵지", "토마토", "임조이", "효짱", "한쪼니", "몽군", "모리", "치리", "강덕구", "클템"]'::jsonb, 'https://youtu.be/Wee70wXys_c?si=5ZijExlkYo-_xEzz', null, 0, false),
('h-mu8l836x', 'manual', '2024-09-08', 'event', '첫 대학대전', '', '["앵지", "강덕구", "졈니", "토마토", "치리", "디임", "모리"]'::jsonb, 'https://youtu.be/fOt_dRg5C_Y?si=WSLgxGmfRFNQKx2W', null, null, false),
('h-mu8lfnto', 'manual', '2024-09-14', 'broadcast', '추석특집 전부치기', '', '["강덕구", "김윤환", "이경민", "디임", "토마토", "졈니", "치리", "모리", "임조이", "효짱", "한쪼니", "몽군"]'::jsonb, 'https://youtu.be/YBYHN2ZmGzA?si=z_Cgcpf19wHFqpZ3', null, null, false),
('h-mu8ljyfb', 'manual', '2024-10-08', 'broadcast', '알탕즈 낚시방송', '', '["김윤환", "몽군", "수입뿌드"]'::jsonb, 'https://youtu.be/33PqXjSe-Wo?si=rAVAfB_pAAjEoXwB', null, null, false),
('h-mu8ll7n0', 'manual', '2024-10-16', 'broadcast', '첫 MT', '2024-10-16 ~ 2024-10-17', '["김윤환", "이경민", "디임", "토마토", "앵지", "졈니", "치리", "모리", "임조이", "효짱", "한쪼니", "몽군", "수입뿌드"]'::jsonb, 'https://youtu.be/_1FjsDpUf0s?si=i3-F8UKCQIa1izlq', null, null, false),
('h-mu8rbkfo', 'manual', '2024-10-26', 'event', '대학대전 0승 4패 직면', '', '["디임", "앵지", "임조이", "모리", "졈니", "치리"]'::jsonb, 'https://youtu.be/9f-g3d_VeBM?si=UB7aHuLzD1NCgZDm', null, null, false),
('h-mu8rj1ab', 'manual', '2024-10-27', 'broadcast', '국토 벌칙', '2024-10-27 ~ 2024-10-30', '["김윤환", "이경민", "몽군", "정윤종", "주서리", "김성대", "지동원", "이유란", "효짱"]'::jsonb, 'https://youtu.be/Qk8H63liFII?si=HsEqv3OkKr31R3zY', null, null, false),
('h-mu8rz3yn', 'manual', '2024-12-23', 'match', '라네트배 스타대학대전 우승', '2024-11-24 ~ 2024-12-23', '["김윤환", "이경민", "정윤종", "몽군", "박준오", "수입뿌드", "세나", "디임", "토마토", "앵지", "졈니", "치리", "모리", "임조이", "효짱", "한쪼니"]'::jsonb, 'https://youtu.be/CvT2Tvgm09o?si=JyetpWvBXJumF2Uk', null, null, false),
('h-mu8sa6va', 'manual', '2024-11-11', 'broadcast', '아차산 등산 벌칙', '', '["김윤환", "정윤종", "앵지", "졈니", "모리", "효짱", "한쪼니"]'::jsonb, 'https://youtu.be/wQsiFxOMens?si=BLxvi165eQTnnYhN', null, null, false),
('h-mu8sh2t3', 'manual', '2024-11-24', 'match', '첫 대회, 첫 승', '', '["세나", "디임", "토마토", "졈니", "치리", "임조이"]'::jsonb, 'https://youtu.be/sveWh1Abl2o?si=TK4p--0s77oBWxGv', null, null, false),
('h-mu97ug6f', 'manual', '2025-01-15', 'broadcast', '이경민 생일 술먹방', '', '["이경민", "김윤환", "정윤종", "수입뿌드"]'::jsonb, 'https://youtu.be/8n_Rcmhzvvo?si=e5q__N4TiBeRIfrI', null, null, false),
('h-mu982lgs', 'manual', '2025-01-30', 'broadcast', '설특집 전부치기', '', '["김윤환", "정윤종", "앵지", "임조이", "효짱", "한쪼니", "모리", "세나"]'::jsonb, 'https://youtu.be/NMpN0UPAzBY?si=BxOjIhRd8lv7osn2', null, null, false),
('h-mu9843mu', 'manual', '2025-02-04', 'broadcast', '세모카세', '', '["세나", "김윤환", "이경민", "정윤종"]'::jsonb, 'https://youtu.be/dQ-QcUegmWw?si=kdjPApe9ciP8L1om', null, null, false),
('h-mu988mlu', 'manual', '2025-02-06', 'broadcast', '쪼징어게임2', '', '["한쪼니", "김윤환", "이경민", "정윤종", "수입뿌드"]'::jsonb, 'https://youtu.be/9qq7ANI1r_M?si=pBmSaMNB6xcbMjj8', null, null, false),
('h-mu98fmbs', 'manual', '2025-02-07', 'broadcast', '츠캄 시즌2 MT', '2025-02-07 ~ 2025-02-08', '["김윤환", "이경민", "정윤종", "세나", "토마토", "앵지", "치리", "임조이", "모리", "효짱", "한쪼니", "몽군", "박준오", "수입뿌드"]'::jsonb, 'https://youtu.be/-Avr1XBR9lk?si=sDOp3H2hgjJwaK63', null, null, false),
('h-mu98j6m9', 'manual', '2025-02-17', 'broadcast', '연봉협상', '', '["김윤환", "이경민", "정윤종", "세나", "토마토", "앵지", "졈니", "치리", "임조이", "모리", "효짱", "한쪼니", "몽군", "박준오", "수입뿌드"]'::jsonb, 'https://youtu.be/a3nEBqT1kG4?si=n7q96x0WlLc4wH8K', null, null, false),
('h-mu98ni4c', 'manual', '2025-02-25', 'broadcast', 'JPL2 프로필 촬영', '', '["김윤환", "이경민", "정윤종", "세나", "토마토", "졈니", "앵지", "치리", "임조이", "모리", "효짱", "한쪼니", "진땅콩 T", "몽군", "박준오", "수입뿌드"]'::jsonb, 'https://youtu.be/LKhQyF5PJ1U?si=3pvyRkCQnjtGqsHT', null, null, false),
('h-mu98qalt', 'manual', '2025-03-13', 'match', '츠캄 JPL2 첫 경기', '', '["다예", "졈니", "한쪼니", "모리", "몽군", "앵지"]'::jsonb, 'https://youtu.be/jcVVnj3vGwE?si=xOvWEfitfeBz6mod', null, null, false),
('h-mu98xwft', 'manual', '2025-03-21', 'broadcast', '코치진 술먹방', '', '["김윤환", "이경민", "정윤종", "몽군", "수입뿌드"]'::jsonb, 'https://youtu.be/Spuu2WhQub0?si=jxD6KTXOMDAZu2yF', null, null, false),
('h-mu9904ch', 'manual', '2025-05-13', 'event', '스승의 날 CK', '', '["김윤환", "수입뿌드", "정윤종", "몽군", "이경민", "박준오"]'::jsonb, 'https://youtu.be/8sURAdwGFo0?si=YkYVd8nNjiVUTStP', null, null, false),
('h-mu992sj2', 'manual', '2025-05-24', 'broadcast', '암앵돌풍 더블 데이트', '', '["김윤환", "앵지", "이유란", "김성대"]'::jsonb, 'https://youtu.be/AX-tgeFqvDA?si=_BdQRrdMbsvNvbhb', null, null, false),
('h-mu994xxs', 'manual', '2025-06-14', 'broadcast', '김윤환을 이겨라', '', '["김윤환", "주하랑", "졈니", "임조이", "다예", "수입뿌드", "오리3", "히엉", "귀요민정"]'::jsonb, 'https://youtu.be/QxK7-EhVt_g?si=EUNuc-uZCZeOBYJ_', null, null, false),
('h-mu9966nb', 'manual', '2025-06-15', 'event', '시빌워', '', '["김윤환", "이경민", "정윤종", "박준오", "수입뿌드", "세나", "토마토", "앵지", "임조이", "효짱", "모리", "치리", "막내현진", "한쪼니", "다예", "오리3"]'::jsonb, 'https://youtu.be/gQVfZQTCOqE?si=vWp_8zcDFuhx3kdC', null, null, false),
('h-mu997bk0', 'manual', '2025-06-21', 'broadcast', '최가네 불편한스타', '', '["김윤환", "김윤중", "란란", "로링", "이지각", "유은", "두돈반"]'::jsonb, 'https://youtu.be/BU9IED2ksD4?si=qydXYIIXaEQazP9u', null, 1, false),
('h-mu998czs', 'manual', '2025-06-21', 'broadcast', '암점 종겜대전', '', '["김윤환", "김윤중"]'::jsonb, 'https://youtu.be/ZIn-AR71uYw?si=wF9_izpMhYw1MbIa', null, 0, false),
('h-mu99d7s4', 'manual', '2025-07-13', 'match', '시조새배 JPL 시즌2 3위', '2025-03-08 ~ 2025-07-16', '["김윤환", "이경민", "정윤종", "몽군", "박준오", "수입뿌드", "세나", "토마토", "다예", "졈니", "앵지", "치리", "임조이", "모리", "효짱", "한쪼니", "막내현진"]'::jsonb, 'https://youtu.be/CmCAu1Z-xTM?si=RRtJwvQ5TPq_Hf_h', null, null, false),
('h-mu9cq534', 'manual', '2025-01-18', 'broadcast', '세나 결혼', '', '["세나"]'::jsonb, 'https://youtu.be/QhxOsoXCH5A?si=vPWjznJFxB36QCpJ', null, null, false),
('h-mu9dcg2r', 'manual', '2025-08-06', 'broadcast', '츠캄 풋살', '', '["김윤환", "이경민", "정윤종", "조일장", "황병영", "박준오", "수입뿌드", "진땅콩", "모리", "시조새", "몽군", "지동원", "정영재", "방태수", "전태양", "김성대", "빡죠스"]'::jsonb, 'https://youtu.be/5AeDjMWIvXA?si=Dithcaebgf7hsm14', null, null, false),
('h-mu9dnn6x', 'manual', '2025-08-09', 'event', '코치CK', 'VS 이노대 왁싱 벌칙빵', '["박준오", "이경민", "황병영", "지동원", "김윤환", "정윤종", "조일장"]'::jsonb, 'https://youtu.be/6UlIfeJHLO0?si=OsTggefmpd4tWqis', null, null, false),
('h-mu9dok0t', 'manual', '2025-08-10', 'broadcast', '왁싱 벌칙', '', '["김윤환", "지동원", "김성대"]'::jsonb, 'https://youtu.be/f-lyC6eoVeE?si=x7045AJbN4CAIqHn', null, null, false),
('h-mu9dt2z5', 'manual', '2025-08-13', 'broadcast', '츠캄 시즌3 MT', '2025-08-13 ~ 2025-08-15', '["김윤환", "이경민", "정윤종", "토마토", "다예", "햇살", "두디", "주하랑", "치리", "임조이", "막내현진", "진땅콩", "조일장", "황병영", "지동원", "수입뿌드"]'::jsonb, 'https://youtu.be/Srssj7p8d-I?si=_jTK7k_WR7u6lArA', null, null, false),
('h-mu9e0jur', 'manual', '2025-08-16', 'event', '한중전', '', '["김윤환", "이경민", "지동원"]'::jsonb, 'https://youtu.be/cRy4TzENFwY?si=vOBUr1fxCHh0bvDr', null, null, false),
('h-mu9e7706', 'manual', '2025-08-20', 'broadcast', '종아리 신길동짬뽕 벌칙', '', '["김윤환", "이경민", "정윤종", "김성대"]'::jsonb, 'https://youtu.be/a5rnB4twtZ4?si=pGWVfg22hQWloWwR', null, 1, false),
('h-mu9e9qsx', 'manual', '2025-08-20', 'broadcast', '츠캄 VS 이노대 종겜대전', '', '["김윤환", "주하랑", "치리", "모리", "박준오", "지동원", "림예이", "연수", "비타밍", "김성대", "임진묵", "윤수철"]'::jsonb, 'https://youtu.be/7avx-ZE_scU?si=7MC9BwHmwc1hq5lV', null, 0, false),
('h-mu9ed46i', 'manual', '2025-08-31', 'broadcast', '토스반 갈먹CK', '', '["김윤환", "정윤종", "토마토", "주하랑", "막내현진", "진땅콩", "지동원"]'::jsonb, 'https://youtu.be/HAA9zs3tkBA?si=qgyznNWi_I2rNGQE', null, null, false),
('h-mu9efdqr', 'manual', '2025-09-03', 'broadcast', '빠지 여행', '2025-09-03 ~ 2025-09-04', '["김윤환", "이경민", "정윤종", "다예", "토마토", "햇살", "두디", "주하랑", "치리", "임조이", "모리", "막내현진", "진땅콩", "조일장", "황병영", "박준오", "지동원", "수입뿌드"]'::jsonb, 'https://youtu.be/jZGLTrGajsE?si=Y7U6zbXjlsA-3qN-', null, null, false),
('h-mu9eo8el', 'manual', '2025-09-06', 'broadcast', '저그반 흉가CK', '', '["김윤환", "다예", "두디", "치리", "임조이", "조일장", "박준오", "지동원", "란란"]'::jsonb, 'https://youtu.be/-AZXMFTLKIg?si=jN18PGNEg3nKJDiZ', null, null, false),
('h-mu9epsve', 'manual', '2025-09-10', 'broadcast', '조살포차', '', '["임조이", "김윤환", "정윤종", "박준오", "치리"]'::jsonb, 'https://youtu.be/35xGr9CFrQ4?si=0N2okdym_9eOaaa6', null, null, false),
('h-mu9eslf0', 'manual', '2025-09-15', 'broadcast', '메이드 카페 벌칙', '', '["김윤환", "이경민", "조일장", "지동원"]'::jsonb, 'https://youtu.be/QZTeMHnq3Xs?si=QWyeluR8h9INnGho', null, null, false),
('h-mu9evd06', 'manual', '2025-09-18', 'broadcast', '스타마블', '', '["김윤환", "토마토", "두디", "지동원"]'::jsonb, 'https://youtu.be/qc69GYL9Wes?si=X-Vnk9qwgyzkAw_8', null, null, false),
('h-mu9f2l1w', 'manual', '2025-09-30', 'event', '시빌워', '', '["김윤환", "이경민", "정윤종", "박준오", "조일장", "황병영", "토마토", "다예", "햇살", "두디", "주하랑", "소주양", "임조이", "치리", "모리", "막내현진", "진땅콩"]'::jsonb, 'https://youtu.be/GiiMTw8Kn0Y?si=FFvGGaNhZLlEtTH5', null, null, false),
('h-mu9f4ro7', 'manual', '2025-10-04', 'broadcast', '24시간 벌칙 방송', '시빌워 벌칙', '["김윤환", "이경민", "정윤종", "다예", "두디", "치리", "주하랑", "막내현진", "진땅콩", "조일장", "지동원", "흑운장", "카히리", "기뉴다", "늑대채린"]'::jsonb, 'https://youtu.be/wZxsNY9Y7W8?si=-UkHMmUFIVQTdwh9', null, null, false),
('h-mu9f8gwk', 'manual', '2025-10-29', 'match', 'SOOP 스타대학리그 2025 조별예선 탈락', '2025-10-26  ~ 2025-11-23', '["김윤환", "이경민", "정윤종", "조일장", "황병영", "박준오", "수입뿌드", "토마토", "다예", "햇살", "두디", "치리", "주하랑", "소주양", "임조이", "모리", "막내현진", "진땅콩"]'::jsonb, 'https://youtu.be/D1MW4zeQokI?si=L4MqZCiVwqBiovxq', null, 1, false),
('h-mu9fh32l', 'manual', '2025-10-30', 'broadcast', '알탕즈 시즌2', '', '["김윤환", "정윤종", "황병영", "지동원", "수입뿌드"]'::jsonb, 'https://youtu.be/OmUfq2iCKuk?si=yOSyiHl3iu4jilSW', null, null, false),
('h-mu9fms54', 'manual', '2025-11-03', 'broadcast', '국토', '2025-11-03 ~ 2025-11-07', '["김윤환", "이경민", "정윤종", "지동원", "수입뿌드", "클템", "란란", "해기", "치리", "진땅콩", "소주양", "토마토", "다예", "주하랑", "임조이"]'::jsonb, 'https://youtu.be/04S2P1IumIk?si=LarKpGMCIbVT2lSs', null, null, false),
('h-mu9fqstd', 'manual', '2025-06-16', 'broadcast', '릴레이 국토', '시빌워 벌칙', '["정윤종", "김봉준", "효짱", "강구열", "앵지", "란란", "치리", "라미", "오리3", "이채이", "세나", "이예훈", "한쪼니", "쟈닌", "이경민", "다뉴"]'::jsonb, '', null, null, false),
('h-mu9goxx0', 'manual', '2025-11-11', 'broadcast', '성심당 오픈런', '할없사 벌칙', '["김윤환", "햇살", "주하랑", "진땅콩", "파도튜브"]'::jsonb, 'https://youtu.be/E5pXHOBM_ts?si=rbaKfK3noD31DV24', null, null, false),
('h-mu9gs0ua', 'manual', '2025-12-04', 'broadcast', '노량진 합방', '홍어 벌칙', '["김윤환", "치리", "주하랑", "소주양", "임조이", "진땅콩", "조일장", "황병영", "박준오", "지동원", "파도튜브", "수입뿌드"]'::jsonb, 'https://youtu.be/DnU0wyfRktE?si=Aa-fxiCKrOp3-H5u', null, null, false),
('h-mu9gyb17', 'manual', '2025-12-20', 'broadcast', '츠캄 VS 이노대 운동회', '', '["김윤환", "정윤종", "토마토", "다예", "햇살", "치리", "주하랑", "소주양", "막내현진", "진땅콩", "박쭈이", "박준오", "지동원", "파도튜브", "수입뿌드"]'::jsonb, 'https://youtu.be/UCrGE9QhfYE?si=VHiARUMtaMNYCxde', null, null, false),
('h-mu9h2ke4', 'manual', '2025-12-27', 'broadcast', 'SOOP 스트리머 대상 시상식', '', '["김윤환", "이경민", "정윤종"]'::jsonb, 'https://youtu.be/4gQHhD040Mw?si=7DZa8S6ZjhRU48QH', null, null, false),
('h-mu9hhn45', 'manual', '2026-01-01', 'broadcast', '72시간 노방종', '2026-01-01 ~ 2026-01-03', '["토마토", "다예", "햇살", "치리", "주하랑", "소주양", "임조이", "진땅콩", "박쭈이", "지동원", "수입뿌드"]'::jsonb, 'https://youtu.be/S0lgphpmiGg?si=gLsbG5goDV3LNmGU', null, null, false),
('h-mu9hksk4', 'manual', '2026-01-15', 'broadcast', '이경민 생일 술먹방', '', '["이경민", "김윤환", "토마토", "치리", "주하랑", "진땅콩"]'::jsonb, 'https://youtu.be/UcHyZ9K4koA?si=fTxULwaAnYQDM8kS', null, null, false),
('h-mu9hnthn', 'manual', '2026-01-13', 'broadcast', '목욕탕 컨텐츠', '', '["진땅콩", "토마토", "다예", "햇살", "치리", "주하랑", "소주양", "임조이", "박쭈이", "수입뿌드"]'::jsonb, 'https://youtu.be/gR6GSy-Ys-s?si=pPPp8NgPFIK2zAyL', null, null, false),
('h-mu9hsvmy', 'manual', '2026-01-24', 'broadcast', '흑스타즈 VS 암카데미', '', '["김윤환", "수입뿌드", "토마토", "임조이", "진땅콩", "흑운장", "몽군", "뚜미", "갱이다", "링가"]'::jsonb, 'https://youtu.be/rU2lJVrB2rI?si=C4ZApvJ-ZJ8hZYjz', null, null, false),
('h-mu9hyaaw', 'manual', '2026-01-31', 'broadcast', '붕어빵 카페', '', '["김윤환", "이경민", "토마토", "햇살", "소주양", "주하랑", "치리", "임조이", "먼진", "진땅콩", "조일장", "황병영", "박준오", "박수범", "배성흠", "지동원", "파도튜브", "수입뿌드"]'::jsonb, 'https://youtu.be/uxMhoaZMNx4?si=uF184J6ZcqIDBw3b', null, null, false),
('h-mu9i65gw', 'manual', '2026-02-13', 'broadcast', '설특집 츠캄요리사', '', '["김윤환", "이경민", "주하랑", "소주양", "치리", "진땅콩", "지동원"]'::jsonb, 'https://youtu.be/BYfilwm-Sdk?si=KEwfIOeO-T8Y-k37', null, null, false),
('h-mu9if3lm', 'manual', '2026-03-14', 'match', '정선숲퍼컵 8강', '2026-02-24 ~ 2026-03-21', '["김윤환", "이경민", "조일장", "황병영", "박준오", "박수범", "배성흠", "지동원", "파도튜브", "수입뿌드", "토마토", "햇살", "소주양", "주하랑", "치리", "임조이", "먼진", "진땅콩"]'::jsonb, 'https://youtu.be/qZoD_Fp2D88?si=fkmQYGMVNUDScdtW', null, 1, false),
('h-mu9ihl5y', 'manual', '2026-03-26', 'broadcast', '츠캄 VS JSA 풋살', '', '["김윤환", "박준오", "사테", "지동원", "배성흠", "파도튜브", "지두두", "찌킹", "먼진", "정영재", "김성대", "시조새"]'::jsonb, 'https://youtu.be/02Hk3X6p23g?si=6xch0tyeGM32nPXB', null, null, false),
('h-mu9inpdm', 'manual', '2026-04-04', 'broadcast', '츠캄 VS JSA 스보라', '', '["김윤환", "토마토", "찌킹", "주하랑", "소주양", "먼진", "아리송이", "박수범", "지동원", "배성흠", "시조새"]'::jsonb, 'https://youtu.be/EonP6znz-x8?si=DSqx2pXyIHJ5kbOk', null, null, false),
('h-mu9ipode', 'manual', '2026-04-17', 'event', '수장CK', '', '["김윤환", "이경민", "철구", "김봉준", "시조새", "기뉴다", "흑운장", "전태규"]'::jsonb, 'https://youtu.be/-o4QGWh178g?si=dD6GehkDgf0w3nIC', null, null, false),
('h-mu9irslm', 'manual', '2026-04-25', 'event', '츠캄 VS 뉴캣슬 대학대전', '빌드실명제 도입 후 첫 재판', '["먼진", "박준오", "임조이", "김윤환", "아리송이", "이경민", "찌킹", "배성흠", "소주양", "사테", "진땅콩", "파도튜브"]'::jsonb, 'https://youtu.be/xmZxsrwz8cY?si=ap1JIBpDJUZzu7eQ', null, null, false),
('h-mu9ityp6', 'manual', '2026-04-29', 'broadcast', '츠캄 시즌4 MT', '2026-04-29 ~ 2026-04-30', '["김윤환", "이경민", "토마토", "지두두", "햇살", "찌킹", "치리", "주하랑", "소주양", "임조이", "비타밍", "아리송이", "먼진", "진땅콩", "낭니", "박준오", "사테", "박수범", "지동원", "배성흠", "파도튜브"]'::jsonb, 'https://youtu.be/pKWjscMNR5I?si=dbUJWDBXYCERHb1o', null, null, false),
('h-mu9j1izt', 'manual', '2026-05-07', 'founding', '대학명 ''캄몬스타즈''로 변경', '', '[]'::jsonb, 'https://youtu.be/MriCJCTlD3U?si=wZme0j45D6ipyr2R', null, null, false),
('h-mu9j38op', 'manual', '2026-05-09', 'broadcast', '24시간 벌칙 방송', '', '["김윤환", "지두두", "찌킹", "소주양", "비타밍", "아리송이", "사테", "지동원", "배성흠", "파도튜브"]'::jsonb, 'https://youtu.be/k64EXRqIgTU?si=IYC9YvCUd2lF0huK', null, null, false),
('h-mu9j5r41', 'manual', '2026-05-13', 'event', '스승의 날 CK', '276만', '["김윤환", "지동원", "파도튜브", "박준오", "박수범", "사테", "배성흠"]'::jsonb, 'https://youtu.be/4EMk8X6ZZAE?si=efFeO8BO9TNfIOVP', null, null, false),
('h-mu9j73j6', 'manual', '2026-05-14', 'broadcast', '스승의 날 합방', '', '["김윤환", "토마토", "지두두", "찌킹", "치리", "주하랑", "소주양", "임조이", "비타밍", "먼진", "아리송이", "진땅콩", "낭니", "박준오", "박수범", "지동원", "배성흠", "파도튜브"]'::jsonb, 'https://youtu.be/FepZ8svCDq0?si=DtU8aED0twN49t_8', null, null, false),
('h-mu9jb2mz', 'manual', '2026-05-20', 'broadcast', '흉가 벌칙', '캄몬 VS 엠비대 대학대전', '["김윤환", "치리", "주하랑", "소주양", "지동원", "파도튜브"]'::jsonb, 'https://youtu.be/FJbb5-cX3Rs?si=MAoaV7_kuvx3PxpZ', null, null, false),
('h-mu9jdg60', 'manual', '2026-06-01', 'match', '스타워즈 4강', '', '["김윤환", "박준오", "사테", "박수범", "지동원", "배성흠", "파도튜브", "토마토", "지두두", "햇살", "찌킹", "치리", "주하랑", "소주양", "임조이", "비타밍", "아리송이", "먼진", "진땅콩", "낭니"]'::jsonb, 'https://youtu.be/NeqyY8yGTp4?si=jgbNoN6yHrVt_m1W', null, null, false),
('h-mu9jepkk', 'manual', '2026-06-02', 'event', '캄몬 VS 씨나인 스타워즈 나락전', '갯벌스타', '["김윤환", "지두두", "토마토", "비타밍", "소주양", "임조이", "치리", "찌킹", "먼진", "아리송이", "진땅콩", "사테", "박준오", "박수범", "지동원", "배성흠", "파도튜"]'::jsonb, 'https://youtu.be/ycD_eTwxDN4?si=XrIByji41EyPhntm', null, null, false),
('h-mu9jh0en', 'manual', '2026-06-03', 'broadcast', '캄몬합숙소', '2026-06-03 ~2026-06-07', '["김윤환", "지두두", "찌킹", "임조이", "진땅콩", "치리", "먼진", "소주양", "비타밍", "토마토", "아리송이", "박준오", "사테", "박수범", "파도튜브", "배성흠", "지동원"]'::jsonb, 'https://youtu.be/Cem7EYHDWOo?si=yh2vR4K0muN_iifa', null, null, false),
('h-mu9jib1s', 'manual', '2026-06-13', 'event', '김윤환 생일 대학대전', '', '["진땅콩", "비타밍", "먼진", "아리송이", "토마토", "찌킹", "임조이"]'::jsonb, 'https://youtu.be/XJR01anzzI0?si=_cvhBev1SsLfqRTh', null, null, false),
('h-mu9jjrw7', 'manual', '2026-06-18', 'event', '촌캉스', '스승의 날 CK 공약', '["지두두", "김윤환", "소주양", "지동원"]'::jsonb, 'https://youtu.be/ybyzIJgwn8E?si=451K37WwlQoxGBRn', null, null, false),
('h-mu9jlo59', 'manual', '2026-06-27', 'broadcast', '놀이공원', '스승의 날 CK 공약', '["비타밍", "김윤환", "토마토", "지동원"]'::jsonb, 'https://youtu.be/lY599_tJkrw?si=-F0J4piqgsp-dpdw', null, null, false),
('h-mu9jo7j8', 'manual', '2026-07-04', 'match', '뉴캄옥션 족암새퉤퉤퉤 준우승', '2026-06-23 ~ 2026-07-04', '["김윤환", "철구", "시조새", "최세상", "비타밍", "갱이다"]'::jsonb, 'https://youtu.be/5DvgTwZHEuY?si=iuHZj7feh2crqpeM', null, null, false),
('h-mu9jpx62', 'manual', '2026-07-09', 'broadcast', '낭니 오프교육', '스승의 날 CK 공약', '["낭니", "김윤환"]'::jsonb, 'https://youtu.be/Ock1jKfcRao?si=ZXbgmTuvujgRGo2u', null, null, false),
('h-mu9jrrwk', 'manual', '2026-07-11', 'broadcast', '현실종겜', '스승의 날 CK 공약', '["주하랑", "김윤환", "먼진", "김민철"]'::jsonb, 'https://youtu.be/PduVMpDwUrc?si=rbtqhCit57DanC1G', null, null, false),
('h-mu9jth29', 'manual', '2026-07-13', 'broadcast', '테란반 글램핑', '스승의 날 CK 공약', '["지두두", "햇살", "소주양", "비타밍", "사테", "지동원"]'::jsonb, '', 'data/history/h-mu9jth29-mu9rd9bk.jpg', null, false),
('h-mu9jus0b', 'manual', '2026-07-14', 'event', '시빌워', '', '["김윤환", "주하랑", "치리", "아리송이", "먼진", "소주양", "남덕선", "지동원", "비타밍", "임조이", "햇살", "찌킹", "박수범", "배성흠", "사테", "박준오", "지두두", "토마토", "변현제", "김민철", "낭니", "클템"]'::jsonb, 'https://youtu.be/orATQAOCpw4?si=nhJPf3BUu-yXMUOv', null, null, false),
('h-mu9jw6h6', 'manual', '2026-07-24', 'broadcast', '힐링캠프', '스승의 날 CK 공약', '["토마토", "김윤환", "박준오", "임조이", "치리"]'::jsonb, 'https://youtu.be/5q7lh3qpRbk?si=C2JDCekFZnbpFDU0', null, null, false),
('h-mu9jyba3', 'manual', '2026-07-30', 'broadcast', '캄몬합숙소', '2026-07-30 ~ 2026-8-01', '["김윤환", "남덕선", "햇살", "주하랑", "소주양", "사테", "박수범", "배성흠", "지동원"]'::jsonb, 'https://youtu.be/OP30_xl0d9o?si=vxZLPbTqOaL5uwAK', null, null, false),
('h-mu9k2fbq', 'manual', '2026-08-04', 'broadcast', '캄몬합숙소', '2026-08-04 ~ 2026-08-05', '["김윤환", "남덕선", "주하랑", "임조이", "비타밍", "김민철", "왜냐맨", "지동원", "박수범"]'::jsonb, 'https://youtu.be/6j-dyjeCt8Q?si=KbUkO5tXv6Ef3v9o', null, null, false),
('h-mu9k532w', 'manual', '2026-08-24', 'broadcast', '족구 스트리머 팀대전', '', '["김윤환", "박준오", "배성흠", "왜냐맨", "지두두", "주하랑", "먼진", "낭니"]'::jsonb, 'https://youtu.be/q-b2uOhwZD8?si=ULWsWsygz_iiOkiH', null, null, false),
('h-mu9k7eql', 'manual', '2026-09-04', 'match', 'K-중만컵 8강', '2026-08-02 ~ 2026-09-19', '["김윤환", "김민철", "변현제", "박준오", "사테", "박수범", "지동원", "배성흠", "왜냐맨", "남덕선", "토마토", "지두두", "햇살", "찌킹", "치리", "주하랑", "소주양", "임조이", "비타밍", "아리송이", "먼진", "낭니"]'::jsonb, 'https://youtu.be/7xSMbE_Uix8?si=u27nOn5kmY9JGDPS', null, 1, false),
('h-mu9k8vio', 'manual', '2026-09-05', 'broadcast', '을왕리 야방', '', '["김윤환", "김민철", "박준오", "배성흠"]'::jsonb, 'https://youtu.be/61m0pUKxtXo?si=U6FwCc18lsbHVe2P', null, null, false),
('h-mu9ka45l', 'manual', '2026-09-07', 'broadcast', '할없사 낚시', '', '["김윤환", "토마토", "먼진", "김민철", "주하랑"]'::jsonb, 'https://youtu.be/kHzcykL7FIo?si=tOuz1Urz4vD9vKnD', null, null, false),
('h-mu9qpqz8', 'manual', '2026-09-20', 'broadcast', '24시간 방송', '스승의 날 CK 공약
2026-09-20 ~ 2026-09-21', '["토마토", "남덕선", "지두두", "햇살", "주하랑", "소주양", "임조이", "비타밍", "아리송이", "먼진", "낭니"]'::jsonb, 'https://youtu.be/6qVPXb_8dXw?si=bdIy6FnmELzx4OJs', null, null, false),
('auto-join-2024-07-08', 'override', null, null, null, null, '[]'::jsonb, null, null, 0, true),
('auto-join-2024-07-09', 'override', null, null, '디임, 졈니 입단', '', '["디임(선수)", "졈니(선수)"]'::jsonb, 'https://youtu.be/nAMxXANHrjs?si=O787Qr8QklH0kUML', null, null, false),
('auto-join-2024-07-12', 'override', null, null, '', '', '["앵지(선수)"]'::jsonb, 'https://youtu.be/XP1lPYf3jOk?si=_hGKxpheNekRV2dC', null, null, false),
('auto-join-2024-07-17', 'override', null, null, '토마토, 임조이 입단', '', '["토마토(선수)", "임조이(유스)"]'::jsonb, 'https://youtu.be/8-LAzyp5JOM?si=Fce3Auv_uiULABPh', null, null, false),
('auto-leave-2024-07-20', 'override', null, null, '', '', '["킹지(유스)"]'::jsonb, '', null, 0, false),
('auto-join-2024-07-20', 'override', null, null, '', '', '["킹지(유스)"]'::jsonb, 'https://youtu.be/Nac05jgNv1M?si=QvVK-eaD6AdwSwNn', null, 1, false),
('auto-join-2024-08-07', 'override', null, null, '효짱, 한쪼니 입단', '', '["효짱(유스)", "한쪼니(유스)"]'::jsonb, 'https://youtu.be/PMIdwfge8j8?si=WDDKK5pzfLlK2nRk', null, null, false),
('auto-join-2024-08-17', 'override', null, null, '몽군, 모리 입단', '', '["몽군(코치)", "모리(선수)"]'::jsonb, 'https://youtu.be/rPbrRLr25a8?si=WKGzSoBfKWMOx78a', null, null, false),
('auto-join-2024-08-19', 'override', null, null, '', '', '["치리(선수)"]'::jsonb, 'https://youtu.be/1tT5UDqj_Cg?si=WIxY6_KaYp8VgEz_', null, null, false),
('auto-join-2024-09-01', 'override', null, null, '', '', '["강덕구(선수)"]'::jsonb, '', null, 1, false),
('auto-leave-2024-09-25', 'override', null, null, '', '', '["강덕구(선수)"]'::jsonb, '', null, null, false),
('auto-join-2024-09-30', 'override', null, null, '', '', '["수입뿌드(코치)"]'::jsonb, 'https://youtu.be/53BKLNYmSNs?si=IbyaIMM_DsY8FgzJ', null, null, false),
('auto-join-2024-10-18', 'override', null, null, '', '', '["박준오(코치)"]'::jsonb, 'https://youtu.be/84yuQx7bSDA?si=SAhFIyz4dbDmQIW-', null, null, false),
('auto-join-2024-10-31', 'override', null, null, '', '', '["정윤종(전력분석관)"]'::jsonb, 'https://youtu.be/EnbnUabTY-M?si=9HUZInK6DuXQhaNB', null, null, false),
('auto-join-2024-11-02', 'override', null, null, '', '', '["세나(선수)"]'::jsonb, 'https://youtu.be/TIuSsn_Ip5g?si=pq3z3tIdFO829KQT', null, null, false),
('auto-leave-2025-01-08', 'override', null, null, '', '', '["디임(선수)"]'::jsonb, '', null, null, false),
('auto-join-2025-02-21', 'override', null, null, '진땅콩, 송혜림 입단', '', '["진땅콩 T(인턴)", "송혜림(인턴)"]'::jsonb, 'https://youtu.be/_E9hH_ZPXAw?si=QXTjtN16YjxKHZF0', null, null, false),
('auto-join-2025-02-28', 'override', null, null, '', '', '["다예(선수)"]'::jsonb, 'https://youtu.be/XsD-pqt3Nho?si=RWABoa2YSlyoiWFI', null, null, false),
('auto-join-2025-03-06', 'override', null, null, '', '', '["막내현진(유스)"]'::jsonb, 'https://youtu.be/t95Kc97OrqQ?si=oyyGaezIfPDvjAbs', null, null, false),
('auto-leave-2025-03-07', 'override', null, null, '진땅콩 퇴단', '', '["진땅콩 T(인턴)"]'::jsonb, '', null, null, false),
('auto-leave-2025-06-12', 'override', null, null, '', '', '["송혜림(유스)"]'::jsonb, '', null, null, false),
('auto-leave-2025-07-14', 'override', null, null, '', '', '["몽군(코치)", "세나(선수)", "졈니(선수)", "앵지(선수)", "효짱(선수)", "한쪼니(선수)"]'::jsonb, 'https://youtu.be/oP1yt9WV6tc?si=9apXLfTXTupZSsAc', null, null, false),
('auto-join-2025-07-26', 'override', null, null, '황병영, 지동원 입단', '', '["황병영(코치)", "지동원(코치)"]'::jsonb, 'https://youtu.be/X2v4tFliNLQ?si=FMCi4y-_5oJLaLnI', null, null, false),
('auto-join-2025-07-27', 'override', null, null, '진땅콩 재입단', '', '["진땅콩(유스)"]'::jsonb, '', null, null, false),
('auto-join-2025-08-04', 'override', null, null, '조일장, 두디 입단', '', '["조일장(코치)", "두디(선수)"]'::jsonb, 'https://youtu.be/KtZ4re55JpI?si=w9U9Fbr0Ommn_DHK', null, null, false),
('auto-join-2025-08-05', 'override', null, null, '', '', '["주하랑(선수)"]'::jsonb, 'https://youtu.be/SoaXJEvurPQ?si=Scu69Z5AFBn47It6', null, null, false),
('auto-join-2025-08-07', 'override', null, null, '', '', '["햇살(선수)"]'::jsonb, 'https://youtu.be/wJUy2V_phes?si=nqboL3KL4wMiiBK-', null, null, false),
('auto-join-2025-09-24', 'override', null, null, '', '', '["소주양(선수)"]'::jsonb, 'https://youtu.be/BROa1Ow9K68?si=CuaP_VpeG-aGwtOr', null, null, false),
('auto-leave-2025-10-29', 'override', null, null, '', '', '["두디(선수)", "모리(선수)", "막내현진(선수)"]'::jsonb, 'https://youtu.be/u8akmF-WyJ0?si=xfij8_i9ihplSoB9', null, 0, false),
('auto-join-2025-11-03', 'override', null, null, '', '', '["파도튜브(코치)"]'::jsonb, '', null, null, false),
('auto-join-2025-11-15', 'override', null, null, '연또, 박쭈이, 정유랭 입단', '', '["연또(인턴)", "박쭈이(인턴)", "정유랭(인턴)"]'::jsonb, 'https://youtu.be/3nt_3kiQM30?si=Zf00wVSrr7u-nuAc', null, null, false),
('auto-leave-2025-11-29', 'override', null, null, '', '', '["정유랭(인턴)"]'::jsonb, '', null, null, false),
('auto-leave-2025-12-06', 'override', null, null, '', '', '["연또(인턴)"]'::jsonb, '', null, null, false),
('auto-leave-2026-01-14', 'override', null, null, '', '', '["정윤종(전력분석관)"]'::jsonb, 'https://youtu.be/ThscazOdcqY?si=-CPOe5vVTWfst7Ll', null, null, false),
('auto-leave-2026-01-17', 'override', null, null, '', '', '["다예(선수)"]'::jsonb, '', null, null, false),
('auto-join-2026-01-17', 'override', null, null, '배성흠, 박수범, 먼진 입단', '', '["배성흠(코치)", "박수범(코치)", "먼진(선수)"]'::jsonb, 'https://youtu.be/c7MKzCW4TVw?si=NmNNGmEwGk6Yc_nB', null, null, false),
('auto-leave-2026-03-14', 'override', null, null, '', '', '["조일장(코치)", "황병영(코치)", "수입뿌드(코치)"]'::jsonb, '', null, 0, false),
('auto-join-2026-03-16', 'override', null, null, '', '', '["비타밍(선수)"]'::jsonb, 'https://youtu.be/ts2d7YEBykQ?si=Is1TJ_E8rPGsHIYd', null, null, false),
('auto-join-2026-03-19', 'override', null, null, '지두두, 아리송이 입단', '', '["지두두(선수)", "아리송이(선수)"]'::jsonb, 'https://youtu.be/vN-MN3XFGk8?si=_DED5oARG5E9AMYD', null, null, false),
('auto-leave-2026-03-21', 'override', null, null, '', '', '["박쭈이(유스)"]'::jsonb, '', null, null, false),
('auto-join-2026-03-26', 'override', null, null, '사테, 찌킹 입단', '', '["사테(코치)", "찌킹(선수)"]'::jsonb, 'https://youtu.be/jA7znOqF12E?si=yKsnBnZvPXDndwCK', null, null, false),
('auto-join-2026-04-28', 'override', null, null, '', '', '["낭니(유스)"]'::jsonb, 'https://youtu.be/s49-qGImYzg?si=uxE-6EwaOnpFPmS5', null, null, false),
('auto-leave-2026-05-04', 'override', null, null, '', '', '["이경민(감독)"]'::jsonb, 'https://youtu.be/zZt3lmoEiSQ?si=ByFNYMfAeAQDDjzH', null, null, false),
('auto-join-2026-06-13', 'override', null, null, '', '', '["변현제(코치)"]'::jsonb, '', null, null, false),
('auto-join-2026-06-16', 'override', null, null, '', '', '["김민철(코치)"]'::jsonb, 'https://youtu.be/I-q__BWF21E?si=epGW4yXLQ2uwZUCE', null, null, false),
('auto-leave-2026-06-28', 'override', null, null, '', '', '["파도튜브(코치)", "진땅콩(선수)"]'::jsonb, 'https://youtu.be/KE_vKv-5w0s?si=MQ8roCCyAjOYnq81', null, null, false),
('auto-join-2026-07-08', 'override', null, null, '', '', '["남덕선(선수)"]'::jsonb, '', 'data/history/auto-join-2026-07-08-mu9rsqn7.jpg', null, false),
('auto-join-2026-07-31', 'override', null, null, '', '', '["왜냐맨(코치)"]'::jsonb, 'https://youtu.be/uigMcUS3O80?si=YoL6SPy0Zey4w0Gj', null, null, false),
('auto-leave-2026-09-04', 'override', null, null, '', '', '["변현제(코치)", "지동원(코치)", "박수범(코치)", "찌킹(선수)", "치리(선수)"]'::jsonb, 'https://youtu.be/RGP4taQNL8g?si=Oj0_TOVB66dRR6uP', null, 0, false),
('auto-join-2024-10-30', 'override', null, null, '', '', '["정윤종(전력분석관)"]'::jsonb, 'https://youtu.be/EnbnUabTY-M?si=iGlrZhLoN_jL_axB', null, null, false)
on conflict (id) do nothing;
