-- ============================================================================
-- 도구 > 외부도구 (기존 어드민 관리 링크)
-- 멀티뷰어/엔트리/캄몬라이더 자체 기능은 Git에 남고, 여기에는 외부 링크만 저장한다.
-- ============================================================================
create table if not exists public.external_tools (
  id bigint generated by default as identity primary key,
  category text not null check (category in ('extTools','extSites')),
  name text not null,
  url text not null,
  favicon text,
  source_order integer not null unique,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);
create index if not exists external_tools_category_order_idx on public.external_tools(category, source_order);
alter table public.external_tools enable row level security;

-- 현재 docs/data/tools.json 최초 시드. 이미 같은 URL이 있으면 건드리지 않는다.
insert into public.external_tools(category,name,url,favicon,source_order,active)
select 'extTools','혹시','https://calm-hoxy.vercel.app/',null,1,true
where not exists (select 1 from public.external_tools where url='https://calm-hoxy.vercel.app/');
insert into public.external_tools(category,name,url,favicon,source_order,active)
select 'extTools','암다리','https://prena.io/brain/',null,2,true
where not exists (select 1 from public.external_tools where url='https://prena.io/brain/');
insert into public.external_tools(category,name,url,favicon,source_order,active)
select 'extTools','핀볼','https://lazygyu.github.io/roulette/',null,3,true
where not exists (select 1 from public.external_tools where url='https://lazygyu.github.io/roulette/');
insert into public.external_tools(category,name,url,favicon,source_order,active)
select 'extTools','네이버 사다리','https://search.naver.com/search.naver?where=nexearch&query=%EC%82%AC%EB%8B%A4%EB%A6%AC%EA%B2%8C%EC%9E%84','https://naver.com/favicon.ico',4,true
where not exists (select 1 from public.external_tools where url='https://search.naver.com/search.naver?where=nexearch&query=%EC%82%AC%EB%8B%A4%EB%A6%AC%EA%B2%8C%EC%9E%84');
insert into public.external_tools(category,name,url,favicon,source_order,active)
select 'extSites','EloBoard','https://eloboard.com/',null,5,true
where not exists (select 1 from public.external_tools where url='https://eloboard.com/');

-- 관리자 CRUD
drop policy if exists admins_all_external_tools on public.external_tools;
create policy admins_all_external_tools on public.external_tools for all to authenticated
using (public.is_admin()) with check (public.is_admin());
grant select,insert,update,delete on public.external_tools to authenticated;
grant usage,select on sequence public.external_tools_id_seq to authenticated;

-- 공개 사이트 읽기
revoke all on public.external_tools from anon;
grant select (id,category,name,url,favicon,source_order,active) on public.external_tools to anon;
drop policy if exists public_read_external_tools on public.external_tools;
create policy public_read_external_tools on public.external_tools for select to anon using (active=true);
