-- StarUniv 일정/휴방/메뉴 설정을 정적 JSON에서 Supabase로 옮기는 1회 마이그레이션.
-- Supabase SQL Editor에서 이 파일 전체를 실행하세요. 여러 번 실행해도 안전하도록 작성했습니다.

create table if not exists public.calendar_events (
  id bigint primary key,
  source_order integer not null unique,
  start_date date not null,
  end_date date not null,
  event_time text,
  person text not null default '',
  description text,
  detail text,
  color text
);
create index if not exists calendar_events_date_idx on public.calendar_events (start_date, end_date);

create table if not exists public.calendar_off_air (
  off_date date not null,
  soop_id text not null,
  source_order integer not null default 0,
  primary key (off_date, soop_id)
);
create index if not exists calendar_off_air_date_idx on public.calendar_off_air (off_date, source_order);

create table if not exists public.site_config (
  config_key text primary key,
  config_value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.calendar_events enable row level security;
alter table public.calendar_off_air enable row level security;
alter table public.site_config enable row level security;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788410176657,1,'2026-09-03'::date,'2026-09-03'::date,'19:00','중만컵','흑카 vs JSA','','#9aa6ba') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788410523229,2,'2026-09-01'::date,'2026-09-01'::date,'','두두','생일','','#ff2538') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788410553136,3,'2026-09-01'::date,'2026-09-01'::date,'20:00','윤환','한중전','','#16c75b') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788410538904,4,'2026-09-02'::date,'2026-09-02'::date,'16:00','낭니','낭피엘','','#ff2538') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788411375531,5,'2026-09-02'::date,'2026-09-03'::date,'비방연습','캄몬','','','#1677ff') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788411859497,6,'2026-09-04'::date,'2026-09-04'::date,'19:00','중만컵','캄몬 vs 케이대','','#1677ff') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788534153554,7,'2026-09-04'::date,'2026-09-04'::date,'21:30','캄몬','재계약','','#1677ff') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788411895026,8,'2026-09-05'::date,'2026-09-05'::date,'19:00','중만컵','뉴캣슬 vs 수술대','','#9aa6ba') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788411922758,9,'2026-09-06'::date,'2026-09-06'::date,'19:00','중만컵','DM vs 엠비대','','#9aa6ba') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788411935742,10,'2026-09-06'::date,'2026-09-06'::date,'19:00','윤환','중만컵 해설','','#16c75b') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788411971561,11,'2026-09-07'::date,'2026-09-07'::date,'19:00','ASL22','16강 A조','짭제 윤중 재욱 영진','#9aa6ba') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788839808275,12,'2026-09-07'::date,'2026-09-07'::date,'30:00','암벽토먼','할없사 낚시','하랑 합류','#1677ff') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788412030098,13,'2026-09-08'::date,'2026-09-08'::date,'19:00','ASL22','16강 B조','상문 경모 제동 명운','#9aa6ba') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788839871844,14,'2026-09-08'::date,'2026-09-08'::date,'14:00','조이','단양 여행','','#ff2538') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788844188701,15,'2026-09-08'::date,'2026-09-08'::date,'16:00','낭니먼진','낭먼이 간다','','#ff2538') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788412051970,16,'2026-09-12'::date,'2026-09-12'::date,'19:00','중만컵','JSA vs 케이대','4강 A조','#9aa6ba') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788412068202,17,'2026-09-13'::date,'2026-09-13'::date,'19:00','중만컵','뉴캣슬 vs DM','4강 B조','#9aa6ba') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788412315390,18,'2026-09-14'::date,'2026-09-14'::date,'19:00','ASL22','16강 C조 민철','재호 영재 민철 일장','#1677ff') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788412376276,19,'2026-09-15'::date,'2026-09-15'::date,'19:00','ASL22','16강 D조','윤철 재현 영한 정우','#9aa6ba') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788412389986,20,'2026-09-19'::date,'2026-09-19'::date,'18:00','중만컵','케이대 vs 뉴캣슬','결승','#9aa6ba') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788951874127,21,'2026-09-20'::date,'2026-09-21'::date,'17:00','캄몬','24시간','','#1677ff') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788972694118,22,'2026-09-09'::date,'2026-09-09'::date,'20:00','민철','코려대CK','','#ff2538') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789013686147,23,'2026-10-03'::date,'2026-10-03'::date,'시간미정','캄몬','팬미팅','','#1677ff') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789025508217,24,'2026-09-10'::date,'2026-09-10'::date,'16:00','햇살','24시간','','#ff2538') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789025526568,25,'2026-09-10'::date,'2026-09-10'::date,'19:00','하랑','테라스 먹방','','#ff2538') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789025567961,26,'2026-09-12'::date,'2026-09-12'::date,'23:00','타밍송이','장판빵 멸망전','윤환 사테 준오','#1677ff') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789100083799,27,'2026-09-11'::date,'2026-09-11'::date,'20:00','윤환','클암CK','','#16c75b') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789186098219,28,'2026-09-12'::date,'2026-09-12'::date,'16:00','낭니','도낭CK','','#ff2538') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789304358823,29,'2026-09-13'::date,'2026-09-13'::date,'22:00','윤환','랜피엘','','#16c75b') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789486342994,30,'2026-09-14'::date,'2026-09-14'::date,'03:30','왜냐맨','블리즈컨','','#ff2538') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789491611046,31,'2026-09-15'::date,'2026-09-15'::date,'24:00','캄몬','롤 내전','','#1677ff') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789537435699,32,'2026-09-13'::date,'2026-09-13'::date,'24:00','두랑먼낭','할업사 주겹살','','#ff2538') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789541321693,33,'2026-09-16'::date,'2026-09-16'::date,'15:00','타밍','낚시 노방종','','#ff2538') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789545339863,34,'2026-09-16'::date,'2026-09-16'::date,'18:00','먼진','더블끝장전','먼진핑핑 vs 정은츄빈','#ff2538') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789624331731,35,'2026-09-17'::date,'2026-09-17'::date,'15:00','준오송이','스튜디오 장판교체','','#1677ff') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789733765026,36,'2026-09-18'::date,'2026-09-18'::date,'20:00','캄몬','단체종겜','','#1677ff') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789802440354,37,'2026-09-19'::date,'2026-09-19'::date,'16:00','마토','장휴 복귀','','#ff2538') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789806002308,38,'2026-09-19'::date,'2026-09-19'::date,'15:00','두두','글램핑 으냉','','#ff2538') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1790056481809,39,'2026-09-21'::date,'2026-09-21'::date,'19:00','ASL22','이영한 VS 유영진','8강 1경기','#9aa6ba') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1790056567014,40,'2026-09-22'::date,'2026-09-22'::date,'19:00','ASL22','이재호 VS 김정우','8강 2경기','#9aa6ba') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1790056611485,41,'2026-09-28'::date,'2026-09-28'::date,'19:00','ASL22','박상현 VS 이제동','8강 3경기','#9aa6ba') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1790056654300,42,'2026-09-29'::date,'2026-09-29'::date,'19:00','ASL22','신상문 VS 김민철','8강 4경기','#1677ff') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1790058669984,43,'2026-09-22'::date,'2026-09-22'::date,'21:00','햇살','4티어 PL','','#ff2538') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-10'::date,'brainzerg7',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-10'::date,'freshtomato',2) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-10'::date,'rnaqpdrjf',3) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-10'::date,'dlaguswl501',4) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-10'::date,'vldpfm2',5) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-10'::date,'sksmsskdsl10',6) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-09'::date,'brainzerg7',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-09'::date,'rnaqpdrjf',2) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-09'::date,'wjswlgns09',3) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-09'::date,'thelddl',4) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-09'::date,'fpahsdltu1',5) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-09'::date,'seemin88',6) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-11'::date,'freshtomato',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-11'::date,'rnaqpdrjf',2) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-11'::date,'dlaguswl501',3) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-11'::date,'2meonjin',4) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-12'::date,'freshtomato',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-12'::date,'rnaqpdrjf',2) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-12'::date,'dlaguswl501',3) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-12'::date,'wjswlgns09',4) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-12'::date,'thelddl',5) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-13'::date,'freshtomato',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-13'::date,'rnaqpdrjf',2) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-13'::date,'dlaguswl501',3) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-14'::date,'freshtomato',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-14'::date,'rnaqpdrjf',2) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-14'::date,'dlaguswl501',3) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-15'::date,'freshtomato',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-15'::date,'dlaguswl501',2) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-15'::date,'rnaqpdrjf',3) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-16'::date,'freshtomato',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-16'::date,'dlaguswl501',2) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-16'::date,'brainzerg7',3) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-16'::date,'sksmsskdsl10',4) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-17'::date,'dlaguswl501',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-17'::date,'brainzerg7',2) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-17'::date,'freshtomato',3) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-17'::date,'wjswlgns09',4) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-18'::date,'brainzerg7',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-18'::date,'freshtomato',2) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-18'::date,'thelddl',3) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-18'::date,'dlaguswl501',4) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-18'::date,'vldpfm2',5) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-18'::date,'sksmsskdsl10',6) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-19'::date,'brainzerg7',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-19'::date,'dlaguswl501',2) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-19'::date,'soju2022',3) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-19'::date,'vldpfm2',4) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-19'::date,'fpahsdltu1',5) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-20'::date,'brainzerg7',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-21'::date,'brainzerg7',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-22'::date,'brainzerg7',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-23'::date,'brainzerg7',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-24'::date,'brainzerg7',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-25'::date,'brainzerg7',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-26'::date,'brainzerg7',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-27'::date,'brainzerg7',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-28'::date,'brainzerg7',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-29'::date,'brainzerg7',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-30'::date,'brainzerg7',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;

insert into public.site_config (config_key,config_value) values ('nav','{"hidden":[],"statsTabs":["balloons"],"heroDescriptions":{}}'::jsonb) on conflict (config_key) do update set config_value=excluded.config_value, updated_at=now();

-- 공개 사이트 읽기 권한
revoke all on public.calendar_events, public.calendar_off_air, public.site_config from anon;
grant select (id,source_order,start_date,end_date,event_time,person,description,detail,color) on public.calendar_events to anon;
grant select (off_date,soop_id,source_order) on public.calendar_off_air to anon;
grant select (config_key,config_value) on public.site_config to anon;

drop policy if exists "public_read_calendar_events" on public.calendar_events;
create policy "public_read_calendar_events" on public.calendar_events for select to anon using (true);
drop policy if exists "public_read_calendar_off_air" on public.calendar_off_air;
create policy "public_read_calendar_off_air" on public.calendar_off_air for select to anon using (true);
drop policy if exists "public_read_site_config" on public.site_config;
create policy "public_read_site_config" on public.site_config for select to anon using (config_key = 'nav');

-- 관리자 CRUD. admin.sql의 public.is_admin()이 먼저 설치되어 있어야 합니다.
do $$
declare t text;
begin
  foreach t in array array['calendar_events','calendar_off_air','site_config']
  loop
    execute format('drop policy if exists %I on public.%I', 'admins_all_' || t, t);
    execute format(
      'create policy %I on public.%I for all to authenticated using (public.is_admin()) with check (public.is_admin())',
      'admins_all_' || t, t
    );
  end loop;
end $$;

grant select, insert, update, delete on public.calendar_events, public.calendar_off_air, public.site_config to authenticated;
