-- StarUniv Supabase schema
-- 1) Supabase SQL Editor에서 이 파일 전체를 실행합니다.
-- 2) 현재 사이트는 DB를 브라우저에서 직접 읽지 않고 GitHub Actions가 db.json으로 내보냅니다.
--    그래서 RLS는 켜되 공개 정책은 만들지 않습니다.

create table if not exists public.settings (
  source_order integer primary key,
  season text not null,
  start_date date
);

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  source_order integer not null unique,
  team_name text not null,
  founders text,
  founded_date date,
  disbanded_date date,
  note text,
  championship text
);
create index if not exists teams_team_name_idx on public.teams (team_name);

create table if not exists public.members (
  -- StarUniv 내부 행 식별자. 외부 서비스 ID와 절대 혼용하지 않는다.
  id bigint generated by default as identity primary key,
  source_order integer not null unique,
  -- 같은 사람의 기준 이름. 예: 진땅콩
  name text not null,
  -- 해당 멤버 행에서 실제 사용한 표시/방송 닉네임. 예: 진땅콩 T
  nickname text not null,
  -- SOOP 계정 ID
  soop_id text,
  -- ELO보드 선수 ID. ELO 원본 players 객체의 key(id)를 여기에는 elo_id로 저장한다.
  elo_id integer,
  birth_date date,
  gender text,
  race text,
  join_tier text,
  tier text,
  role text,
  joined_date date,
  left_date date,
  mbti text
);
create index if not exists members_name_idx on public.members (name);
create index if not exists members_nickname_idx on public.members (nickname);
create index if not exists members_soop_id_idx on public.members (soop_id);
create index if not exists members_elo_id_idx on public.members (elo_id);

create table if not exists public.matches (
  match_no integer primary key,
  source_order integer not null unique,
  match_date date not null,
  opponent_team text not null,
  match_format text,
  method text,
  final_result text,
  set_result text,
  score_diff text,
  funding text,
  support_amount text,
  personal_amount text,
  challenge_mission text
);
create index if not exists matches_date_idx on public.matches (match_date desc);
create index if not exists matches_opponent_idx on public.matches (opponent_team);

create table if not exists public.rounds (
  id bigint generated by default as identity primary key,
  source_order integer not null unique,
  match_no integer not null references public.matches(match_no) on update cascade on delete cascade,
  match_date date not null,
  opponent_team text,
  match_format text,
  set_name text,
  round_name text,
  our_player text,
  our_race text,
  our_tier text,
  result text,
  opponent_player text,
  opponent_race text,
  opponent_tier text,
  map_name text
);
create index if not exists rounds_match_no_idx on public.rounds (match_no);
create index if not exists rounds_date_idx on public.rounds (match_date desc);
create index if not exists rounds_our_player_idx on public.rounds (our_player);
create index if not exists rounds_opponent_player_idx on public.rounds (opponent_player);

create table if not exists public.tier_members (
  id bigint generated by default as identity primary key,
  source_order integer not null unique,
  name text,
  nickname text not null,
  soop_id text,
  elo_id integer,
  birth_date date,
  gender text,
  race text,
  tier text,
  affiliation text,
  role text,
  modified_at text,
  history text,
  started_on text,
  elo_registered text,
  tier_table_registered text,
  promoted_tier_8 text,
  promoted_tier_7 text,
  promoted_tier_6 text,
  promoted_tier_5 text,
  promoted_tier_4 text,
  promoted_tier_3 text,
  promoted_tier_2 text,
  promoted_tier_1 text,
  promoted_tier_0 text
);
create unique index if not exists tier_members_elo_id_uq
  on public.tier_members (elo_id) where elo_id is not null;
create index if not exists tier_members_nickname_idx on public.tier_members (nickname);
create index if not exists tier_members_soop_id_idx on public.tier_members (soop_id);
create index if not exists tier_members_affiliation_idx on public.tier_members (affiliation);

-- ELO 원본은 2차 이전용. migrate_to_supabase.py --include-elo 로 넣을 수 있습니다.
create table if not exists public.elo_categories (
  category_id smallint primary key,
  name text not null
);

create table if not exists public.elo_maps (
  map_id integer primary key,
  name text not null
);

create table if not exists public.elo_players (
  -- eloboard.json players의 key. 원본에서는 그냥 id처럼 보이지만 DB에서는 elo_id로 명확히 구분한다.
  elo_id integer primary key,
  name text not null,
  race text
);
create index if not exists elo_players_name_idx on public.elo_players (name);

create table if not exists public.elo_matches (
  elo_match_id bigint primary key,
  match_date date not null,
  winner_elo_id integer references public.elo_players(elo_id),
  loser_elo_id integer references public.elo_players(elo_id),
  map_id integer references public.elo_maps(map_id),
  category_id smallint not null references public.elo_categories(category_id)
);
create index if not exists elo_matches_date_idx on public.elo_matches (match_date desc);
create index if not exists elo_matches_winner_idx on public.elo_matches (winner_elo_id);
create index if not exists elo_matches_loser_idx on public.elo_matches (loser_elo_id);
create index if not exists elo_matches_map_idx on public.elo_matches (map_id);
create index if not exists elo_matches_category_idx on public.elo_matches (category_id);

-- 브라우저의 anon/authenticated 사용자가 정책 없이 직접 읽거나 쓰지 못하게 막습니다.
alter table public.settings enable row level security;
alter table public.teams enable row level security;
alter table public.members enable row level security;
alter table public.matches enable row level security;
alter table public.rounds enable row level security;
alter table public.tier_members enable row level security;
alter table public.elo_categories enable row level security;
alter table public.elo_maps enable row level security;
alter table public.elo_players enable row level security;
alter table public.elo_matches enable row level security;
