-- StarUniv 최종 Supabase 통합 설정
-- 최종 적용에서는 이 파일 하나만 Supabase SQL Editor에서 실행하세요.
-- 재실행 가능한 DDL/정책과 충돌 안전한 시드(upsert/do nothing)로 구성되어 있습니다.


-- ============================================================================
-- 기본 스키마
-- ============================================================================

-- StarUniv Supabase schema
-- 1) Supabase SQL Editor에서 이 파일 전체를 실행합니다.
-- 2) 현재 사이트는 DB를 브라우저에서 직접 읽지 않고 GitHub Actions가 db.json으로 내보냅니다.
--    그래서 RLS는 켜되 공개 정책은 만들지 않습니다.

create table if not exists public.settings (
  source_order integer primary key,
  season text not null,
  start_date date
);

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  source_order integer not null unique,
  team_name text not null,
  founders text,
  founded_date date,
  disbanded_date date,
  note text,
  championship text,
  logo_path text
);
create index if not exists teams_team_name_idx on public.teams (team_name);

create table if not exists public.members (
  -- StarUniv 내부 행 식별자. 외부 서비스 ID와 절대 혼용하지 않는다.
  id bigint generated by default as identity primary key,
  source_order integer not null unique,
  -- 같은 사람의 기준 이름. 예: 진땅콩
  name text not null,
  -- 해당 멤버 행에서 실제 사용한 표시/방송 닉네임. 예: 진땅콩 T
  nickname text not null,
  -- SOOP 계정 ID
  soop_id text,
  -- ELO보드 선수 ID. ELO 원본 players 객체의 key(id)를 여기에는 elo_id로 저장한다.
  elo_id integer,
  birth_date date,
  gender text,
  race text,
  join_tier text,
  tier text,
  role text,
  joined_date date,
  left_date date,
  mbti text,
  avatar_path text
);
create index if not exists members_name_idx on public.members (name);
create index if not exists members_nickname_idx on public.members (nickname);
create index if not exists members_soop_id_idx on public.members (soop_id);
create index if not exists members_elo_id_idx on public.members (elo_id);

create table if not exists public.matches (
  match_no integer primary key,
  source_order integer not null unique,
  match_date date not null,
  opponent_team text not null,
  match_format text,
  method text,
  final_result text,
  set_result text,
  score_diff text,
  funding text,
  support_amount text,
  personal_amount text,
  challenge_mission text
);
create index if not exists matches_date_idx on public.matches (match_date desc);
create index if not exists matches_opponent_idx on public.matches (opponent_team);

create table if not exists public.rounds (
  id bigint generated by default as identity primary key,
  source_order integer not null unique,
  match_no integer not null references public.matches(match_no) on update cascade on delete cascade,
  match_date date not null,
  opponent_team text,
  match_format text,
  set_name text,
  round_name text,
  our_player text,
  our_race text,
  our_tier text,
  result text,
  opponent_player text,
  opponent_race text,
  opponent_tier text,
  map_name text
);
create index if not exists rounds_match_no_idx on public.rounds (match_no);
create index if not exists rounds_date_idx on public.rounds (match_date desc);
create index if not exists rounds_our_player_idx on public.rounds (our_player);
create index if not exists rounds_opponent_player_idx on public.rounds (opponent_player);

create table if not exists public.tier_members (
  id bigint generated by default as identity primary key,
  source_order integer not null unique,
  name text,
  nickname text not null,
  soop_id text,
  elo_id integer,
  birth_date date,
  gender text,
  race text,
  tier text,
  affiliation text,
  role text,
  modified_at text,
  history text,
  started_on text,
  elo_registered text,
  tier_table_registered text,
  promoted_tier_8 text,
  promoted_tier_7 text,
  promoted_tier_6 text,
  promoted_tier_5 text,
  promoted_tier_4 text,
  promoted_tier_3 text,
  promoted_tier_2 text,
  promoted_tier_1 text,
  promoted_tier_0 text
);
create unique index if not exists tier_members_elo_id_uq
  on public.tier_members (elo_id) where elo_id is not null;
create index if not exists tier_members_nickname_idx on public.tier_members (nickname);
create index if not exists tier_members_soop_id_idx on public.tier_members (soop_id);
create index if not exists tier_members_affiliation_idx on public.tier_members (affiliation);

-- ELO 원본은 2차 이전용. migrate_to_supabase.py --include-elo 로 넣을 수 있습니다.
create table if not exists public.elo_categories (
  category_id smallint primary key,
  name text not null
);

create table if not exists public.elo_maps (
  map_id integer primary key,
  name text not null
);

create table if not exists public.elo_players (
  -- eloboard.json players의 key. 원본에서는 그냥 id처럼 보이지만 DB에서는 elo_id로 명확히 구분한다.
  elo_id integer primary key,
  name text not null,
  race text
);
create index if not exists elo_players_name_idx on public.elo_players (name);

create table if not exists public.elo_matches (
  elo_match_id bigint primary key,
  match_date date not null,
  winner_elo_id integer references public.elo_players(elo_id),
  loser_elo_id integer references public.elo_players(elo_id),
  map_id integer references public.elo_maps(map_id),
  category_id smallint not null references public.elo_categories(category_id)
);
create index if not exists elo_matches_date_idx on public.elo_matches (match_date desc);
create index if not exists elo_matches_winner_idx on public.elo_matches (winner_elo_id);
create index if not exists elo_matches_loser_idx on public.elo_matches (loser_elo_id);
create index if not exists elo_matches_map_idx on public.elo_matches (map_id);
create index if not exists elo_matches_category_idx on public.elo_matches (category_id);

-- 브라우저의 anon/authenticated 사용자가 정책 없이 직접 읽거나 쓰지 못하게 막습니다.
alter table public.settings enable row level security;
alter table public.teams enable row level security;
alter table public.members enable row level security;
alter table public.matches enable row level security;
alter table public.rounds enable row level security;
alter table public.tier_members enable row level security;
alter table public.elo_categories enable row level security;
alter table public.elo_maps enable row level security;
alter table public.elo_players enable row level security;
alter table public.elo_matches enable row level security;

-- 실시간 일정/휴방/사이트 표시 설정. 기존 calendar.json/nav.json의 운영 데이터를 Supabase로 이동한다.
create table if not exists public.calendar_events (
  id bigint primary key,
  source_order integer not null unique,
  start_date date not null,
  end_date date not null,
  event_time text,
  person text not null default '',
  description text,
  detail text,
  color text
);
create index if not exists calendar_events_date_idx on public.calendar_events (start_date, end_date);

create table if not exists public.calendar_off_air (
  off_date date not null,
  soop_id text not null,
  source_order integer not null default 0,
  primary key (off_date, soop_id)
);
create index if not exists calendar_off_air_date_idx on public.calendar_off_air (off_date, source_order);

create table if not exists public.site_config (
  config_key text primary key,
  config_value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.calendar_events enable row level security;
alter table public.calendar_off_air enable row level security;
alter table public.site_config enable row level security;
-- 운영자가 수정하는 연혁 메타데이터. 사진 파일은 Storage(staruniv-media)에 두고 image_path만 저장한다.
create table if not exists public.history_entries (
  id text primary key,
  entry_kind text not null default 'manual' check (entry_kind in ('manual','override')),
  event_date date,
  event_type text,
  title text,
  description text,
  members jsonb not null default '[]'::jsonb,
  youtube_url text,
  image_path text,
  sort_order integer,
  hidden boolean not null default false,
  updated_at timestamptz not null default now()
);
create index if not exists history_entries_date_idx on public.history_entries (event_date desc);

alter table public.history_entries enable row level security;

-- ============================================================================
-- 관리자 인증/RLS
-- ============================================================================

-- StarUniv 관리자용 Auth/RLS 설정
-- 현재 운영 중인 Supabase 프로젝트의 SQL Editor에서 이 파일 전체를 한 번 실행하세요.
-- 실행 후 Authentication > Users 에서 관리자 계정을 만든 다음, 맨 아래 예시 INSERT로 등록합니다.

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'admin' check (role in ('owner', 'admin')),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

-- RLS 정책 안에서 재사용하는 관리자 판별 함수.
-- SECURITY DEFINER로 admin_users 자체의 RLS 순환을 피한다.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users a
    where a.user_id = auth.uid()
      and a.is_active = true
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

-- 로그인한 사용자는 자기 관리자 등록 상태만 읽을 수 있다.
drop policy if exists "admin_users_read_self" on public.admin_users;
create policy "admin_users_read_self"
on public.admin_users
for select
to authenticated
using (user_id = auth.uid());

grant select on public.admin_users to authenticated;

-- 운영 데이터: 관리자만 브라우저에서 CRUD 가능.
do $$
declare
  t text;
begin
  foreach t in array array['settings','teams','members','matches','rounds','tier_members','calendar_events','calendar_off_air','site_config','history_entries']
  loop
    execute format('drop policy if exists %I on public.%I', 'admins_all_' || t, t);
    execute format(
      'create policy %I on public.%I for all to authenticated using (public.is_admin()) with check (public.is_admin())',
      'admins_all_' || t,
      t
    );
  end loop;
end $$;

grant select, insert, update, delete on public.settings, public.teams, public.members,
  public.matches, public.rounds, public.tier_members, public.calendar_events, public.calendar_off_air, public.site_config, public.history_entries to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- ELO 원본은 관리자 화면에서는 조회만 허용한다.
do $$
declare
  t text;
begin
  foreach t in array array['elo_categories','elo_maps','elo_players','elo_matches']
  loop
    execute format('drop policy if exists %I on public.%I', 'admins_read_' || t, t);
    execute format(
      'create policy %I on public.%I for select to authenticated using (public.is_admin())',
      'admins_read_' || t,
      t
    );
  end loop;
end $$;

grant select on public.elo_categories, public.elo_maps, public.elo_players, public.elo_matches to authenticated;

-- 경기 + 세트를 한 트랜잭션으로 저장한다.
-- 기존 경기를 수정할 때는 source_order를 유지하고, 세트 목록은 전달된 내용으로 교체한다.
create or replace function public.admin_save_match(p_match jsonb, p_rounds jsonb default '[]'::jsonb)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_match_no integer;
  v_source_order integer;
  v_round_source integer;
  r jsonb;
begin
  if not public.is_admin() then
    raise exception 'admin only';
  end if;

  v_match_no := nullif(p_match->>'match_no', '')::integer;
  if v_match_no is null then
    select coalesce(max(match_no), 0) + 1 into v_match_no from public.matches;
  end if;

  v_source_order := nullif(p_match->>'source_order', '')::integer;
  if v_source_order is null then
    select coalesce(max(source_order), 0) + 1 into v_source_order from public.matches;
  end if;

  insert into public.matches (
    match_no, source_order, match_date, opponent_team, match_format, method,
    final_result, set_result, score_diff, funding, support_amount, personal_amount, challenge_mission
  ) values (
    v_match_no,
    v_source_order,
    nullif(p_match->>'match_date','')::date,
    nullif(p_match->>'opponent_team',''),
    nullif(p_match->>'match_format',''),
    nullif(p_match->>'method',''),
    nullif(p_match->>'final_result',''),
    nullif(p_match->>'set_result',''),
    nullif(p_match->>'score_diff',''),
    nullif(p_match->>'funding',''),
    nullif(p_match->>'support_amount',''),
    nullif(p_match->>'personal_amount',''),
    nullif(p_match->>'challenge_mission','')
  )
  on conflict (match_no) do update set
    source_order = excluded.source_order,
    match_date = excluded.match_date,
    opponent_team = excluded.opponent_team,
    match_format = excluded.match_format,
    method = excluded.method,
    final_result = excluded.final_result,
    set_result = excluded.set_result,
    score_diff = excluded.score_diff,
    funding = excluded.funding,
    support_amount = excluded.support_amount,
    personal_amount = excluded.personal_amount,
    challenge_mission = excluded.challenge_mission;

  delete from public.rounds where match_no = v_match_no;
  select coalesce(max(source_order), 0) into v_round_source from public.rounds;

  for r in select value from jsonb_array_elements(coalesce(p_rounds, '[]'::jsonb))
  loop
    v_round_source := v_round_source + 1;
    insert into public.rounds (
      source_order, match_no, match_date, opponent_team, match_format,
      set_name, round_name, our_player, our_race, our_tier, result,
      opponent_player, opponent_race, opponent_tier, map_name
    ) values (
      v_round_source,
      v_match_no,
      nullif(coalesce(r->>'match_date', p_match->>'match_date'),'')::date,
      nullif(coalesce(r->>'opponent_team', p_match->>'opponent_team'),''),
      nullif(coalesce(r->>'match_format', p_match->>'match_format'),''),
      nullif(r->>'set_name',''),
      nullif(r->>'round_name',''),
      nullif(r->>'our_player',''),
      nullif(r->>'our_race',''),
      nullif(r->>'our_tier',''),
      nullif(r->>'result',''),
      nullif(r->>'opponent_player',''),
      nullif(r->>'opponent_race',''),
      nullif(r->>'opponent_tier',''),
      nullif(r->>'map_name','')
    );
  end loop;

  return v_match_no;
end;
$$;

revoke all on function public.admin_save_match(jsonb, jsonb) from public;
grant execute on function public.admin_save_match(jsonb, jsonb) to authenticated;

-- 관리자 계정 등록 예시
-- 1) Authentication > Users > Add user 로 이메일/비밀번호 계정을 만든 뒤
-- 2) 아래 EMAIL 부분만 바꾸고 실행하세요.
-- insert into public.admin_users (user_id, role)
-- select id, 'owner' from auth.users where email = 'YOUR_ADMIN_EMAIL@example.com'
-- on conflict (user_id) do update set role = excluded.role, is_active = true;

-- ============================================================================
-- 캘린더/휴방/메뉴 데이터
-- ============================================================================

-- StarUniv 일정/휴방/메뉴 설정을 정적 JSON에서 Supabase로 옮기는 1회 마이그레이션.
-- Supabase SQL Editor에서 이 파일 전체를 실행하세요. 여러 번 실행해도 안전하도록 작성했습니다.

create table if not exists public.calendar_events (
  id bigint primary key,
  source_order integer not null unique,
  start_date date not null,
  end_date date not null,
  event_time text,
  person text not null default '',
  description text,
  detail text,
  color text
);
create index if not exists calendar_events_date_idx on public.calendar_events (start_date, end_date);

create table if not exists public.calendar_off_air (
  off_date date not null,
  soop_id text not null,
  source_order integer not null default 0,
  primary key (off_date, soop_id)
);
create index if not exists calendar_off_air_date_idx on public.calendar_off_air (off_date, source_order);

create table if not exists public.site_config (
  config_key text primary key,
  config_value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.calendar_events enable row level security;
alter table public.calendar_off_air enable row level security;
alter table public.site_config enable row level security;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788410176657,1,'2026-09-03'::date,'2026-09-03'::date,'19:00','중만컵','흑카 vs JSA','','#9aa6ba') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788410523229,2,'2026-09-01'::date,'2026-09-01'::date,'','두두','생일','','#ff2538') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788410553136,3,'2026-09-01'::date,'2026-09-01'::date,'20:00','윤환','한중전','','#16c75b') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788410538904,4,'2026-09-02'::date,'2026-09-02'::date,'16:00','낭니','낭피엘','','#ff2538') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788411375531,5,'2026-09-02'::date,'2026-09-03'::date,'비방연습','캄몬','','','#1677ff') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788411859497,6,'2026-09-04'::date,'2026-09-04'::date,'19:00','중만컵','캄몬 vs 케이대','','#1677ff') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788534153554,7,'2026-09-04'::date,'2026-09-04'::date,'21:30','캄몬','재계약','','#1677ff') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788411895026,8,'2026-09-05'::date,'2026-09-05'::date,'19:00','중만컵','뉴캣슬 vs 수술대','','#9aa6ba') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788411922758,9,'2026-09-06'::date,'2026-09-06'::date,'19:00','중만컵','DM vs 엠비대','','#9aa6ba') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788411935742,10,'2026-09-06'::date,'2026-09-06'::date,'19:00','윤환','중만컵 해설','','#16c75b') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788411971561,11,'2026-09-07'::date,'2026-09-07'::date,'19:00','ASL22','16강 A조','짭제 윤중 재욱 영진','#9aa6ba') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788839808275,12,'2026-09-07'::date,'2026-09-07'::date,'30:00','암벽토먼','할없사 낚시','하랑 합류','#1677ff') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788412030098,13,'2026-09-08'::date,'2026-09-08'::date,'19:00','ASL22','16강 B조','상문 경모 제동 명운','#9aa6ba') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788839871844,14,'2026-09-08'::date,'2026-09-08'::date,'14:00','조이','단양 여행','','#ff2538') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788844188701,15,'2026-09-08'::date,'2026-09-08'::date,'16:00','낭니먼진','낭먼이 간다','','#ff2538') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788412051970,16,'2026-09-12'::date,'2026-09-12'::date,'19:00','중만컵','JSA vs 케이대','4강 A조','#9aa6ba') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788412068202,17,'2026-09-13'::date,'2026-09-13'::date,'19:00','중만컵','뉴캣슬 vs DM','4강 B조','#9aa6ba') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788412315390,18,'2026-09-14'::date,'2026-09-14'::date,'19:00','ASL22','16강 C조 민철','재호 영재 민철 일장','#1677ff') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788412376276,19,'2026-09-15'::date,'2026-09-15'::date,'19:00','ASL22','16강 D조','윤철 재현 영한 정우','#9aa6ba') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788412389986,20,'2026-09-19'::date,'2026-09-19'::date,'18:00','중만컵','케이대 vs 뉴캣슬','결승','#9aa6ba') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788951874127,21,'2026-09-20'::date,'2026-09-21'::date,'17:00','캄몬','24시간','','#1677ff') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1788972694118,22,'2026-09-09'::date,'2026-09-09'::date,'20:00','민철','코려대CK','','#ff2538') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789013686147,23,'2026-10-03'::date,'2026-10-03'::date,'시간미정','캄몬','팬미팅','','#1677ff') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789025508217,24,'2026-09-10'::date,'2026-09-10'::date,'16:00','햇살','24시간','','#ff2538') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789025526568,25,'2026-09-10'::date,'2026-09-10'::date,'19:00','하랑','테라스 먹방','','#ff2538') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789025567961,26,'2026-09-12'::date,'2026-09-12'::date,'23:00','타밍송이','장판빵 멸망전','윤환 사테 준오','#1677ff') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789100083799,27,'2026-09-11'::date,'2026-09-11'::date,'20:00','윤환','클암CK','','#16c75b') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789186098219,28,'2026-09-12'::date,'2026-09-12'::date,'16:00','낭니','도낭CK','','#ff2538') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789304358823,29,'2026-09-13'::date,'2026-09-13'::date,'22:00','윤환','랜피엘','','#16c75b') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789486342994,30,'2026-09-14'::date,'2026-09-14'::date,'03:30','왜냐맨','블리즈컨','','#ff2538') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789491611046,31,'2026-09-15'::date,'2026-09-15'::date,'24:00','캄몬','롤 내전','','#1677ff') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789537435699,32,'2026-09-13'::date,'2026-09-13'::date,'24:00','두랑먼낭','할업사 주겹살','','#ff2538') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789541321693,33,'2026-09-16'::date,'2026-09-16'::date,'15:00','타밍','낚시 노방종','','#ff2538') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789545339863,34,'2026-09-16'::date,'2026-09-16'::date,'18:00','먼진','더블끝장전','먼진핑핑 vs 정은츄빈','#ff2538') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789624331731,35,'2026-09-17'::date,'2026-09-17'::date,'15:00','준오송이','스튜디오 장판교체','','#1677ff') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789733765026,36,'2026-09-18'::date,'2026-09-18'::date,'20:00','캄몬','단체종겜','','#1677ff') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789802440354,37,'2026-09-19'::date,'2026-09-19'::date,'16:00','마토','장휴 복귀','','#ff2538') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1789806002308,38,'2026-09-19'::date,'2026-09-19'::date,'15:00','두두','글램핑 으냉','','#ff2538') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1790056481809,39,'2026-09-21'::date,'2026-09-21'::date,'19:00','ASL22','이영한 VS 유영진','8강 1경기','#9aa6ba') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1790056567014,40,'2026-09-22'::date,'2026-09-22'::date,'19:00','ASL22','이재호 VS 김정우','8강 2경기','#9aa6ba') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1790056611485,41,'2026-09-28'::date,'2026-09-28'::date,'19:00','ASL22','박상현 VS 이제동','8강 3경기','#9aa6ba') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1790056654300,42,'2026-09-29'::date,'2026-09-29'::date,'19:00','ASL22','신상문 VS 김민철','8강 4경기','#1677ff') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_events (id,source_order,start_date,end_date,event_time,person,description,detail,color) values (1790058669984,43,'2026-09-22'::date,'2026-09-22'::date,'21:00','햇살','4티어 PL','','#ff2538') on conflict (id) do update set source_order=excluded.source_order,start_date=excluded.start_date,end_date=excluded.end_date,event_time=excluded.event_time,person=excluded.person,description=excluded.description,detail=excluded.detail,color=excluded.color;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-10'::date,'brainzerg7',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-10'::date,'freshtomato',2) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-10'::date,'rnaqpdrjf',3) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-10'::date,'dlaguswl501',4) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-10'::date,'vldpfm2',5) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-10'::date,'sksmsskdsl10',6) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-09'::date,'brainzerg7',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-09'::date,'rnaqpdrjf',2) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-09'::date,'wjswlgns09',3) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-09'::date,'thelddl',4) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-09'::date,'fpahsdltu1',5) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-09'::date,'seemin88',6) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-11'::date,'freshtomato',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-11'::date,'rnaqpdrjf',2) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-11'::date,'dlaguswl501',3) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-11'::date,'2meonjin',4) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-12'::date,'freshtomato',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-12'::date,'rnaqpdrjf',2) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-12'::date,'dlaguswl501',3) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-12'::date,'wjswlgns09',4) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-12'::date,'thelddl',5) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-13'::date,'freshtomato',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-13'::date,'rnaqpdrjf',2) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-13'::date,'dlaguswl501',3) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-14'::date,'freshtomato',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-14'::date,'rnaqpdrjf',2) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-14'::date,'dlaguswl501',3) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-15'::date,'freshtomato',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-15'::date,'dlaguswl501',2) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-15'::date,'rnaqpdrjf',3) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-16'::date,'freshtomato',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-16'::date,'dlaguswl501',2) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-16'::date,'brainzerg7',3) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-16'::date,'sksmsskdsl10',4) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-17'::date,'dlaguswl501',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-17'::date,'brainzerg7',2) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-17'::date,'freshtomato',3) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-17'::date,'wjswlgns09',4) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-18'::date,'brainzerg7',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-18'::date,'freshtomato',2) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-18'::date,'thelddl',3) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-18'::date,'dlaguswl501',4) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-18'::date,'vldpfm2',5) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-18'::date,'sksmsskdsl10',6) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-19'::date,'brainzerg7',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-19'::date,'dlaguswl501',2) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-19'::date,'soju2022',3) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-19'::date,'vldpfm2',4) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-19'::date,'fpahsdltu1',5) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-20'::date,'brainzerg7',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-21'::date,'brainzerg7',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-22'::date,'brainzerg7',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-23'::date,'brainzerg7',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-24'::date,'brainzerg7',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-25'::date,'brainzerg7',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-26'::date,'brainzerg7',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-27'::date,'brainzerg7',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-28'::date,'brainzerg7',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-29'::date,'brainzerg7',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;
insert into public.calendar_off_air (off_date,soop_id,source_order) values ('2026-09-30'::date,'brainzerg7',1) on conflict (off_date,soop_id) do update set source_order=excluded.source_order;

insert into public.site_config (config_key,config_value) values ('nav','{"hidden":[],"statsTabs":["balloons"],"heroDescriptions":{}}'::jsonb) on conflict (config_key) do update set config_value=excluded.config_value, updated_at=now();

-- 공개 사이트 읽기 권한
revoke all on public.calendar_events, public.calendar_off_air, public.site_config from anon;
grant select (id,source_order,start_date,end_date,event_time,person,description,detail,color) on public.calendar_events to anon;
grant select (off_date,soop_id,source_order) on public.calendar_off_air to anon;
grant select (config_key,config_value) on public.site_config to anon;

drop policy if exists "public_read_calendar_events" on public.calendar_events;
create policy "public_read_calendar_events" on public.calendar_events for select to anon using (true);
drop policy if exists "public_read_calendar_off_air" on public.calendar_off_air;
create policy "public_read_calendar_off_air" on public.calendar_off_air for select to anon using (true);
drop policy if exists "public_read_site_config" on public.site_config;
create policy "public_read_site_config" on public.site_config for select to anon using (config_key = 'nav');

-- 관리자 CRUD. admin.sql의 public.is_admin()이 먼저 설치되어 있어야 합니다.
do $$
declare t text;
begin
  foreach t in array array['calendar_events','calendar_off_air','site_config']
  loop
    execute format('drop policy if exists %I on public.%I', 'admins_all_' || t, t);
    execute format(
      'create policy %I on public.%I for all to authenticated using (public.is_admin()) with check (public.is_admin())',
      'admins_all_' || t, t
    );
  end loop;
end $$;

grant select, insert, update, delete on public.calendar_events, public.calendar_off_air, public.site_config to authenticated;

-- ============================================================================
-- 연혁/미디어 Storage
-- ============================================================================

-- StarUniv 운영 콘텐츠/미디어 하이브리드 전환
-- 1) 운영 메타데이터는 DB, 업로드 파일은 Storage, 디자인 고정 자산은 Git에 둔다.
-- 2) 이 파일은 재실행해도 기존 운영 수정값을 덮어쓰지 않는다.

alter table public.members add column if not exists avatar_path text;
alter table public.teams add column if not exists logo_path text;

create table if not exists public.history_entries (
  id text primary key,
  entry_kind text not null default 'manual' check (entry_kind in ('manual','override')),
  event_date date, event_type text, title text, description text,
  members jsonb not null default '[]'::jsonb, youtube_url text, image_path text,
  sort_order integer, hidden boolean not null default false, updated_at timestamptz not null default now()
);
alter table public.history_entries enable row level security;

-- 공개 Storage 버킷. URL은 공개지만 쓰기/삭제는 관리자만 가능하다.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('staruniv-media','staruniv-media',true,10485760,array['image/jpeg','image/png','image/webp','image/gif'])
on conflict (id) do update set public=excluded.public, file_size_limit=excluded.file_size_limit, allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "staruniv_media_public_read" on storage.objects;
create policy "staruniv_media_public_read" on storage.objects for select to public using (bucket_id='staruniv-media');
drop policy if exists "staruniv_media_admin_insert" on storage.objects;
create policy "staruniv_media_admin_insert" on storage.objects for insert to authenticated with check (bucket_id='staruniv-media' and public.is_admin());
drop policy if exists "staruniv_media_admin_update" on storage.objects;
create policy "staruniv_media_admin_update" on storage.objects for update to authenticated using (bucket_id='staruniv-media' and public.is_admin()) with check (bucket_id='staruniv-media' and public.is_admin());
drop policy if exists "staruniv_media_admin_delete" on storage.objects;
create policy "staruniv_media_admin_delete" on storage.objects for delete to authenticated using (bucket_id='staruniv-media' and public.is_admin());

-- 현재 history.json 메타데이터를 최초 1회 시드한다. 운영 DB에 이미 같은 id가 있으면 건드리지 않는다.
insert into public.history_entries (id,entry_kind,event_date,event_type,title,description,members,youtube_url,image_path,sort_order,hidden) values
('h-founding', 'manual', '2024-07-08', 'founding', '츠캄 몬스타즈 창단', '', '["김윤환(감독)", "이경민(감독)"]'::jsonb, 'https://youtu.be/AUVSbE3CJPk?si=sp0XotYnl7vMNuY2', null, 1, false),
('h-mu6xzcc5', 'manual', '2024-09-01', 'broadcast', '츠캄 몬스타즈 창단식', '', '["김윤환", "이경민", "디임", "졈니", "앵지", "토마토", "임조이", "효짱", "한쪼니", "몽군", "모리", "치리", "강덕구", "클템"]'::jsonb, 'https://youtu.be/Wee70wXys_c?si=5ZijExlkYo-_xEzz', null, 0, false),
('h-mu8l836x', 'manual', '2024-09-08', 'event', '첫 대학대전', '', '["앵지", "강덕구", "졈니", "토마토", "치리", "디임", "모리"]'::jsonb, 'https://youtu.be/fOt_dRg5C_Y?si=WSLgxGmfRFNQKx2W', null, null, false),
('h-mu8lfnto', 'manual', '2024-09-14', 'broadcast', '추석특집 전부치기', '', '["강덕구", "김윤환", "이경민", "디임", "토마토", "졈니", "치리", "모리", "임조이", "효짱", "한쪼니", "몽군"]'::jsonb, 'https://youtu.be/YBYHN2ZmGzA?si=z_Cgcpf19wHFqpZ3', null, null, false),
('h-mu8ljyfb', 'manual', '2024-10-08', 'broadcast', '알탕즈 낚시방송', '', '["김윤환", "몽군", "수입뿌드"]'::jsonb, 'https://youtu.be/33PqXjSe-Wo?si=rAVAfB_pAAjEoXwB', null, null, false),
('h-mu8ll7n0', 'manual', '2024-10-16', 'broadcast', '첫 MT', '2024-10-16 ~ 2024-10-17', '["김윤환", "이경민", "디임", "토마토", "앵지", "졈니", "치리", "모리", "임조이", "효짱", "한쪼니", "몽군", "수입뿌드"]'::jsonb, 'https://youtu.be/_1FjsDpUf0s?si=i3-F8UKCQIa1izlq', null, null, false),
('h-mu8rbkfo', 'manual', '2024-10-26', 'event', '대학대전 0승 4패 직면', '', '["디임", "앵지", "임조이", "모리", "졈니", "치리"]'::jsonb, 'https://youtu.be/9f-g3d_VeBM?si=UB7aHuLzD1NCgZDm', null, null, false),
('h-mu8rj1ab', 'manual', '2024-10-27', 'broadcast', '국토 벌칙', '2024-10-27 ~ 2024-10-30', '["김윤환", "이경민", "몽군", "정윤종", "주서리", "김성대", "지동원", "이유란", "효짱"]'::jsonb, 'https://youtu.be/Qk8H63liFII?si=HsEqv3OkKr31R3zY', null, null, false),
('h-mu8rz3yn', 'manual', '2024-12-23', 'match', '라네트배 스타대학대전 우승', '2024-11-24 ~ 2024-12-23', '["김윤환", "이경민", "정윤종", "몽군", "박준오", "수입뿌드", "세나", "디임", "토마토", "앵지", "졈니", "치리", "모리", "임조이", "효짱", "한쪼니"]'::jsonb, 'https://youtu.be/CvT2Tvgm09o?si=JyetpWvBXJumF2Uk', null, null, false),
('h-mu8sa6va', 'manual', '2024-11-11', 'broadcast', '아차산 등산 벌칙', '', '["김윤환", "정윤종", "앵지", "졈니", "모리", "효짱", "한쪼니"]'::jsonb, 'https://youtu.be/wQsiFxOMens?si=BLxvi165eQTnnYhN', null, null, false),
('h-mu8sh2t3', 'manual', '2024-11-24', 'match', '첫 대회, 첫 승', '', '["세나", "디임", "토마토", "졈니", "치리", "임조이"]'::jsonb, 'https://youtu.be/sveWh1Abl2o?si=TK4p--0s77oBWxGv', null, null, false),
('h-mu97ug6f', 'manual', '2025-01-15', 'broadcast', '이경민 생일 술먹방', '', '["이경민", "김윤환", "정윤종", "수입뿌드"]'::jsonb, 'https://youtu.be/8n_Rcmhzvvo?si=e5q__N4TiBeRIfrI', null, null, false),
('h-mu982lgs', 'manual', '2025-01-30', 'broadcast', '설특집 전부치기', '', '["김윤환", "정윤종", "앵지", "임조이", "효짱", "한쪼니", "모리", "세나"]'::jsonb, 'https://youtu.be/NMpN0UPAzBY?si=BxOjIhRd8lv7osn2', null, null, false),
('h-mu9843mu', 'manual', '2025-02-04', 'broadcast', '세모카세', '', '["세나", "김윤환", "이경민", "정윤종"]'::jsonb, 'https://youtu.be/dQ-QcUegmWw?si=kdjPApe9ciP8L1om', null, null, false),
('h-mu988mlu', 'manual', '2025-02-06', 'broadcast', '쪼징어게임2', '', '["한쪼니", "김윤환", "이경민", "정윤종", "수입뿌드"]'::jsonb, 'https://youtu.be/9qq7ANI1r_M?si=pBmSaMNB6xcbMjj8', null, null, false),
('h-mu98fmbs', 'manual', '2025-02-07', 'broadcast', '츠캄 시즌2 MT', '2025-02-07 ~ 2025-02-08', '["김윤환", "이경민", "정윤종", "세나", "토마토", "앵지", "치리", "임조이", "모리", "효짱", "한쪼니", "몽군", "박준오", "수입뿌드"]'::jsonb, 'https://youtu.be/-Avr1XBR9lk?si=sDOp3H2hgjJwaK63', null, null, false),
('h-mu98j6m9', 'manual', '2025-02-17', 'broadcast', '연봉협상', '', '["김윤환", "이경민", "정윤종", "세나", "토마토", "앵지", "졈니", "치리", "임조이", "모리", "효짱", "한쪼니", "몽군", "박준오", "수입뿌드"]'::jsonb, 'https://youtu.be/a3nEBqT1kG4?si=n7q96x0WlLc4wH8K', null, null, false),
('h-mu98ni4c', 'manual', '2025-02-25', 'broadcast', 'JPL2 프로필 촬영', '', '["김윤환", "이경민", "정윤종", "세나", "토마토", "졈니", "앵지", "치리", "임조이", "모리", "효짱", "한쪼니", "진땅콩 T", "몽군", "박준오", "수입뿌드"]'::jsonb, 'https://youtu.be/LKhQyF5PJ1U?si=3pvyRkCQnjtGqsHT', null, null, false),
('h-mu98qalt', 'manual', '2025-03-13', 'match', '츠캄 JPL2 첫 경기', '', '["다예", "졈니", "한쪼니", "모리", "몽군", "앵지"]'::jsonb, 'https://youtu.be/jcVVnj3vGwE?si=xOvWEfitfeBz6mod', null, null, false),
('h-mu98xwft', 'manual', '2025-03-21', 'broadcast', '코치진 술먹방', '', '["김윤환", "이경민", "정윤종", "몽군", "수입뿌드"]'::jsonb, 'https://youtu.be/Spuu2WhQub0?si=jxD6KTXOMDAZu2yF', null, null, false),
('h-mu9904ch', 'manual', '2025-05-13', 'event', '스승의 날 CK', '', '["김윤환", "수입뿌드", "정윤종", "몽군", "이경민", "박준오"]'::jsonb, 'https://youtu.be/8sURAdwGFo0?si=YkYVd8nNjiVUTStP', null, null, false),
('h-mu992sj2', 'manual', '2025-05-24', 'broadcast', '암앵돌풍 더블 데이트', '', '["김윤환", "앵지", "이유란", "김성대"]'::jsonb, 'https://youtu.be/AX-tgeFqvDA?si=_BdQRrdMbsvNvbhb', null, null, false),
('h-mu994xxs', 'manual', '2025-06-14', 'broadcast', '김윤환을 이겨라', '', '["김윤환", "주하랑", "졈니", "임조이", "다예", "수입뿌드", "오리3", "히엉", "귀요민정"]'::jsonb, 'https://youtu.be/QxK7-EhVt_g?si=EUNuc-uZCZeOBYJ_', null, null, false),
('h-mu9966nb', 'manual', '2025-06-15', 'event', '시빌워', '', '["김윤환", "이경민", "정윤종", "박준오", "수입뿌드", "세나", "토마토", "앵지", "임조이", "효짱", "모리", "치리", "막내현진", "한쪼니", "다예", "오리3"]'::jsonb, 'https://youtu.be/gQVfZQTCOqE?si=vWp_8zcDFuhx3kdC', null, null, false),
('h-mu997bk0', 'manual', '2025-06-21', 'broadcast', '최가네 불편한스타', '', '["김윤환", "김윤중", "란란", "로링", "이지각", "유은", "두돈반"]'::jsonb, 'https://youtu.be/BU9IED2ksD4?si=qydXYIIXaEQazP9u', null, 1, false),
('h-mu998czs', 'manual', '2025-06-21', 'broadcast', '암점 종겜대전', '', '["김윤환", "김윤중"]'::jsonb, 'https://youtu.be/ZIn-AR71uYw?si=wF9_izpMhYw1MbIa', null, 0, false),
('h-mu99d7s4', 'manual', '2025-07-13', 'match', '시조새배 JPL 시즌2 3위', '2025-03-08 ~ 2025-07-16', '["김윤환", "이경민", "정윤종", "몽군", "박준오", "수입뿌드", "세나", "토마토", "다예", "졈니", "앵지", "치리", "임조이", "모리", "효짱", "한쪼니", "막내현진"]'::jsonb, 'https://youtu.be/CmCAu1Z-xTM?si=RRtJwvQ5TPq_Hf_h', null, null, false),
('h-mu9cq534', 'manual', '2025-01-18', 'broadcast', '세나 결혼', '', '["세나"]'::jsonb, 'https://youtu.be/QhxOsoXCH5A?si=vPWjznJFxB36QCpJ', null, null, false),
('h-mu9dcg2r', 'manual', '2025-08-06', 'broadcast', '츠캄 풋살', '', '["김윤환", "이경민", "정윤종", "조일장", "황병영", "박준오", "수입뿌드", "진땅콩", "모리", "시조새", "몽군", "지동원", "정영재", "방태수", "전태양", "김성대", "빡죠스"]'::jsonb, 'https://youtu.be/5AeDjMWIvXA?si=Dithcaebgf7hsm14', null, null, false),
('h-mu9dnn6x', 'manual', '2025-08-09', 'event', '코치CK', 'VS 이노대 왁싱 벌칙빵', '["박준오", "이경민", "황병영", "지동원", "김윤환", "정윤종", "조일장"]'::jsonb, 'https://youtu.be/6UlIfeJHLO0?si=OsTggefmpd4tWqis', null, null, false),
('h-mu9dok0t', 'manual', '2025-08-10', 'broadcast', '왁싱 벌칙', '', '["김윤환", "지동원", "김성대"]'::jsonb, 'https://youtu.be/f-lyC6eoVeE?si=x7045AJbN4CAIqHn', null, null, false),
('h-mu9dt2z5', 'manual', '2025-08-13', 'broadcast', '츠캄 시즌3 MT', '2025-08-13 ~ 2025-08-15', '["김윤환", "이경민", "정윤종", "토마토", "다예", "햇살", "두디", "주하랑", "치리", "임조이", "막내현진", "진땅콩", "조일장", "황병영", "지동원", "수입뿌드"]'::jsonb, 'https://youtu.be/Srssj7p8d-I?si=_jTK7k_WR7u6lArA', null, null, false),
('h-mu9e0jur', 'manual', '2025-08-16', 'event', '한중전', '', '["김윤환", "이경민", "지동원"]'::jsonb, 'https://youtu.be/cRy4TzENFwY?si=vOBUr1fxCHh0bvDr', null, null, false),
('h-mu9e7706', 'manual', '2025-08-20', 'broadcast', '종아리 신길동짬뽕 벌칙', '', '["김윤환", "이경민", "정윤종", "김성대"]'::jsonb, 'https://youtu.be/a5rnB4twtZ4?si=pGWVfg22hQWloWwR', null, 1, false),
('h-mu9e9qsx', 'manual', '2025-08-20', 'broadcast', '츠캄 VS 이노대 종겜대전', '', '["김윤환", "주하랑", "치리", "모리", "박준오", "지동원", "림예이", "연수", "비타밍", "김성대", "임진묵", "윤수철"]'::jsonb, 'https://youtu.be/7avx-ZE_scU?si=7MC9BwHmwc1hq5lV', null, 0, false),
('h-mu9ed46i', 'manual', '2025-08-31', 'broadcast', '토스반 갈먹CK', '', '["김윤환", "정윤종", "토마토", "주하랑", "막내현진", "진땅콩", "지동원"]'::jsonb, 'https://youtu.be/HAA9zs3tkBA?si=qgyznNWi_I2rNGQE', null, null, false),
('h-mu9efdqr', 'manual', '2025-09-03', 'broadcast', '빠지 여행', '2025-09-03 ~ 2025-09-04', '["김윤환", "이경민", "정윤종", "다예", "토마토", "햇살", "두디", "주하랑", "치리", "임조이", "모리", "막내현진", "진땅콩", "조일장", "황병영", "박준오", "지동원", "수입뿌드"]'::jsonb, 'https://youtu.be/jZGLTrGajsE?si=Y7U6zbXjlsA-3qN-', null, null, false),
('h-mu9eo8el', 'manual', '2025-09-06', 'broadcast', '저그반 흉가CK', '', '["김윤환", "다예", "두디", "치리", "임조이", "조일장", "박준오", "지동원", "란란"]'::jsonb, 'https://youtu.be/-AZXMFTLKIg?si=jN18PGNEg3nKJDiZ', null, null, false),
('h-mu9epsve', 'manual', '2025-09-10', 'broadcast', '조살포차', '', '["임조이", "김윤환", "정윤종", "박준오", "치리"]'::jsonb, 'https://youtu.be/35xGr9CFrQ4?si=0N2okdym_9eOaaa6', null, null, false),
('h-mu9eslf0', 'manual', '2025-09-15', 'broadcast', '메이드 카페 벌칙', '', '["김윤환", "이경민", "조일장", "지동원"]'::jsonb, 'https://youtu.be/QZTeMHnq3Xs?si=QWyeluR8h9INnGho', null, null, false),
('h-mu9evd06', 'manual', '2025-09-18', 'broadcast', '스타마블', '', '["김윤환", "토마토", "두디", "지동원"]'::jsonb, 'https://youtu.be/qc69GYL9Wes?si=X-Vnk9qwgyzkAw_8', null, null, false),
('h-mu9f2l1w', 'manual', '2025-09-30', 'event', '시빌워', '', '["김윤환", "이경민", "정윤종", "박준오", "조일장", "황병영", "토마토", "다예", "햇살", "두디", "주하랑", "소주양", "임조이", "치리", "모리", "막내현진", "진땅콩"]'::jsonb, 'https://youtu.be/GiiMTw8Kn0Y?si=FFvGGaNhZLlEtTH5', null, null, false),
('h-mu9f4ro7', 'manual', '2025-10-04', 'broadcast', '24시간 벌칙 방송', '시빌워 벌칙', '["김윤환", "이경민", "정윤종", "다예", "두디", "치리", "주하랑", "막내현진", "진땅콩", "조일장", "지동원", "흑운장", "카히리", "기뉴다", "늑대채린"]'::jsonb, 'https://youtu.be/wZxsNY9Y7W8?si=-UkHMmUFIVQTdwh9', null, null, false),
('h-mu9f8gwk', 'manual', '2025-10-29', 'match', 'SOOP 스타대학리그 2025 조별예선 탈락', '2025-10-26  ~ 2025-11-23', '["김윤환", "이경민", "정윤종", "조일장", "황병영", "박준오", "수입뿌드", "토마토", "다예", "햇살", "두디", "치리", "주하랑", "소주양", "임조이", "모리", "막내현진", "진땅콩"]'::jsonb, 'https://youtu.be/D1MW4zeQokI?si=L4MqZCiVwqBiovxq', null, 1, false),
('h-mu9fh32l', 'manual', '2025-10-30', 'broadcast', '알탕즈 시즌2', '', '["김윤환", "정윤종", "황병영", "지동원", "수입뿌드"]'::jsonb, 'https://youtu.be/OmUfq2iCKuk?si=yOSyiHl3iu4jilSW', null, null, false),
('h-mu9fms54', 'manual', '2025-11-03', 'broadcast', '국토', '2025-11-03 ~ 2025-11-07', '["김윤환", "이경민", "정윤종", "지동원", "수입뿌드", "클템", "란란", "해기", "치리", "진땅콩", "소주양", "토마토", "다예", "주하랑", "임조이"]'::jsonb, 'https://youtu.be/04S2P1IumIk?si=LarKpGMCIbVT2lSs', null, null, false),
('h-mu9fqstd', 'manual', '2025-06-16', 'broadcast', '릴레이 국토', '시빌워 벌칙', '["정윤종", "김봉준", "효짱", "강구열", "앵지", "란란", "치리", "라미", "오리3", "이채이", "세나", "이예훈", "한쪼니", "쟈닌", "이경민", "다뉴"]'::jsonb, '', null, null, false),
('h-mu9goxx0', 'manual', '2025-11-11', 'broadcast', '성심당 오픈런', '할없사 벌칙', '["김윤환", "햇살", "주하랑", "진땅콩", "파도튜브"]'::jsonb, 'https://youtu.be/E5pXHOBM_ts?si=rbaKfK3noD31DV24', null, null, false),
('h-mu9gs0ua', 'manual', '2025-12-04', 'broadcast', '노량진 합방', '홍어 벌칙', '["김윤환", "치리", "주하랑", "소주양", "임조이", "진땅콩", "조일장", "황병영", "박준오", "지동원", "파도튜브", "수입뿌드"]'::jsonb, 'https://youtu.be/DnU0wyfRktE?si=Aa-fxiCKrOp3-H5u', null, null, false),
('h-mu9gyb17', 'manual', '2025-12-20', 'broadcast', '츠캄 VS 이노대 운동회', '', '["김윤환", "정윤종", "토마토", "다예", "햇살", "치리", "주하랑", "소주양", "막내현진", "진땅콩", "박쭈이", "박준오", "지동원", "파도튜브", "수입뿌드"]'::jsonb, 'https://youtu.be/UCrGE9QhfYE?si=VHiARUMtaMNYCxde', null, null, false),
('h-mu9h2ke4', 'manual', '2025-12-27', 'broadcast', 'SOOP 스트리머 대상 시상식', '', '["김윤환", "이경민", "정윤종"]'::jsonb, 'https://youtu.be/4gQHhD040Mw?si=7DZa8S6ZjhRU48QH', null, null, false),
('h-mu9hhn45', 'manual', '2026-01-01', 'broadcast', '72시간 노방종', '2026-01-01 ~ 2026-01-03', '["토마토", "다예", "햇살", "치리", "주하랑", "소주양", "임조이", "진땅콩", "박쭈이", "지동원", "수입뿌드"]'::jsonb, 'https://youtu.be/S0lgphpmiGg?si=gLsbG5goDV3LNmGU', null, null, false),
('h-mu9hksk4', 'manual', '2026-01-15', 'broadcast', '이경민 생일 술먹방', '', '["이경민", "김윤환", "토마토", "치리", "주하랑", "진땅콩"]'::jsonb, 'https://youtu.be/UcHyZ9K4koA?si=fTxULwaAnYQDM8kS', null, null, false),
('h-mu9hnthn', 'manual', '2026-01-13', 'broadcast', '목욕탕 컨텐츠', '', '["진땅콩", "토마토", "다예", "햇살", "치리", "주하랑", "소주양", "임조이", "박쭈이", "수입뿌드"]'::jsonb, 'https://youtu.be/gR6GSy-Ys-s?si=pPPp8NgPFIK2zAyL', null, null, false),
('h-mu9hsvmy', 'manual', '2026-01-24', 'broadcast', '흑스타즈 VS 암카데미', '', '["김윤환", "수입뿌드", "토마토", "임조이", "진땅콩", "흑운장", "몽군", "뚜미", "갱이다", "링가"]'::jsonb, 'https://youtu.be/rU2lJVrB2rI?si=C4ZApvJ-ZJ8hZYjz', null, null, false),
('h-mu9hyaaw', 'manual', '2026-01-31', 'broadcast', '붕어빵 카페', '', '["김윤환", "이경민", "토마토", "햇살", "소주양", "주하랑", "치리", "임조이", "먼진", "진땅콩", "조일장", "황병영", "박준오", "박수범", "배성흠", "지동원", "파도튜브", "수입뿌드"]'::jsonb, 'https://youtu.be/uxMhoaZMNx4?si=uF184J6ZcqIDBw3b', null, null, false),
('h-mu9i65gw', 'manual', '2026-02-13', 'broadcast', '설특집 츠캄요리사', '', '["김윤환", "이경민", "주하랑", "소주양", "치리", "진땅콩", "지동원"]'::jsonb, 'https://youtu.be/BYfilwm-Sdk?si=KEwfIOeO-T8Y-k37', null, null, false),
('h-mu9if3lm', 'manual', '2026-03-14', 'match', '정선숲퍼컵 8강', '2026-02-24 ~ 2026-03-21', '["김윤환", "이경민", "조일장", "황병영", "박준오", "박수범", "배성흠", "지동원", "파도튜브", "수입뿌드", "토마토", "햇살", "소주양", "주하랑", "치리", "임조이", "먼진", "진땅콩"]'::jsonb, 'https://youtu.be/qZoD_Fp2D88?si=fkmQYGMVNUDScdtW', null, 1, false),
('h-mu9ihl5y', 'manual', '2026-03-26', 'broadcast', '츠캄 VS JSA 풋살', '', '["김윤환", "박준오", "사테", "지동원", "배성흠", "파도튜브", "지두두", "찌킹", "먼진", "정영재", "김성대", "시조새"]'::jsonb, 'https://youtu.be/02Hk3X6p23g?si=6xch0tyeGM32nPXB', null, null, false),
('h-mu9inpdm', 'manual', '2026-04-04', 'broadcast', '츠캄 VS JSA 스보라', '', '["김윤환", "토마토", "찌킹", "주하랑", "소주양", "먼진", "아리송이", "박수범", "지동원", "배성흠", "시조새"]'::jsonb, 'https://youtu.be/EonP6znz-x8?si=DSqx2pXyIHJ5kbOk', null, null, false),
('h-mu9ipode', 'manual', '2026-04-17', 'event', '수장CK', '', '["김윤환", "이경민", "철구", "김봉준", "시조새", "기뉴다", "흑운장", "전태규"]'::jsonb, 'https://youtu.be/-o4QGWh178g?si=dD6GehkDgf0w3nIC', null, null, false),
('h-mu9irslm', 'manual', '2026-04-25', 'event', '츠캄 VS 뉴캣슬 대학대전', '빌드실명제 도입 후 첫 재판', '["먼진", "박준오", "임조이", "김윤환", "아리송이", "이경민", "찌킹", "배성흠", "소주양", "사테", "진땅콩", "파도튜브"]'::jsonb, 'https://youtu.be/xmZxsrwz8cY?si=ap1JIBpDJUZzu7eQ', null, null, false),
('h-mu9ityp6', 'manual', '2026-04-29', 'broadcast', '츠캄 시즌4 MT', '2026-04-29 ~ 2026-04-30', '["김윤환", "이경민", "토마토", "지두두", "햇살", "찌킹", "치리", "주하랑", "소주양", "임조이", "비타밍", "아리송이", "먼진", "진땅콩", "낭니", "박준오", "사테", "박수범", "지동원", "배성흠", "파도튜브"]'::jsonb, 'https://youtu.be/pKWjscMNR5I?si=dbUJWDBXYCERHb1o', null, null, false),
('h-mu9j1izt', 'manual', '2026-05-07', 'founding', '대학명 ''캄몬스타즈''로 변경', '', '[]'::jsonb, 'https://youtu.be/MriCJCTlD3U?si=wZme0j45D6ipyr2R', null, null, false),
('h-mu9j38op', 'manual', '2026-05-09', 'broadcast', '24시간 벌칙 방송', '', '["김윤환", "지두두", "찌킹", "소주양", "비타밍", "아리송이", "사테", "지동원", "배성흠", "파도튜브"]'::jsonb, 'https://youtu.be/k64EXRqIgTU?si=IYC9YvCUd2lF0huK', null, null, false),
('h-mu9j5r41', 'manual', '2026-05-13', 'event', '스승의 날 CK', '276만', '["김윤환", "지동원", "파도튜브", "박준오", "박수범", "사테", "배성흠"]'::jsonb, 'https://youtu.be/4EMk8X6ZZAE?si=efFeO8BO9TNfIOVP', null, null, false),
('h-mu9j73j6', 'manual', '2026-05-14', 'broadcast', '스승의 날 합방', '', '["김윤환", "토마토", "지두두", "찌킹", "치리", "주하랑", "소주양", "임조이", "비타밍", "먼진", "아리송이", "진땅콩", "낭니", "박준오", "박수범", "지동원", "배성흠", "파도튜브"]'::jsonb, 'https://youtu.be/FepZ8svCDq0?si=DtU8aED0twN49t_8', null, null, false),
('h-mu9jb2mz', 'manual', '2026-05-20', 'broadcast', '흉가 벌칙', '캄몬 VS 엠비대 대학대전', '["김윤환", "치리", "주하랑", "소주양", "지동원", "파도튜브"]'::jsonb, 'https://youtu.be/FJbb5-cX3Rs?si=MAoaV7_kuvx3PxpZ', null, null, false),
('h-mu9jdg60', 'manual', '2026-06-01', 'match', '스타워즈 4강', '', '["김윤환", "박준오", "사테", "박수범", "지동원", "배성흠", "파도튜브", "토마토", "지두두", "햇살", "찌킹", "치리", "주하랑", "소주양", "임조이", "비타밍", "아리송이", "먼진", "진땅콩", "낭니"]'::jsonb, 'https://youtu.be/NeqyY8yGTp4?si=jgbNoN6yHrVt_m1W', null, null, false),
('h-mu9jepkk', 'manual', '2026-06-02', 'event', '캄몬 VS 씨나인 스타워즈 나락전', '갯벌스타', '["김윤환", "지두두", "토마토", "비타밍", "소주양", "임조이", "치리", "찌킹", "먼진", "아리송이", "진땅콩", "사테", "박준오", "박수범", "지동원", "배성흠", "파도튜"]'::jsonb, 'https://youtu.be/ycD_eTwxDN4?si=XrIByji41EyPhntm', null, null, false),
('h-mu9jh0en', 'manual', '2026-06-03', 'broadcast', '캄몬합숙소', '2026-06-03 ~2026-06-07', '["김윤환", "지두두", "찌킹", "임조이", "진땅콩", "치리", "먼진", "소주양", "비타밍", "토마토", "아리송이", "박준오", "사테", "박수범", "파도튜브", "배성흠", "지동원"]'::jsonb, 'https://youtu.be/Cem7EYHDWOo?si=yh2vR4K0muN_iifa', null, null, false),
('h-mu9jib1s', 'manual', '2026-06-13', 'event', '김윤환 생일 대학대전', '', '["진땅콩", "비타밍", "먼진", "아리송이", "토마토", "찌킹", "임조이"]'::jsonb, 'https://youtu.be/XJR01anzzI0?si=_cvhBev1SsLfqRTh', null, null, false),
('h-mu9jjrw7', 'manual', '2026-06-18', 'event', '촌캉스', '스승의 날 CK 공약', '["지두두", "김윤환", "소주양", "지동원"]'::jsonb, 'https://youtu.be/ybyzIJgwn8E?si=451K37WwlQoxGBRn', null, null, false),
('h-mu9jlo59', 'manual', '2026-06-27', 'broadcast', '놀이공원', '스승의 날 CK 공약', '["비타밍", "김윤환", "토마토", "지동원"]'::jsonb, 'https://youtu.be/lY599_tJkrw?si=-F0J4piqgsp-dpdw', null, null, false),
('h-mu9jo7j8', 'manual', '2026-07-04', 'match', '뉴캄옥션 족암새퉤퉤퉤 준우승', '2026-06-23 ~ 2026-07-04', '["김윤환", "철구", "시조새", "최세상", "비타밍", "갱이다"]'::jsonb, 'https://youtu.be/5DvgTwZHEuY?si=iuHZj7feh2crqpeM', null, null, false),
('h-mu9jpx62', 'manual', '2026-07-09', 'broadcast', '낭니 오프교육', '스승의 날 CK 공약', '["낭니", "김윤환"]'::jsonb, 'https://youtu.be/Ock1jKfcRao?si=ZXbgmTuvujgRGo2u', null, null, false),
('h-mu9jrrwk', 'manual', '2026-07-11', 'broadcast', '현실종겜', '스승의 날 CK 공약', '["주하랑", "김윤환", "먼진", "김민철"]'::jsonb, 'https://youtu.be/PduVMpDwUrc?si=rbtqhCit57DanC1G', null, null, false),
('h-mu9jth29', 'manual', '2026-07-13', 'broadcast', '테란반 글램핑', '스승의 날 CK 공약', '["지두두", "햇살", "소주양", "비타밍", "사테", "지동원"]'::jsonb, '', 'data/history/h-mu9jth29-mu9rd9bk.jpg', null, false),
('h-mu9jus0b', 'manual', '2026-07-14', 'event', '시빌워', '', '["김윤환", "주하랑", "치리", "아리송이", "먼진", "소주양", "남덕선", "지동원", "비타밍", "임조이", "햇살", "찌킹", "박수범", "배성흠", "사테", "박준오", "지두두", "토마토", "변현제", "김민철", "낭니", "클템"]'::jsonb, 'https://youtu.be/orATQAOCpw4?si=nhJPf3BUu-yXMUOv', null, null, false),
('h-mu9jw6h6', 'manual', '2026-07-24', 'broadcast', '힐링캠프', '스승의 날 CK 공약', '["토마토", "김윤환", "박준오", "임조이", "치리"]'::jsonb, 'https://youtu.be/5q7lh3qpRbk?si=C2JDCekFZnbpFDU0', null, null, false),
('h-mu9jyba3', 'manual', '2026-07-30', 'broadcast', '캄몬합숙소', '2026-07-30 ~ 2026-8-01', '["김윤환", "남덕선", "햇살", "주하랑", "소주양", "사테", "박수범", "배성흠", "지동원"]'::jsonb, 'https://youtu.be/OP30_xl0d9o?si=vxZLPbTqOaL5uwAK', null, null, false),
('h-mu9k2fbq', 'manual', '2026-08-04', 'broadcast', '캄몬합숙소', '2026-08-04 ~ 2026-08-05', '["김윤환", "남덕선", "주하랑", "임조이", "비타밍", "김민철", "왜냐맨", "지동원", "박수범"]'::jsonb, 'https://youtu.be/6j-dyjeCt8Q?si=KbUkO5tXv6Ef3v9o', null, null, false),
('h-mu9k532w', 'manual', '2026-08-24', 'broadcast', '족구 스트리머 팀대전', '', '["김윤환", "박준오", "배성흠", "왜냐맨", "지두두", "주하랑", "먼진", "낭니"]'::jsonb, 'https://youtu.be/q-b2uOhwZD8?si=ULWsWsygz_iiOkiH', null, null, false),
('h-mu9k7eql', 'manual', '2026-09-04', 'match', 'K-중만컵 8강', '2026-08-02 ~ 2026-09-19', '["김윤환", "김민철", "변현제", "박준오", "사테", "박수범", "지동원", "배성흠", "왜냐맨", "남덕선", "토마토", "지두두", "햇살", "찌킹", "치리", "주하랑", "소주양", "임조이", "비타밍", "아리송이", "먼진", "낭니"]'::jsonb, 'https://youtu.be/7xSMbE_Uix8?si=u27nOn5kmY9JGDPS', null, 1, false),
('h-mu9k8vio', 'manual', '2026-09-05', 'broadcast', '을왕리 야방', '', '["김윤환", "김민철", "박준오", "배성흠"]'::jsonb, 'https://youtu.be/61m0pUKxtXo?si=U6FwCc18lsbHVe2P', null, null, false),
('h-mu9ka45l', 'manual', '2026-09-07', 'broadcast', '할없사 낚시', '', '["김윤환", "토마토", "먼진", "김민철", "주하랑"]'::jsonb, 'https://youtu.be/kHzcykL7FIo?si=tOuz1Urz4vD9vKnD', null, null, false),
('h-mu9qpqz8', 'manual', '2026-09-20', 'broadcast', '24시간 방송', '스승의 날 CK 공약
2026-09-20 ~ 2026-09-21', '["토마토", "남덕선", "지두두", "햇살", "주하랑", "소주양", "임조이", "비타밍", "아리송이", "먼진", "낭니"]'::jsonb, 'https://youtu.be/6qVPXb_8dXw?si=bdIy6FnmELzx4OJs', null, null, false),
('auto-join-2024-07-08', 'override', null, null, null, null, '[]'::jsonb, null, null, 0, true),
('auto-join-2024-07-09', 'override', null, null, '디임, 졈니 입단', '', '["디임(선수)", "졈니(선수)"]'::jsonb, 'https://youtu.be/nAMxXANHrjs?si=O787Qr8QklH0kUML', null, null, false),
('auto-join-2024-07-12', 'override', null, null, '', '', '["앵지(선수)"]'::jsonb, 'https://youtu.be/XP1lPYf3jOk?si=_hGKxpheNekRV2dC', null, null, false),
('auto-join-2024-07-17', 'override', null, null, '토마토, 임조이 입단', '', '["토마토(선수)", "임조이(유스)"]'::jsonb, 'https://youtu.be/8-LAzyp5JOM?si=Fce3Auv_uiULABPh', null, null, false),
('auto-leave-2024-07-20', 'override', null, null, '', '', '["킹지(유스)"]'::jsonb, '', null, 0, false),
('auto-join-2024-07-20', 'override', null, null, '', '', '["킹지(유스)"]'::jsonb, 'https://youtu.be/Nac05jgNv1M?si=QvVK-eaD6AdwSwNn', null, 1, false),
('auto-join-2024-08-07', 'override', null, null, '효짱, 한쪼니 입단', '', '["효짱(유스)", "한쪼니(유스)"]'::jsonb, 'https://youtu.be/PMIdwfge8j8?si=WDDKK5pzfLlK2nRk', null, null, false),
('auto-join-2024-08-17', 'override', null, null, '몽군, 모리 입단', '', '["몽군(코치)", "모리(선수)"]'::jsonb, 'https://youtu.be/rPbrRLr25a8?si=WKGzSoBfKWMOx78a', null, null, false),
('auto-join-2024-08-19', 'override', null, null, '', '', '["치리(선수)"]'::jsonb, 'https://youtu.be/1tT5UDqj_Cg?si=WIxY6_KaYp8VgEz_', null, null, false),
('auto-join-2024-09-01', 'override', null, null, '', '', '["강덕구(선수)"]'::jsonb, '', null, 1, false),
('auto-leave-2024-09-25', 'override', null, null, '', '', '["강덕구(선수)"]'::jsonb, '', null, null, false),
('auto-join-2024-09-30', 'override', null, null, '', '', '["수입뿌드(코치)"]'::jsonb, 'https://youtu.be/53BKLNYmSNs?si=IbyaIMM_DsY8FgzJ', null, null, false),
('auto-join-2024-10-18', 'override', null, null, '', '', '["박준오(코치)"]'::jsonb, 'https://youtu.be/84yuQx7bSDA?si=SAhFIyz4dbDmQIW-', null, null, false),
('auto-join-2024-10-31', 'override', null, null, '', '', '["정윤종(전력분석관)"]'::jsonb, 'https://youtu.be/EnbnUabTY-M?si=9HUZInK6DuXQhaNB', null, null, false),
('auto-join-2024-11-02', 'override', null, null, '', '', '["세나(선수)"]'::jsonb, 'https://youtu.be/TIuSsn_Ip5g?si=pq3z3tIdFO829KQT', null, null, false),
('auto-leave-2025-01-08', 'override', null, null, '', '', '["디임(선수)"]'::jsonb, '', null, null, false),
('auto-join-2025-02-21', 'override', null, null, '진땅콩, 송혜림 입단', '', '["진땅콩 T(인턴)", "송혜림(인턴)"]'::jsonb, 'https://youtu.be/_E9hH_ZPXAw?si=QXTjtN16YjxKHZF0', null, null, false),
('auto-join-2025-02-28', 'override', null, null, '', '', '["다예(선수)"]'::jsonb, 'https://youtu.be/XsD-pqt3Nho?si=RWABoa2YSlyoiWFI', null, null, false),
('auto-join-2025-03-06', 'override', null, null, '', '', '["막내현진(유스)"]'::jsonb, 'https://youtu.be/t95Kc97OrqQ?si=oyyGaezIfPDvjAbs', null, null, false),
('auto-leave-2025-03-07', 'override', null, null, '진땅콩 퇴단', '', '["진땅콩 T(인턴)"]'::jsonb, '', null, null, false),
('auto-leave-2025-06-12', 'override', null, null, '', '', '["송혜림(유스)"]'::jsonb, '', null, null, false),
('auto-leave-2025-07-14', 'override', null, null, '', '', '["몽군(코치)", "세나(선수)", "졈니(선수)", "앵지(선수)", "효짱(선수)", "한쪼니(선수)"]'::jsonb, 'https://youtu.be/oP1yt9WV6tc?si=9apXLfTXTupZSsAc', null, null, false),
('auto-join-2025-07-26', 'override', null, null, '황병영, 지동원 입단', '', '["황병영(코치)", "지동원(코치)"]'::jsonb, 'https://youtu.be/X2v4tFliNLQ?si=FMCi4y-_5oJLaLnI', null, null, false),
('auto-join-2025-07-27', 'override', null, null, '진땅콩 재입단', '', '["진땅콩(유스)"]'::jsonb, '', null, null, false),
('auto-join-2025-08-04', 'override', null, null, '조일장, 두디 입단', '', '["조일장(코치)", "두디(선수)"]'::jsonb, 'https://youtu.be/KtZ4re55JpI?si=w9U9Fbr0Ommn_DHK', null, null, false),
('auto-join-2025-08-05', 'override', null, null, '', '', '["주하랑(선수)"]'::jsonb, 'https://youtu.be/SoaXJEvurPQ?si=Scu69Z5AFBn47It6', null, null, false),
('auto-join-2025-08-07', 'override', null, null, '', '', '["햇살(선수)"]'::jsonb, 'https://youtu.be/wJUy2V_phes?si=nqboL3KL4wMiiBK-', null, null, false),
('auto-join-2025-09-24', 'override', null, null, '', '', '["소주양(선수)"]'::jsonb, 'https://youtu.be/BROa1Ow9K68?si=CuaP_VpeG-aGwtOr', null, null, false),
('auto-leave-2025-10-29', 'override', null, null, '', '', '["두디(선수)", "모리(선수)", "막내현진(선수)"]'::jsonb, 'https://youtu.be/u8akmF-WyJ0?si=xfij8_i9ihplSoB9', null, 0, false),
('auto-join-2025-11-03', 'override', null, null, '', '', '["파도튜브(코치)"]'::jsonb, '', null, null, false),
('auto-join-2025-11-15', 'override', null, null, '연또, 박쭈이, 정유랭 입단', '', '["연또(인턴)", "박쭈이(인턴)", "정유랭(인턴)"]'::jsonb, 'https://youtu.be/3nt_3kiQM30?si=Zf00wVSrr7u-nuAc', null, null, false),
('auto-leave-2025-11-29', 'override', null, null, '', '', '["정유랭(인턴)"]'::jsonb, '', null, null, false),
('auto-leave-2025-12-06', 'override', null, null, '', '', '["연또(인턴)"]'::jsonb, '', null, null, false),
('auto-leave-2026-01-14', 'override', null, null, '', '', '["정윤종(전력분석관)"]'::jsonb, 'https://youtu.be/ThscazOdcqY?si=-CPOe5vVTWfst7Ll', null, null, false),
('auto-leave-2026-01-17', 'override', null, null, '', '', '["다예(선수)"]'::jsonb, '', null, null, false),
('auto-join-2026-01-17', 'override', null, null, '배성흠, 박수범, 먼진 입단', '', '["배성흠(코치)", "박수범(코치)", "먼진(선수)"]'::jsonb, 'https://youtu.be/c7MKzCW4TVw?si=NmNNGmEwGk6Yc_nB', null, null, false),
('auto-leave-2026-03-14', 'override', null, null, '', '', '["조일장(코치)", "황병영(코치)", "수입뿌드(코치)"]'::jsonb, '', null, 0, false),
('auto-join-2026-03-16', 'override', null, null, '', '', '["비타밍(선수)"]'::jsonb, 'https://youtu.be/ts2d7YEBykQ?si=Is1TJ_E8rPGsHIYd', null, null, false),
('auto-join-2026-03-19', 'override', null, null, '지두두, 아리송이 입단', '', '["지두두(선수)", "아리송이(선수)"]'::jsonb, 'https://youtu.be/vN-MN3XFGk8?si=_DED5oARG5E9AMYD', null, null, false),
('auto-leave-2026-03-21', 'override', null, null, '', '', '["박쭈이(유스)"]'::jsonb, '', null, null, false),
('auto-join-2026-03-26', 'override', null, null, '사테, 찌킹 입단', '', '["사테(코치)", "찌킹(선수)"]'::jsonb, 'https://youtu.be/jA7znOqF12E?si=yKsnBnZvPXDndwCK', null, null, false),
('auto-join-2026-04-28', 'override', null, null, '', '', '["낭니(유스)"]'::jsonb, 'https://youtu.be/s49-qGImYzg?si=uxE-6EwaOnpFPmS5', null, null, false),
('auto-leave-2026-05-04', 'override', null, null, '', '', '["이경민(감독)"]'::jsonb, 'https://youtu.be/zZt3lmoEiSQ?si=ByFNYMfAeAQDDjzH', null, null, false),
('auto-join-2026-06-13', 'override', null, null, '', '', '["변현제(코치)"]'::jsonb, '', null, null, false),
('auto-join-2026-06-16', 'override', null, null, '', '', '["김민철(코치)"]'::jsonb, 'https://youtu.be/I-q__BWF21E?si=epGW4yXLQ2uwZUCE', null, null, false),
('auto-leave-2026-06-28', 'override', null, null, '', '', '["파도튜브(코치)", "진땅콩(선수)"]'::jsonb, 'https://youtu.be/KE_vKv-5w0s?si=MQ8roCCyAjOYnq81', null, null, false),
('auto-join-2026-07-08', 'override', null, null, '', '', '["남덕선(선수)"]'::jsonb, '', 'data/history/auto-join-2026-07-08-mu9rsqn7.jpg', null, false),
('auto-join-2026-07-31', 'override', null, null, '', '', '["왜냐맨(코치)"]'::jsonb, 'https://youtu.be/uigMcUS3O80?si=YoL6SPy0Zey4w0Gj', null, null, false),
('auto-leave-2026-09-04', 'override', null, null, '', '', '["변현제(코치)", "지동원(코치)", "박수범(코치)", "찌킹(선수)", "치리(선수)"]'::jsonb, 'https://youtu.be/RGP4taQNL8g?si=Oj0_TOVB66dRR6uP', null, 0, false),
('auto-join-2024-10-30', 'override', null, null, '', '', '["정윤종(전력분석관)"]'::jsonb, 'https://youtu.be/EnbnUabTY-M?si=iGlrZhLoN_jL_axB', null, null, false)
on conflict (id) do nothing;

-- ============================================================================
-- 공개 사이트 읽기 권한
-- ============================================================================

-- 공개 사이트가 Supabase를 직접 읽기 위한 최소 권한 설정.
-- Supabase SQL Editor에서 한 번 실행하세요.
-- 관리자(authenticated)의 기존 CRUD 정책은 supabase/admin.sql 그대로 유지합니다.

-- 공개 방문자는 사이트 화면에 실제로 쓰는 컬럼만 SELECT할 수 있습니다.
revoke all on public.members from anon;
revoke all on public.matches from anon;
revoke all on public.rounds from anon;
revoke all on public.tier_members from anon;

grant select (source_order, nickname, soop_id, birth_date, gender, race, tier, role, joined_date, left_date, mbti, avatar_path)
  on public.members to anon;
grant select (team_name, logo_path) on public.teams to anon;
grant select (source_order, match_no, match_date, opponent_team, match_format, method, final_result, set_result)
  on public.matches to anon;
grant select (source_order, match_no, match_date, opponent_team, match_format, set_name, round_name, our_player, our_race, result, opponent_player, opponent_race, map_name)
  on public.rounds to anon;
grant select (source_order, nickname, soop_id, race, tier, affiliation, modified_at)
  on public.tier_members to anon;

drop policy if exists "public_read_teams" on public.teams;
create policy "public_read_teams" on public.teams for select to anon using (true);
drop policy if exists "public_read_members" on public.members;
create policy "public_read_members" on public.members for select to anon using (true);
drop policy if exists "public_read_matches" on public.matches;
create policy "public_read_matches" on public.matches for select to anon using (true);
drop policy if exists "public_read_rounds" on public.rounds;
create policy "public_read_rounds" on public.rounds for select to anon using (true);
drop policy if exists "public_read_tier_members" on public.tier_members;
create policy "public_read_tier_members" on public.tier_members for select to anon using (true);


-- 일정/휴방/메뉴 설정도 공개 사이트가 직접 읽는다.
revoke all on public.calendar_events from anon;
revoke all on public.calendar_off_air from anon;
revoke all on public.site_config from anon;

grant select (id, source_order, start_date, end_date, event_time, person, description, detail, color)
  on public.calendar_events to anon;
grant select (off_date, soop_id, source_order) on public.calendar_off_air to anon;
grant select (config_key, config_value) on public.site_config to anon;

drop policy if exists "public_read_calendar_events" on public.calendar_events;
create policy "public_read_calendar_events" on public.calendar_events for select to anon using (true);
drop policy if exists "public_read_calendar_off_air" on public.calendar_off_air;
create policy "public_read_calendar_off_air" on public.calendar_off_air for select to anon using (true);
drop policy if exists "public_read_site_config" on public.site_config;
create policy "public_read_site_config" on public.site_config for select to anon using (config_key = 'nav');


-- 연혁은 공개 사이트에서 바로 읽는다.
revoke all on public.history_entries from anon;
grant select (id, entry_kind, event_date, event_type, title, description, members, youtube_url, image_path, sort_order, hidden) on public.history_entries to anon;
drop policy if exists "public_read_history_entries" on public.history_entries;
create policy "public_read_history_entries" on public.history_entries for select to anon using (true);
