-- StarUniv Supabase 전체 설정(한 파일)
--
-- Supabase SQL 편집기에 이 파일 전체를 붙여 넣고 실행한다. 여러 번 실행해도 된다:
--   표·열은 없을 때만 만들고, 함수·정책·권한은 최신으로 다시 쓴다. 운영 데이터(일정·휴방·연혁·
--   메뉴 설정·영상·외부 도구·선수)는 읽지도 바꾸지도 않는다(처음 옮길 때 넣던 시드 데이터는 뺐다).
-- 공유 DB의 파이프라인(ELO·영상·방송 통계) 스키마는 ststat 저장소 supabase/ststat.sql이 따로 맡는다(이 파일을 먼저 실행한 뒤 그 파일을 실행).
--
-- 처음 한 번만 필요한 준비(이미 했으면 건너뜀):
--   1) Authentication > Users에서 관리자 계정을 만든 뒤 등록:
--        insert into public.admin_users (user_id, role)
--        select id, 'owner' from auth.users where email = '관리자 이메일'
--        on conflict (user_id) do update set role = excluded.role, is_active = true;
--   2) GitHub 토큰(저장소 ststats/staruniv만, 권한 Actions = Read and write)을 Vault에 넣기
--      ('달력 사진 갱신' 버튼과 '티어표 갱신'이 쓴다. 토큰 값은 이 파일에 적지 말 것):
--        select vault.create_secret('<토큰>', 'github_actions_token');
--      바꿀 때: select vault.update_secret((select id from vault.secrets where name = 'github_actions_token'), '<새 토큰>');
--
-- 구성(순서대로): 1 기본 스키마·관리자 권한·영상·도구 → 2 공개 읽기 권한 → 3 어드민 편집 보조
--                 → 4 어드민 ELO 통계 → 5 달력 사진 갱신 → 6 티어표 갱신 → 7 대학 로고


-- ############################################################################
-- 1. 기본 스키마 · 관리자 권한 · 영상 · 도구
-- ############################################################################

-- ============================================================================
-- 기본 스키마
-- ============================================================================

-- 공개 페이지는 publishable key로 운영 데이터를 직접 읽고, Actions는 장애 대비 JSON을 내보냅니다.
--    공개 SELECT와 관리자 쓰기 범위는 아래 RLS/권한 정책으로 제한합니다.

create table if not exists public.settings (
  source_order integer primary key,
  season text not null,
  start_date date
);

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  source_order integer not null unique,
  team_name text not null,
  founders text,
  founded_date date,
  disbanded_date date,
  note text,
  championship text,
  logo_path text
);
create index if not exists teams_team_name_idx on public.teams (team_name);

create table if not exists public.members (
  -- StarUniv 내부 행 식별자. 외부 서비스 ID와 절대 혼용하지 않는다.
  id bigint generated by default as identity primary key,
  source_order integer not null unique,
  -- 같은 사람의 기준 이름. 예: 진땅콩
  name text not null,
  -- 해당 멤버 행에서 실제 사용한 표시/방송 닉네임. 예: 진땅콩 T
  nickname text not null,
  -- SOOP 계정 ID
  soop_id text,
  -- ELO보드 선수 ID. ELO 원본 players 객체의 key(id)를 여기에는 elo_id로 저장한다.
  elo_id integer,
  birth_date date,
  gender text,
  race text,
  join_tier text,
  tier text,
  role text,
  joined_date date,
  left_date date,
  mbti text,
  avatar_path text,
  -- 유튜브 채널 주소(있는 사람만). 프로필의 YouTube 버튼에 쓴다.
  youtube_url text
);
alter table public.members add column if not exists youtube_url text;
create index if not exists members_name_idx on public.members (name);
create index if not exists members_nickname_idx on public.members (nickname);
create index if not exists members_soop_id_idx on public.members (soop_id);
create index if not exists members_elo_id_idx on public.members (elo_id);

create table if not exists public.matches (
  match_no integer primary key,
  source_order integer not null unique,
  match_date date not null,
  opponent_team text not null,
  match_format text,
  method text,
  final_result text,
  set_result text,
  score_diff text,
  funding text,
  support_amount text,
  personal_amount text,
  challenge_mission text
);
create index if not exists matches_date_idx on public.matches (match_date desc);
create index if not exists matches_opponent_idx on public.matches (opponent_team);

create table if not exists public.rounds (
  id bigint generated by default as identity primary key,
  source_order integer not null unique,
  match_no integer not null references public.matches(match_no) on update cascade on delete cascade,
  match_date date not null,
  opponent_team text,
  match_format text,
  set_name text,
  round_name text,
  our_player text,
  our_race text,
  our_tier text,
  result text,
  opponent_player text,
  opponent_race text,
  opponent_tier text,
  map_name text
);
create index if not exists rounds_match_no_idx on public.rounds (match_no);
create index if not exists rounds_date_idx on public.rounds (match_date desc);
create index if not exists rounds_our_player_idx on public.rounds (our_player);
create index if not exists rounds_opponent_player_idx on public.rounds (opponent_player);

create table if not exists public.tier_members (
  id bigint generated by default as identity primary key,
  source_order integer not null unique,
  name text,
  nickname text not null,
  soop_id text,
  elo_id integer,
  birth_date date,
  gender text,
  race text,
  tier text,
  affiliation text,
  role text,
  modified_at text,
  history text,
  started_on text,
  elo_registered text,
  tier_table_registered text,
  promoted_tier_8 text,
  promoted_tier_7 text,
  promoted_tier_6 text,
  promoted_tier_5 text,
  promoted_tier_4 text,
  promoted_tier_3 text,
  promoted_tier_2 text,
  promoted_tier_1 text,
  promoted_tier_0 text
);
create unique index if not exists tier_members_elo_id_uq
  on public.tier_members (elo_id) where elo_id is not null;
create index if not exists tier_members_nickname_idx on public.tier_members (nickname);
create index if not exists tier_members_soop_id_idx on public.tier_members (soop_id);
create index if not exists tier_members_affiliation_idx on public.tier_members (affiliation);

-- ELO 원본 테이블. Actions가 외부 최신분을 증분 저장하고 빌드용 캐시를 다시 내보냅니다.
create table if not exists public.elo_categories (
  category_id smallint primary key,
  name text not null
);

create table if not exists public.elo_maps (
  map_id integer primary key,
  name text not null
);

create table if not exists public.elo_players (
  -- eloboard.json players의 key. 원본에서는 그냥 id처럼 보이지만 DB에서는 elo_id로 명확히 구분한다.
  elo_id integer primary key,
  name text not null,
  race text
);
create index if not exists elo_players_name_idx on public.elo_players (name);

create table if not exists public.elo_matches (
  elo_match_id bigint primary key,
  match_date date not null,
  winner_elo_id integer references public.elo_players(elo_id),
  loser_elo_id integer references public.elo_players(elo_id),
  map_id integer references public.elo_maps(map_id),
  category_id smallint not null references public.elo_categories(category_id)
);
create index if not exists elo_matches_date_idx on public.elo_matches (match_date desc);
create index if not exists elo_matches_winner_idx on public.elo_matches (winner_elo_id);
create index if not exists elo_matches_loser_idx on public.elo_matches (loser_elo_id);
create index if not exists elo_matches_map_idx on public.elo_matches (map_id);
create index if not exists elo_matches_category_idx on public.elo_matches (category_id);

-- 브라우저의 anon/authenticated 사용자가 정책 없이 직접 읽거나 쓰지 못하게 막습니다.
alter table public.settings enable row level security;
alter table public.teams enable row level security;
alter table public.members enable row level security;
alter table public.matches enable row level security;
alter table public.rounds enable row level security;
alter table public.tier_members enable row level security;
alter table public.elo_categories enable row level security;
alter table public.elo_maps enable row level security;
alter table public.elo_players enable row level security;
alter table public.elo_matches enable row level security;

-- 실시간 일정/휴방/사이트 표시 설정. 기존 calendar.json/nav.json의 운영 데이터를 Supabase로 이동한다.
create table if not exists public.calendar_events (
  id bigint primary key,
  source_order integer not null unique,
  start_date date not null,
  end_date date not null,
  event_time text,
  person text not null default '',
  description text,
  detail text,
  color text
);
create index if not exists calendar_events_date_idx on public.calendar_events (start_date, end_date);

create table if not exists public.calendar_off_air (
  off_date date not null,
  soop_id text not null,
  source_order integer not null default 0,
  primary key (off_date, soop_id)
);
create index if not exists calendar_off_air_date_idx on public.calendar_off_air (off_date, source_order);

create table if not exists public.site_config (
  config_key text primary key,
  config_value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.calendar_events enable row level security;
alter table public.calendar_off_air enable row level security;
alter table public.site_config enable row level security;
-- 운영자가 수정하는 연혁 메타데이터. 사진 파일은 Storage(staruniv-media)에 두고 image_path만 저장한다.
create table if not exists public.history_entries (
  id text primary key,
  entry_kind text not null default 'manual' check (entry_kind in ('manual','override')),
  event_date date,
  event_type text,
  title text,
  description text,
  members jsonb not null default '[]'::jsonb,
  youtube_url text,
  image_path text,
  sort_order integer,
  hidden boolean not null default false,
  updated_at timestamptz not null default now()
);
create index if not exists history_entries_date_idx on public.history_entries (event_date desc);

alter table public.history_entries enable row level security;

-- ============================================================================
-- 관리자 인증/RLS
-- ============================================================================

-- 관리자 계정 등록은 이 파일 맨 위 '처음 한 번만 필요한 준비' 참고

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'admin' check (role in ('owner', 'admin')),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

-- RLS 정책 안에서 재사용하는 관리자 판별 함수.
-- SECURITY DEFINER로 admin_users 자체의 RLS 순환을 피한다.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users a
    where a.user_id = auth.uid()
      and a.is_active = true
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

-- 로그인한 사용자는 자기 관리자 등록 상태만 읽을 수 있다.
drop policy if exists "admin_users_read_self" on public.admin_users;
create policy "admin_users_read_self"
on public.admin_users
for select
to authenticated
using (user_id = (select auth.uid()));

grant select on public.admin_users to authenticated;

-- 운영 데이터: 관리자만 브라우저에서 CRUD 가능.
do $$
declare
  t text;
begin
  foreach t in array array['settings','teams','members','matches','rounds','tier_members','calendar_events','calendar_off_air','site_config','history_entries']
  loop
    execute format('drop policy if exists %I on public.%I', 'admins_all_' || t, t);
    execute format(
      'create policy %I on public.%I for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()))',
      'admins_all_' || t,
      t
    );
  end loop;
end $$;

grant select, insert, update, delete on public.settings, public.teams, public.members,
  public.matches, public.rounds, public.tier_members, public.calendar_events, public.calendar_off_air, public.site_config, public.history_entries to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- ELO 원본은 관리자 화면에서는 조회만 허용한다.
do $$
declare
  t text;
begin
  foreach t in array array['elo_categories','elo_maps','elo_players','elo_matches']
  loop
    execute format('drop policy if exists %I on public.%I', 'admins_read_' || t, t);
    execute format(
      'create policy %I on public.%I for select to authenticated using ((select public.is_admin()))',
      'admins_read_' || t,
      t
    );
  end loop;
end $$;

grant select on public.elo_categories, public.elo_maps, public.elo_players, public.elo_matches to authenticated;

-- 경기 + 세트를 한 트랜잭션으로 저장한다.
-- 기존 경기를 수정할 때는 source_order를 유지하고, 세트 목록은 전달된 내용으로 교체한다.
create or replace function public.admin_save_match(p_match jsonb, p_rounds jsonb default '[]'::jsonb)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_match_no integer;
  v_source_order integer;
  v_round_source integer;
  r jsonb;
begin
  if not public.is_admin() then
    raise exception 'admin only';
  end if;

  v_match_no := nullif(p_match->>'match_no', '')::integer;
  if v_match_no is null then
    select coalesce(max(match_no), 0) + 1 into v_match_no from public.matches;
  end if;

  v_source_order := nullif(p_match->>'source_order', '')::integer;
  if v_source_order is null then
    select coalesce(max(source_order), 0) + 1 into v_source_order from public.matches;
  end if;

  insert into public.matches (
    match_no, source_order, match_date, opponent_team, match_format, method,
    final_result, set_result, score_diff, funding, support_amount, personal_amount, challenge_mission
  ) values (
    v_match_no,
    v_source_order,
    nullif(p_match->>'match_date','')::date,
    nullif(p_match->>'opponent_team',''),
    nullif(p_match->>'match_format',''),
    nullif(p_match->>'method',''),
    nullif(p_match->>'final_result',''),
    nullif(p_match->>'set_result',''),
    nullif(p_match->>'score_diff',''),
    nullif(p_match->>'funding',''),
    nullif(p_match->>'support_amount',''),
    nullif(p_match->>'personal_amount',''),
    nullif(p_match->>'challenge_mission','')
  )
  on conflict (match_no) do update set
    source_order = excluded.source_order,
    match_date = excluded.match_date,
    opponent_team = excluded.opponent_team,
    match_format = excluded.match_format,
    method = excluded.method,
    final_result = excluded.final_result,
    set_result = excluded.set_result,
    score_diff = excluded.score_diff,
    funding = excluded.funding,
    support_amount = excluded.support_amount,
    personal_amount = excluded.personal_amount,
    challenge_mission = excluded.challenge_mission;

  delete from public.rounds where match_no = v_match_no;
  select coalesce(max(source_order), 0) into v_round_source from public.rounds;

  for r in select value from jsonb_array_elements(coalesce(p_rounds, '[]'::jsonb))
  loop
    v_round_source := v_round_source + 1;
    insert into public.rounds (
      source_order, match_no, match_date, opponent_team, match_format,
      set_name, round_name, our_player, our_race, our_tier, result,
      opponent_player, opponent_race, opponent_tier, map_name
    ) values (
      v_round_source,
      v_match_no,
      nullif(coalesce(r->>'match_date', p_match->>'match_date'),'')::date,
      nullif(coalesce(r->>'opponent_team', p_match->>'opponent_team'),''),
      nullif(coalesce(r->>'match_format', p_match->>'match_format'),''),
      nullif(r->>'set_name',''),
      nullif(r->>'round_name',''),
      nullif(r->>'our_player',''),
      nullif(r->>'our_race',''),
      nullif(r->>'our_tier',''),
      nullif(r->>'result',''),
      nullif(r->>'opponent_player',''),
      nullif(r->>'opponent_race',''),
      nullif(r->>'opponent_tier',''),
      nullif(r->>'map_name','')
    );
  end loop;

  return v_match_no;
end;
$$;

revoke all on function public.admin_save_match(jsonb, jsonb) from public;
grant execute on function public.admin_save_match(jsonb, jsonb) to authenticated;

-- 관리자 계정 등록 예시
-- 1) Authentication > Users > Add user 로 이메일/비밀번호 계정을 만든 뒤
-- 2) 아래 EMAIL 부분만 바꾸고 실행하세요.
-- insert into public.admin_users (user_id, role)
-- select id, 'owner' from auth.users where email = 'YOUR_ADMIN_EMAIL@example.com'
-- on conflict (user_id) do update set role = excluded.role, is_active = true;

-- ============================================================================
-- 캘린더/휴방/메뉴 데이터
-- ============================================================================

-- 일정/휴방/메뉴 설정 표(예전 정적 JSON에서 옮겨 왔다)

create table if not exists public.calendar_events (
  id bigint primary key,
  source_order integer not null unique,
  start_date date not null,
  end_date date not null,
  event_time text,
  person text not null default '',
  description text,
  detail text,
  color text
);
create index if not exists calendar_events_date_idx on public.calendar_events (start_date, end_date);

create table if not exists public.calendar_off_air (
  off_date date not null,
  soop_id text not null,
  source_order integer not null default 0,
  primary key (off_date, soop_id)
);
create index if not exists calendar_off_air_date_idx on public.calendar_off_air (off_date, source_order);

create table if not exists public.site_config (
  config_key text primary key,
  config_value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.calendar_events enable row level security;
alter table public.calendar_off_air enable row level security;
alter table public.site_config enable row level security;


-- 공개 사이트 읽기 권한
revoke all on public.calendar_events, public.calendar_off_air, public.site_config from anon;
grant select (id,source_order,start_date,end_date,event_time,person,description,detail,color) on public.calendar_events to anon;
grant select (off_date,soop_id,source_order) on public.calendar_off_air to anon;
grant select (config_key,config_value) on public.site_config to anon;

drop policy if exists "public_read_calendar_events" on public.calendar_events;
create policy "public_read_calendar_events" on public.calendar_events for select to anon using (true);
drop policy if exists "public_read_calendar_off_air" on public.calendar_off_air;
create policy "public_read_calendar_off_air" on public.calendar_off_air for select to anon using (true);
drop policy if exists "public_read_site_config" on public.site_config;
create policy "public_read_site_config" on public.site_config for select to anon using (config_key = 'nav');

-- 관리자 CRUD. public.is_admin()은 이 통합 설정의 앞부분에서 설치합니다.
do $$
declare t text;
begin
  foreach t in array array['calendar_events','calendar_off_air','site_config']
  loop
    execute format('drop policy if exists %I on public.%I', 'admins_all_' || t, t);
    execute format(
      'create policy %I on public.%I for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()))',
      'admins_all_' || t, t
    );
  end loop;
end $$;

grant select, insert, update, delete on public.calendar_events, public.calendar_off_air, public.site_config to authenticated;

-- ============================================================================
-- 운영 이미지 Storage (연혁 사진/팀 로고/커스텀 프로필)
-- ============================================================================

-- StarUniv 운영 콘텐츠/미디어 하이브리드 전환
-- 운영 메타데이터는 DB, 업로드 파일은 Storage, 디자인 고정 자산은 Git에 둔다.

alter table public.members add column if not exists avatar_path text;
alter table public.teams add column if not exists logo_path text;

create table if not exists public.history_entries (
  id text primary key,
  entry_kind text not null default 'manual' check (entry_kind in ('manual','override')),
  event_date date, event_type text, title text, description text,
  members jsonb not null default '[]'::jsonb, youtube_url text, image_path text,
  sort_order integer, hidden boolean not null default false, updated_at timestamptz not null default now()
);
alter table public.history_entries enable row level security;

-- 공개 Storage 버킷. URL은 공개지만 쓰기/삭제는 관리자만 가능하다.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('staruniv-media','staruniv-media',true,10485760,array['image/jpeg','image/png','image/webp','image/gif'])
on conflict (id) do update set public=excluded.public, file_size_limit=excluded.file_size_limit, allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "staruniv_media_public_read" on storage.objects;
create policy "staruniv_media_public_read" on storage.objects for select to public using (bucket_id='staruniv-media');
drop policy if exists "staruniv_media_admin_insert" on storage.objects;
create policy "staruniv_media_admin_insert" on storage.objects for insert to authenticated with check (bucket_id='staruniv-media' and (select public.is_admin()));
drop policy if exists "staruniv_media_admin_update" on storage.objects;
create policy "staruniv_media_admin_update" on storage.objects for update to authenticated using (bucket_id='staruniv-media' and (select public.is_admin())) with check (bucket_id='staruniv-media' and (select public.is_admin()));
drop policy if exists "staruniv_media_admin_delete" on storage.objects;
create policy "staruniv_media_admin_delete" on storage.objects for delete to authenticated using (bucket_id='staruniv-media' and (select public.is_admin()));

-- 현재 history.json 메타데이터를 최초 1회 시드한다. 운영 DB에 이미 같은 id가 있으면 건드리지 않는다.

-- ============================================================================
-- 공개 사이트 읽기 권한
-- ============================================================================

-- 공개 사이트가 Supabase를 직접 읽기 위한 최소 권한 설정.
-- 관리자(authenticated)의 CRUD 정책은 이 통합 설정의 관리자 정책을 유지합니다.

-- 공개 방문자는 사이트 화면에 실제로 쓰는 컬럼만 SELECT할 수 있습니다.
revoke all on public.members from anon;
revoke all on public.matches from anon;
revoke all on public.rounds from anon;
revoke all on public.tier_members from anon;

grant select (source_order, nickname, soop_id, birth_date, gender, race, tier, role, joined_date, left_date, mbti, avatar_path, youtube_url)
  on public.members to anon;
grant select (team_name, logo_path) on public.teams to anon;
grant select (source_order, match_no, match_date, opponent_team, match_format, method, final_result, set_result)
  on public.matches to anon;
grant select (source_order, match_no, match_date, opponent_team, match_format, set_name, round_name, our_player, our_race, result, opponent_player, opponent_race, map_name)
  on public.rounds to anon;
grant select (source_order, nickname, soop_id, race, tier, affiliation, modified_at)
  on public.tier_members to anon;

drop policy if exists "public_read_teams" on public.teams;
create policy "public_read_teams" on public.teams for select to anon using (true);
drop policy if exists "public_read_members" on public.members;
create policy "public_read_members" on public.members for select to anon using (true);
drop policy if exists "public_read_matches" on public.matches;
create policy "public_read_matches" on public.matches for select to anon using (true);
drop policy if exists "public_read_rounds" on public.rounds;
create policy "public_read_rounds" on public.rounds for select to anon using (true);
drop policy if exists "public_read_tier_members" on public.tier_members;
create policy "public_read_tier_members" on public.tier_members for select to anon using (true);


-- 일정/휴방/메뉴 설정도 공개 사이트가 직접 읽는다.
revoke all on public.calendar_events from anon;
revoke all on public.calendar_off_air from anon;
revoke all on public.site_config from anon;

grant select (id, source_order, start_date, end_date, event_time, person, description, detail, color)
  on public.calendar_events to anon;
grant select (off_date, soop_id, source_order) on public.calendar_off_air to anon;
grant select (config_key, config_value) on public.site_config to anon;

drop policy if exists "public_read_calendar_events" on public.calendar_events;
create policy "public_read_calendar_events" on public.calendar_events for select to anon using (true);
drop policy if exists "public_read_calendar_off_air" on public.calendar_off_air;
create policy "public_read_calendar_off_air" on public.calendar_off_air for select to anon using (true);
drop policy if exists "public_read_site_config" on public.site_config;
create policy "public_read_site_config" on public.site_config for select to anon using (config_key = 'nav');


-- 연혁은 공개 사이트에서 바로 읽는다.
revoke all on public.history_entries from anon;
grant select (id, entry_kind, event_date, event_type, title, description, members, youtube_url, image_path, sort_order, hidden) on public.history_entries to anon;
drop policy if exists "public_read_history_entries" on public.history_entries;
create policy "public_read_history_entries" on public.history_entries for select to anon using (true);


-- ============================================================================
-- 별도 영상 탭 (팬튜브 + 보자)
-- ============================================================================
create table if not exists public.video_channels (
  channel_url text primary key, channel_id text, title text, display_name text, thumb text, uploads text,
  source_order integer not null unique, active boolean not null default true, updated_at timestamptz not null default now()
);
create table if not exists public.videos (
  id text primary key, channel_url text, title text not null, published timestamptz, thumb text,
  views bigint not null default 0, short boolean not null default false, hidden boolean not null default false,
  updated_at timestamptz not null default now()
);
create index if not exists videos_published_idx on public.videos (published desc);
create index if not exists videos_channel_idx on public.videos (channel_url);
create table if not exists public.video_picks (
  id text primary key, kind text not null default 'youtube' check (kind in ('youtube','soop')), title text not null, note text,
  group_name text, group_en text, added_at date, author text, thumb text, short boolean not null default false,
  hidden boolean not null default false, source_order integer not null unique, updated_at timestamptz not null default now()
);
alter table public.video_channels enable row level security;
alter table public.videos enable row level security;
alter table public.video_picks enable row level security;

-- 관리자 CRUD
do $$ declare t text; begin
  foreach t in array array['video_channels','videos','video_picks'] loop
    execute format('drop policy if exists %I on public.%I', 'admins_all_' || t, t);
    execute format('create policy %I on public.%I for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()))', 'admins_all_' || t, t);
  end loop;
end $$;
grant select,insert,update,delete on public.video_channels,public.videos,public.video_picks to authenticated;

-- 공개 영상 탭 읽기
revoke all on public.video_channels,public.videos,public.video_picks from anon;
grant select (channel_url,channel_id,title,display_name,thumb,uploads,source_order,active) on public.video_channels to anon;
grant select (id,channel_url,title,published,thumb,views,short,hidden) on public.videos to anon;
grant select (id,kind,title,note,group_name,group_en,added_at,author,thumb,short,hidden,source_order) on public.video_picks to anon;
drop policy if exists public_read_video_channels on public.video_channels;
create policy public_read_video_channels on public.video_channels for select to anon using (active=true);
drop policy if exists public_read_videos on public.videos;
create policy public_read_videos on public.videos for select to anon using (true);
drop policy if exists public_read_video_picks on public.video_picks;
create policy public_read_video_picks on public.video_picks for select to anon using (true);
-- ============================================================================
-- 도구 > 외부도구 (기존 어드민 관리 링크)
-- 멀티뷰어/엔트리/캄몬라이더 자체 기능은 Git에 남고, 여기에는 외부 링크만 저장한다.
-- ============================================================================
create table if not exists public.external_tools (
  id bigint generated by default as identity primary key,
  category text not null check (category in ('extTools','extSites')),
  name text not null,
  url text not null,
  favicon text,
  source_order integer not null unique,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);
create index if not exists external_tools_category_order_idx on public.external_tools(category, source_order);
alter table public.external_tools enable row level security;

-- 현재 docs/data/tools.json 최초 시드. 이미 같은 URL이 있으면 건드리지 않는다.

-- 관리자 CRUD
drop policy if exists admins_all_external_tools on public.external_tools;
create policy admins_all_external_tools on public.external_tools for all to authenticated
using ((select public.is_admin())) with check ((select public.is_admin()));
grant select,insert,update,delete on public.external_tools to authenticated;
grant usage,select on sequence public.external_tools_id_seq to authenticated;

-- 공개 사이트 읽기
revoke all on public.external_tools from anon;
grant select (id,category,name,url,favicon,source_order,active) on public.external_tools to anon;
drop policy if exists public_read_external_tools on public.external_tools;
create policy public_read_external_tools on public.external_tools for select to anon using (active=true);


-- ############################################################################
-- 2. 공개 사이트 읽기 권한
-- ############################################################################

-- Idempotent public read grants for the browser-facing site.
-- Write access remains restricted to the existing authenticated admin policies.

revoke all on public.members from anon;
revoke all on public.teams from anon;
revoke all on public.matches from anon;
revoke all on public.rounds from anon;
revoke all on public.tier_members from anon;

grant select (source_order,nickname,soop_id,birth_date,gender,race,tier,role,joined_date,left_date,mbti,avatar_path,youtube_url) on public.members to anon;
grant select (source_order,team_name,logo_path) on public.teams to anon;
grant select (source_order,match_no,match_date,opponent_team,match_format,method,final_result,set_result) on public.matches to anon;
grant select (source_order,match_no,match_date,opponent_team,match_format,set_name,round_name,our_player,our_race,result,opponent_player,opponent_race,map_name) on public.rounds to anon;
grant select (source_order,nickname,soop_id,race,tier,affiliation,modified_at) on public.tier_members to anon;

drop policy if exists public_read_teams on public.teams;
create policy public_read_teams on public.teams for select to anon using (true);
drop policy if exists public_read_members on public.members;
create policy public_read_members on public.members for select to anon using (true);
drop policy if exists public_read_matches on public.matches;
create policy public_read_matches on public.matches for select to anon using (true);
drop policy if exists public_read_rounds on public.rounds;
create policy public_read_rounds on public.rounds for select to anon using (true);
drop policy if exists public_read_tier_members on public.tier_members;
create policy public_read_tier_members on public.tier_members for select to anon using (true);

revoke all on public.calendar_events from anon;
revoke all on public.calendar_off_air from anon;
revoke all on public.site_config from anon;
grant select (id,source_order,start_date,end_date,event_time,person,description,detail,color) on public.calendar_events to anon;
grant select (off_date,soop_id,source_order) on public.calendar_off_air to anon;
grant select (config_key,config_value) on public.site_config to anon;
drop policy if exists public_read_calendar_events on public.calendar_events;
create policy public_read_calendar_events on public.calendar_events for select to anon using (true);
drop policy if exists public_read_calendar_off_air on public.calendar_off_air;
create policy public_read_calendar_off_air on public.calendar_off_air for select to anon using (true);
drop policy if exists public_read_site_config on public.site_config;
create policy public_read_site_config on public.site_config for select to anon using (config_key='nav');

revoke all on public.history_entries from anon;
grant select (id,entry_kind,event_date,event_type,title,description,members,youtube_url,image_path,sort_order,hidden) on public.history_entries to anon;
drop policy if exists public_read_history_entries on public.history_entries;
create policy public_read_history_entries on public.history_entries for select to anon using (true);

revoke all on public.video_channels from anon;
revoke all on public.videos from anon;
revoke all on public.video_picks from anon;
grant select (channel_url,channel_id,title,display_name,thumb,uploads,source_order,active) on public.video_channels to anon;
grant select (id,channel_url,title,published,thumb,views,short,hidden) on public.videos to anon;
grant select (id,kind,title,note,group_name,group_en,added_at,author,thumb,short,hidden,source_order) on public.video_picks to anon;
drop policy if exists public_read_video_channels on public.video_channels;
create policy public_read_video_channels on public.video_channels for select to anon using (active=true);
drop policy if exists public_read_videos on public.videos;
create policy public_read_videos on public.videos for select to anon using (true);
drop policy if exists public_read_video_picks on public.video_picks;
create policy public_read_video_picks on public.video_picks for select to anon using (true);

revoke all on public.external_tools from anon;
grant select (id,category,name,url,favicon,source_order,active) on public.external_tools to anon;
drop policy if exists public_read_external_tools on public.external_tools;
create policy public_read_external_tools on public.external_tools for select to anon using (active=true);


-- ############################################################################
-- 3. 어드민 편집 보조(일정 색·감사 기록·일괄 수정)
-- ############################################################################

-- StarUniv inline admin editor migration.
-- 여러 번 실행해도 된다.

-- ---------------------------------------------------------------------------
-- Stable schedule color keys
-- ---------------------------------------------------------------------------
create or replace function public.staruniv_schedule_color_key(p_color text)
returns text
language plpgsql
immutable
as $$
declare
  c text := lower(trim(coalesce(p_color,'')));
  h text;
  r integer; g integer; b integer;
  best text := 'light_gray';
  best_d bigint := 9223372036854775807;
  pr integer; pg integer; pb integer;
  item record;
begin
  if c in ('red','orange','yellow','green','blue','indigo','purple','light_gray') then
    return c;
  end if;

  if c ~ '^#[0-9a-f]{3}$' then
    h := '#' || substr(c,2,1)||substr(c,2,1)||substr(c,3,1)||substr(c,3,1)||substr(c,4,1)||substr(c,4,1);
  elsif c ~ '^#[0-9a-f]{6}$' then
    h := c;
  else
    return 'light_gray';
  end if;

  r := ('x'||substr(h,2,2))::bit(8)::int;
  g := ('x'||substr(h,4,2))::bit(8)::int;
  b := ('x'||substr(h,6,2))::bit(8)::int;

  for item in
    select * from (values
      ('red',255,37,56),('orange',255,138,0),('yellow',255,212,59),('green',22,199,91),
      ('blue',22,119,255),('indigo',51,70,181),('purple',124,58,237),('light_gray',229,231,235)
    ) as p(k,rr,gg,bb)
  loop
    pr := r-item.rr; pg := g-item.gg; pb := b-item.bb;
    if (pr::bigint*pr + pg::bigint*pg + pb::bigint*pb) < best_d then
      best_d := pr::bigint*pr + pg::bigint*pg + pb::bigint*pb;
      best := item.k;
    end if;
  end loop;
  return best;
end;
$$;

update public.calendar_events
set color = public.staruniv_schedule_color_key(color)
where coalesce(color,'') not in ('red','orange','yellow','green','blue','indigo','purple','light_gray');

alter table public.calendar_events
  drop constraint if exists calendar_events_color_key_check;
alter table public.calendar_events
  add constraint calendar_events_color_key_check
  check (color is null or color in ('red','orange','yellow','green','blue','indigo','purple','light_gray'));

-- ---------------------------------------------------------------------------
-- Minimal audit log for destructive and bulk admin actions
-- ---------------------------------------------------------------------------
create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid references auth.users(id),
  action text not null,
  entity text not null,
  entity_id text,
  details jsonb not null default '{}'::jsonb
);
alter table public.admin_audit_log enable row level security;

drop policy if exists admins_read_audit_log on public.admin_audit_log;
create policy admins_read_audit_log
on public.admin_audit_log for select to authenticated
using ((select public.is_admin()));

revoke all on public.admin_audit_log from public, anon;
grant select on public.admin_audit_log to authenticated;
revoke all on sequence public.admin_audit_log_id_seq from anon, authenticated;   -- 기록은 admin_write_audit 함수로만 쓴다

create or replace function public.admin_write_audit(
  p_action text,
  p_entity text,
  p_entity_id text default null,
  p_details jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare v_id bigint;
begin
  if not public.is_admin() then raise exception 'admin only'; end if;
  insert into public.admin_audit_log(user_id,action,entity,entity_id,details)
  values(auth.uid(),p_action,p_entity,p_entity_id,coalesce(p_details,'{}'::jsonb))
  returning id into v_id;
  return v_id;
end;
$$;
revoke all on function public.admin_write_audit(text,text,text,jsonb) from public;
grant execute on function public.admin_write_audit(text,text,text,jsonb) to authenticated;

-- ---------------------------------------------------------------------------
-- Atomic bulk tier edits with audit
-- ---------------------------------------------------------------------------
create or replace function public.admin_bulk_update_tier_members(
  p_ids bigint[],
  p_affiliation text default null,
  p_tier text default null
)
returns integer
language plpgsql
security definer
set search_path=public
as $$
declare v_count integer;
begin
  if not public.is_admin() then raise exception 'admin only'; end if;
  if coalesce(array_length(p_ids,1),0)=0 then return 0; end if;
  if p_affiliation is null and p_tier is null then raise exception 'nothing to update'; end if;

  update public.tier_members
  set affiliation=coalesce(p_affiliation,affiliation),
      tier=coalesce(p_tier,tier),
      modified_at=to_char(timezone('Asia/Seoul',now()),'YYYY-MM-DD HH24:MI:SS')
  where id=any(p_ids);
  get diagnostics v_count = row_count;

  perform public.admin_write_audit(
    'bulk_update','tier_members',array_to_string(p_ids,','),
    jsonb_build_object('affiliation',p_affiliation,'tier',p_tier,'count',v_count)
  );
  return v_count;
end;
$$;
revoke all on function public.admin_bulk_update_tier_members(bigint[],text,text) from public;
grant execute on function public.admin_bulk_update_tier_members(bigint[],text,text) to authenticated;

-- Keep site config shape backwards compatible while establishing inline-editor defaults.
insert into public.site_config(config_key,config_value,updated_at)
values (
  'nav',
  jsonb_build_object(
    'hidden','[]'::jsonb,
    'order','["schedule","members","records","tier","video","stats","tools"]'::jsonb,
    'subtabs','{}'::jsonb,
    'heroDescriptions','{}'::jsonb,
    'homeCarousel','{}'::jsonb,
    'homeSections','{"live":true,"notices":true}'::jsonb
  ),
  now()
)
-- 이미 있으면 빠진 값만 기본값으로 채우고, 운영자가 저장한 값(다른 키 포함)은 그대로 둔다
on conflict (config_key) do update
set config_value = jsonb_build_object(
      'hidden','[]'::jsonb,
      'order','["schedule","members","records","tier","video","stats","tools"]'::jsonb,
      'subtabs','{}'::jsonb,
      'heroDescriptions','{}'::jsonb,
      'homeCarousel','{}'::jsonb,
      'homeSections','{"live":true,"notices":true}'::jsonb,
      'statsTabs','[]'::jsonb
    ) || site_config.config_value,
    updated_at=site_config.updated_at;


-- ############################################################################
-- 4. 어드민 대시보드 ELO 통계
-- ############################################################################

-- 관리자 대시보드 ELO exact 통계
create or replace function public.admin_elo_stats()
returns table (
  total bigint,
  min_match_id bigint,
  max_match_id bigint,
  first_match_date date,
  last_match_date date
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'admin access required' using errcode = '42501';
  end if;

  return query
  select
    count(*)::bigint,
    min(m.elo_match_id)::bigint,
    max(m.elo_match_id)::bigint,
    min(m.match_date)::date,
    max(m.match_date)::date
  from public.elo_matches m;
end;
$$;

revoke all on function public.admin_elo_stats() from public;
grant execute on function public.admin_elo_stats() to authenticated;


-- ############################################################################
-- 5. 달력 사진 갱신 버튼
-- ############################################################################

-- 어드민 일정 화면의 '달력 사진 갱신' 버튼이 부르는 함수.
-- 스타유니브 빌드(Build StarUniv web)를 실행해 docs/data/calendar.png를 새로 찍는다
-- (외부 자동화가 이 사진 주소를 가져간다). GitHub 토큰은 브라우저에 두지 않고 Vault에서 꺼내 쓴다.
-- GitHub 토큰 준비는 이 파일 맨 위 참고.
-- 버튼을 여러 번 눌러도 빌드가 줄줄이 쌓이지 않는다: 워크플로의 concurrency 설정 때문에
-- 도는 중인 빌드 하나 + 대기 하나만 남는다.

create extension if not exists pg_net with schema extensions;

-- 빌드 실행 요청. 반환값은 pg_net 요청 번호(결과 확인용).
create or replace function public.admin_request_calendar_capture()
returns bigint
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  token text;
  request_id bigint;
begin
  if not public.is_admin() then
    raise exception '관리자만 실행할 수 있습니다.';
  end if;
  select decrypted_secret into token
  from vault.decrypted_secrets
  where name = 'github_actions_token'
  limit 1;
  if token is null or token = '' then
    raise exception 'GitHub 토큰(github_actions_token)이 Vault에 없습니다.';
  end if;

  select net.http_post(
    url := 'https://api.github.com/repos/ststats/staruniv/actions/workflows/update.yml/dispatches',
    body := jsonb_build_object('ref', 'main'),
    headers := jsonb_build_object(
      'Authorization', 'Bearer ' || token,
      'Accept', 'application/vnd.github+json',
      'X-GitHub-Api-Version', '2022-11-28',
      'User-Agent', 'staruniv-supabase'
    )
  ) into request_id;
  return request_id;
end;
$$;

-- 요청 결과: GitHub 응답 코드(204면 성공). 아직 응답이 없으면 null.
create or replace function public.admin_calendar_capture_status(p_request_id bigint)
returns table (status_code integer, error text)
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if not public.is_admin() then
    raise exception '관리자만 실행할 수 있습니다.';
  end if;
  return query
    select r.status_code, coalesce(r.error_msg, case when r.status_code >= 300 then left(r.content::text, 300) end)
    from net._http_response r
    where r.id = p_request_id;
end;
$$;

revoke all on function public.admin_request_calendar_capture() from public, anon;
revoke all on function public.admin_calendar_capture_status(bigint) from public, anon;
grant execute on function public.admin_request_calendar_capture() to authenticated;
grant execute on function public.admin_calendar_capture_status(bigint) to authenticated;

-- (예전 안) 일정이 바뀔 때마다 자동으로 돌리던 트리거가 있으면 지운다
drop trigger if exists calendar_events_capture on public.calendar_events;
drop trigger if exists calendar_off_air_capture on public.calendar_off_air;
drop function if exists public.request_calendar_capture();


-- ############################################################################
-- 6. 티어표 갱신(반자동)
-- ############################################################################

-- 티어표 갱신(반자동): 펨코 티어표 이미지 주소 + FA 명단 글을 넣으면 GitHub Actions가
-- scripts/tier_table.py로 읽어 DB와 비교하고, 결과를 tier_update_jobs.result에 넣는다.
-- 관리자는 결과를 보고 반영할 것만 골라 반영한다(반영 함수는 이 절 아래쪽).
-- '달력 사진 갱신'과 같은 GitHub 토큰(Vault의 github_actions_token)을 쓴다.

create extension if not exists pg_net with schema extensions;

-- 분석 요청과 결과
create table if not exists public.tier_update_jobs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid(),
  image_url text not null,
  fa_text text,
  status text not null default 'queued'
    check (status in ('queued', 'running', 'done', 'failed', 'applied')),
  result jsonb,
  error text,
  started_at timestamptz,
  finished_at timestamptz,
  applied_at timestamptz
);
-- 반영 내용(다음 분석 때 확인된 카드를 기억에 더한다)과 GitHub 실행 요청 번호
alter table public.tier_update_jobs add column if not exists applied jsonb;
alter table public.tier_update_jobs add column if not exists learned_at timestamptz;
alter table public.tier_update_jobs add column if not exists dispatch_request bigint;
alter table public.tier_update_jobs enable row level security;
drop policy if exists tier_update_jobs_admin_read on public.tier_update_jobs;
create policy tier_update_jobs_admin_read on public.tier_update_jobs
  for select to authenticated using ((select public.is_admin()));
revoke all on public.tier_update_jobs from anon;
grant select on public.tier_update_jobs to authenticated;

-- 기억(학습): 확인된 카드의 티어·종족 글씨와 선수 사진 지문. 분석기만 쓴다(브라우저에서는 못 읽음).
create table if not exists public.tier_memory_glyphs (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('tier', 'race')),
  value text not null,
  feat text not null,
  bg text,
  created_at timestamptz not null default now()
);
create table if not exists public.tier_memory_photos (
  id bigint generated by default as identity primary key,
  soop_id text,
  nickname text not null,
  hash text not null,
  tier text,
  race text,
  tier_feat text,
  race_feat text,
  updated_at timestamptz not null default now()
);
create index if not exists tier_memory_photos_soop_idx on public.tier_memory_photos (soop_id);
alter table public.tier_memory_glyphs enable row level security;
alter table public.tier_memory_photos enable row level security;
revoke all on public.tier_memory_glyphs, public.tier_memory_photos from anon, authenticated;
-- 1절의 '모든 시퀀스 사용 허용'이 다시 실행될 때 여기 표들까지 넓어지지 않게(이 표들은 함수로만 쓴다)
revoke all on sequence public.tier_update_jobs_id_seq, public.tier_memory_glyphs_id_seq,
  public.tier_memory_photos_id_seq from anon, authenticated;

-- 분석 요청: 작업을 만들고 GitHub Actions(tier-analysis.yml)를 실행한다. 반환값: 작업 번호.
create or replace function public.admin_request_tier_analysis(p_image_url text, p_fa_text text default null)
returns bigint
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  token text;
  job_id bigint;
  req bigint;
begin
  if not coalesce(public.is_admin(), false) then
    raise exception '관리자만 실행할 수 있습니다.';
  end if;
  -- 펨코 이미지 서버 주소만 받는다(다른 주소를 Actions가 내려받지 않게)
  if p_image_url is null or p_image_url !~ '^https://image\.fmkorea\.com/' then
    raise exception '티어표 이미지 주소는 https://image.fmkorea.com/ 으로 시작해야 합니다.';
  end if;
  select decrypted_secret into token
  from vault.decrypted_secrets where name = 'github_actions_token' limit 1;
  if token is null or token = '' then
    raise exception 'GitHub 토큰(github_actions_token)이 Vault에 없습니다.';
  end if;

  insert into public.tier_update_jobs (image_url, fa_text)
  values (p_image_url, nullif(btrim(coalesce(p_fa_text, '')), ''))
  returning id into job_id;

  select net.http_post(
    url := 'https://api.github.com/repos/ststats/staruniv/actions/workflows/tier-analysis.yml/dispatches',
    body := jsonb_build_object('ref', 'main', 'inputs', jsonb_build_object('job_id', job_id::text)),
    headers := jsonb_build_object(
      'Authorization', 'Bearer ' || token,
      'Accept', 'application/vnd.github+json',
      'X-GitHub-Api-Version', '2022-11-28',
      'User-Agent', 'staruniv-supabase'
    )
  ) into req;
  update public.tier_update_jobs set dispatch_request = req where id = job_id;
  return job_id;
end;
$$;

revoke all on function public.admin_request_tier_analysis(text, text) from public, anon;
grant execute on function public.admin_request_tier_analysis(text, text) to authenticated;

-- GitHub 실행 요청의 응답(204면 성공). 작업이 오래 '대기'에 머물 때 관리자 화면이 원인을 보여 준다.
create or replace function public.admin_tier_job_dispatch_status(p_job_id bigint)
returns table (status_code integer, error text)
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if not coalesce(public.is_admin(), false) then
    raise exception '관리자만 실행할 수 있습니다.';
  end if;
  return query
    select r.status_code, coalesce(r.error_msg, case when r.status_code >= 300 then left(r.content::text, 300) end)
    from public.tier_update_jobs j join net._http_response r on r.id = j.dispatch_request
    where j.id = p_job_id;
end;
$$;
revoke all on function public.admin_tier_job_dispatch_status(bigint) from public, anon;
grant execute on function public.admin_tier_job_dispatch_status(bigint) to authenticated;

-- 반영: 관리자 화면에서 고른 변동을 tier_members에 한 번에 적용한다.
--   p_updates   [{id, affiliation?, tier?, race?, nickname?}]  바뀌는 칸만
--   p_inserts   [{nickname, tier, race, affiliation, soop_id?, elo_id?}] 새 선수
--   p_confirmed [{ref:[구역,카드], id} 또는 {ref, insert:새 선수 순번(0부터)}]  이 카드가 이 선수로 확인됨(학습용)
--   p_date      승급일로 적을 날짜(보통 티어표 글 날짜)
-- 소속이 대학으로 바뀌면 연혁 끝에 대학을 붙이고, 숫자 티어로 오르면 그 티어 승급일에 날짜를 더한다
-- (이미 날짜가 있으면 강등 뒤 재승급이라 쉼표로 이어 적는다).
create or replace function public.admin_apply_tier_update(
  p_job_id bigint, p_updates jsonb, p_inserts jsonb, p_confirmed jsonb, p_date date default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  ladder constant text[] := array['갓','킹','잭','조커','스페이드','0','1','2','3','4','5','6','7','8','베이비'];
  stamp text := to_char(timezone('Asia/Seoul', now()), 'YYYY-MM-DD HH24:MI:SS');
  d text := to_char(coalesce(p_date, timezone('Asia/Seoul', now())::date), 'YYYY-MM-DD');
  job_status text;
  u jsonb;
  r public.tier_members;
  new_aff text;
  new_tier text;
  hist text;
  col text;
  cur text;
  next_order integer;
  new_id bigint;
  ins_ids bigint[] := '{}';
  conf jsonb := '[]'::jsonb;
  pid bigint;
  n_upd integer := 0;
  log jsonb := '[]'::jsonb;   -- 반영 기록: 선수마다 바뀌기 전·후(관리자 화면의 '반영 내역')
  promoted text;
begin
  if not coalesce(public.is_admin(), false) then
    raise exception '관리자만 실행할 수 있습니다.';
  end if;
  select status into job_status from public.tier_update_jobs where id = p_job_id for update;
  if job_status is null then
    raise exception '작업 %이 없습니다.', p_job_id;
  end if;
  if job_status <> 'done' then
    raise exception '분석이 끝난 작업만 반영할 수 있습니다(지금: %).', job_status;
  end if;

  for u in select * from jsonb_array_elements(coalesce(p_updates, '[]'::jsonb)) loop
    select * into r from public.tier_members where id = (u->>'id')::bigint for update;
    if not found then
      raise exception '선수 번호 %이 없습니다.', u->>'id';
    end if;
    new_aff := coalesce(nullif(btrim(u->>'affiliation'), ''), r.affiliation);
    new_tier := coalesce(nullif(btrim(u->>'tier'), ''), r.tier);
    hist := r.history;
    promoted := null;
    if new_aff is distinct from r.affiliation and new_aff not in ('FA', '휴면')
       and btrim(regexp_replace(coalesce(hist, ''), '^.*,', '')) is distinct from new_aff then
      hist := case when coalesce(btrim(hist), '') = '' then new_aff else hist || ', ' || new_aff end;
    end if;
    -- 'N티어 승급' 칸 = 그 티어가 된 날. 승급뿐 아니라 강등으로 내려간 날도 그 티어 칸에 적는다
    -- (예전엔 승급만 적어서, 강등된 선수는 지금 티어와 마지막 날짜의 티어가 어긋났다).
    if new_tier is distinct from r.tier and new_tier ~ '^[0-8]$' then
      col := 'promoted_tier_' || new_tier;
      execute format('select %I from public.tier_members where id = $1', col) into cur using r.id;
      if array_position(ladder, new_tier) < coalesce(array_position(ladder, r.tier), 999) then
        promoted := new_tier;
      end if;
      if coalesce(cur, '') not like '%' || d || '%' then
        execute format('update public.tier_members set %I = $1 where id = $2', col)
          using case when coalesce(btrim(cur), '') = '' then d else cur || ', ' || d end, r.id;
      end if;
    end if;
    update public.tier_members set
      affiliation = new_aff,
      tier = new_tier,
      race = coalesce(nullif(btrim(u->>'race'), ''), race),
      nickname = coalesce(nullif(btrim(u->>'nickname'), ''), nickname),
      history = hist,
      modified_at = stamp
    where id = r.id;
    n_upd := n_upd + 1;
    log := log || jsonb_build_object('id', r.id, 'nickname', r.nickname,
      'before', jsonb_build_object('nickname', r.nickname, 'affiliation', r.affiliation, 'tier', r.tier, 'race', r.race),
      'after', jsonb_build_object('nickname', coalesce(nullif(btrim(u->>'nickname'), ''), r.nickname),
                                  'affiliation', new_aff, 'tier', new_tier,
                                  'race', coalesce(nullif(btrim(u->>'race'), ''), r.race)),
      'promoted', promoted);
  end loop;

  select coalesce(max(source_order), 0) into next_order from public.tier_members;
  for u in select * from jsonb_array_elements(coalesce(p_inserts, '[]'::jsonb)) loop
    if coalesce(btrim(u->>'nickname'), '') = '' then
      raise exception '새 선수 닉네임이 비었습니다.';
    end if;
    next_order := next_order + 1;
    -- ELO 대기 명단에서 고른 새 선수는 ELO ID(·SOOP ID)까지 넣어 전적·방송통계와 바로 이어진다
    insert into public.tier_members (source_order, nickname, soop_id, elo_id, tier, race, affiliation, history,
                                     modified_at, tier_table_registered)
    values (next_order, btrim(u->>'nickname'), nullif(btrim(u->>'soop_id'), ''),
            case when coalesce(u->>'elo_id', '') ~ '^[0-9]+$' then (u->>'elo_id')::int end,
            nullif(u->>'tier', ''),
            nullif(u->>'race', ''), nullif(u->>'affiliation', ''),
            case when u->>'affiliation' in ('FA', '휴면') then null else nullif(u->>'affiliation', '') end,
            stamp, d)
    returning id into new_id;
    ins_ids := ins_ids || new_id;
    log := log || jsonb_build_object('id', new_id, 'nickname', btrim(u->>'nickname'), 'new', true,
      'after', jsonb_build_object('nickname', btrim(u->>'nickname'), 'affiliation', nullif(u->>'affiliation', ''),
                                  'tier', nullif(u->>'tier', ''), 'race', nullif(u->>'race', '')));
  end loop;

  -- 확인된 카드: 반영이 끝난 뒤의 선수 정보로 적어 둔다(다음 분석이 사진·글씨를 이 값으로 기억)
  for u in select * from jsonb_array_elements(coalesce(p_confirmed, '[]'::jsonb)) loop
    pid := case when u ? 'insert' then ins_ids[(u->>'insert')::int + 1] else (u->>'id')::bigint end;
    select * into r from public.tier_members where id = pid;
    if found then
      conf := conf || jsonb_build_object('ref', u->'ref', 'id', r.id, 'soop_id', r.soop_id,
                                         'nickname', r.nickname, 'tier', r.tier, 'race', r.race);
    end if;
  end loop;

  update public.tier_update_jobs set status = 'applied', applied_at = now(),
    applied = jsonb_build_object('date', d, 'updates', coalesce(p_updates, '[]'::jsonb),
                                 'inserts', coalesce(p_inserts, '[]'::jsonb), 'confirmed', conf, 'log', log)
  where id = p_job_id;
  begin
    perform public.admin_write_audit('tier_table_update', 'tier_members', p_job_id::text,
      jsonb_build_object('updated', n_upd, 'inserted', coalesce(array_length(ins_ids, 1), 0)));
  exception when undefined_function then null;
  end;
  return jsonb_build_object('updated', n_upd, 'inserted', coalesce(array_length(ins_ids, 1), 0));
end;
$$;
revoke all on function public.admin_apply_tier_update(bigint, jsonb, jsonb, jsonb, date) from public, anon;
grant execute on function public.admin_apply_tier_update(bigint, jsonb, jsonb, jsonb, date) to authenticated;


-- ############################################################################
-- 7. 대학 로고(스타유니브·시너지 공용)
-- ############################################################################

-- 어드민 티어표 > 대학 로고에서 올린다. 브라우저가 긴 변 96px로 줄여 Storage(staruniv-media/logos/)에
-- 두고, 원본에서 뽑은 대표 색(시너지 카드 윗줄)을 함께 적는다. 두 사이트가 페이지를 열 때 이 표를 읽는다.
create table if not exists public.university_logos (
  name text primary key,
  path text not null,
  color text check (color is null or color ~ '^#[0-9a-f]{6}$'),
  updated_at timestamptz not null default now()
);
alter table public.university_logos enable row level security;
drop policy if exists university_logos_public_read on public.university_logos;
create policy university_logos_public_read on public.university_logos for select to anon, authenticated using (true);
drop policy if exists university_logos_admin_write on public.university_logos;
create policy university_logos_admin_write on public.university_logos for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
revoke all on public.university_logos from anon;
grant select on public.university_logos to anon;
grant select, insert, update, delete on public.university_logos to authenticated;

-- ############################################################################
-- 8. 한 선수의 다른 ELO 계정(종족 변경 등)
-- ############################################################################

-- EloBoard는 종족마다 계정(ELO ID)이 따로라 종족을 바꾸면 새 ELO ID가 생긴다. tier_members.elo_id는 메인 종족
-- 계정이고, 예전·다른 종족 계정은 여기에 '연결'만 해 둔다. 연결된 계정은 신규 인원에 다시 뜨지 않는다.
-- 전적·방송통계는 합치지 않는다(계정별 그대로).
create table if not exists public.tier_member_elo_links (
  elo_id integer primary key,
  tier_member_id bigint not null references public.tier_members(id) on delete cascade,
  elo_name text,
  race text,
  created_at timestamptz not null default now()
);
create index if not exists tier_member_elo_links_member_idx on public.tier_member_elo_links (tier_member_id);
alter table public.tier_member_elo_links enable row level security;
drop policy if exists tier_member_elo_links_admin on public.tier_member_elo_links;
create policy tier_member_elo_links_admin on public.tier_member_elo_links for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
revoke all on public.tier_member_elo_links from anon, authenticated;
grant select, insert, update, delete on public.tier_member_elo_links to authenticated;

-- 같은 ELO ID가 '메인 계정'과 '연결 계정'에 동시에 있으면 안 된다.
-- 같은 SOOP ID가 두 선수에 있으면 방송통계 일일 저장이 통째로 멈춘다(SOOP ID가 방송통계의 키).
-- 새로 넣거나 그 칸을 바꿀 때만 검사하므로, 이 파일을 다시 실행해도 기존 행 때문에 실패하지 않는다.
create or replace function public.tier_members_guard_ids()
returns trigger
language plpgsql
set search_path = public
as $$
declare other text;
begin
  if new.soop_id is not null and btrim(new.soop_id) <> ''
     and (tg_op = 'INSERT' or lower(btrim(new.soop_id)) is distinct from lower(btrim(coalesce(old.soop_id, '')))) then
    select nickname into other from public.tier_members
    where lower(btrim(soop_id)) = lower(btrim(new.soop_id)) and id <> coalesce(new.id, -1) limit 1;
    if found then
      raise exception 'SOOP ID %는 이미 % 선수가 쓰고 있습니다(같은 사람이면 새 선수를 만들지 말고 기존 선수를 고치세요)', new.soop_id, other;
    end if;
  end if;
  if new.elo_id is not null and (tg_op = 'INSERT' or new.elo_id is distinct from old.elo_id) then
    select m.nickname into other from public.tier_member_elo_links l join public.tier_members m on m.id = l.tier_member_id
    where l.elo_id = new.elo_id and l.tier_member_id <> coalesce(new.id, -1) limit 1;
    if found then
      raise exception 'ELO ID %는 % 선수의 연결 계정입니다', new.elo_id, other;
    end if;
    -- 자기 연결 계정을 '메인 계정'으로 올리면 연결 목록에서는 뺀다
    delete from public.tier_member_elo_links where elo_id = new.elo_id and tier_member_id = new.id;
  end if;
  return new;
end;
$$;
drop trigger if exists tier_members_guard_ids on public.tier_members;
create trigger tier_members_guard_ids before insert or update of soop_id, elo_id on public.tier_members
  for each row execute function public.tier_members_guard_ids();

create or replace function public.tier_member_elo_links_guard()
returns trigger
language plpgsql
set search_path = public
as $$
declare other text;
begin
  select nickname into other from public.tier_members where elo_id = new.elo_id limit 1;
  if found then
    raise exception 'ELO ID %는 이미 % 선수의 메인 계정입니다', new.elo_id, other;
  end if;
  return new;
end;
$$;
drop trigger if exists tier_member_elo_links_guard on public.tier_member_elo_links;
create trigger tier_member_elo_links_guard before insert or update of elo_id on public.tier_member_elo_links
  for each row execute function public.tier_member_elo_links_guard();

-- 메인 계정 바꾸기(메인 종족이 바뀐 경우): 연결 계정 하나를 메인으로 올리고, 옛 메인은 연결 계정으로 내린다.
-- 한 번에 처리해 옛 계정이 신규 인원에 다시 뜨지 않는다. 수정일은 오늘(그날부터 방송통계가 새 계정으로 센다).
-- 종족 칸은 바꾸지 않는다(티어표 갱신이나 선수 수정에서 고친다).
create or replace function public.admin_set_main_elo(p_member_id bigint, p_elo_id integer)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare m public.tier_members%rowtype;
begin
  if not public.is_admin() then raise exception 'admin only'; end if;
  select * into m from public.tier_members where id = p_member_id for update;
  if not found then raise exception '선수 번호 %이 없습니다', p_member_id; end if;
  if not exists (select 1 from public.tier_member_elo_links where elo_id = p_elo_id and tier_member_id = p_member_id) then
    raise exception 'ELO ID %는 이 선수의 연결 계정이 아닙니다', p_elo_id;
  end if;
  -- 메인을 바꾸면 트리거가 새 메인을 연결 목록에서 뺀다
  update public.tier_members
  set elo_id = p_elo_id,
      modified_at = to_char(timezone('Asia/Seoul', now()), 'YYYY-MM-DD HH24:MI:SS')
  where id = p_member_id;
  if m.elo_id is not null then
    -- 옛 메인 계정의 EloBoard 이름·종족(수집해 둔 원본). 없으면 비워 둔다.
    insert into public.tier_member_elo_links (elo_id, tier_member_id, elo_name, race)
    select m.elo_id, p_member_id, p.name, p.race
    from (select 1) one left join public.elo_players p on p.elo_id = m.elo_id
    on conflict (elo_id) do nothing;
  end if;
  perform public.admin_write_audit('set_main_elo', 'tier_members', p_member_id::text,
    jsonb_build_object('from', m.elo_id, 'to', p_elo_id, 'nickname', m.nickname));
end;
$$;
revoke all on function public.admin_set_main_elo(bigint, integer) from public, anon;
grant execute on function public.admin_set_main_elo(bigint, integer) to authenticated;

-- ############################################################################
-- 9. 멤버 ↔ 티어표 선수 연동
-- ############################################################################

-- 멤버 표 한 줄 = 한 번의 입단 기록(같은 사람이 두 번 들어오면 두 줄: 예 '진땅콩 T'·'진땅콩').
-- 사람 정보(SOOP ID·생년월일·성별·지금 티어)는 티어표 선수 명단(tier_members)이 원본이고, 연결된 멤버 줄의
-- 같은 칸은 DB가 자동으로 맞춘다(사이트·멀티뷰·빌드는 지금처럼 members 칸을 읽으면 된다).
-- 입단 기록 정보(그때 닉네임·종족·입단 티어·직책·입단일·퇴단일·MBTI·사진·YouTube·그때 쓴 ELO 계정)는 멤버 줄에만 있다.
alter table public.members
  add column if not exists tier_member_id bigint references public.tier_members(id) on delete set null;
-- 대표 사진(방송통계 TOP 칸). 프로필 원형 사진(avatar_path·SOOP 사진)과 따로, 잘 나온 사진 한 장.
alter table public.members add column if not exists photo_path text;
create index if not exists members_tier_member_idx on public.members (tier_member_id);

-- 처음 한 번: SOOP ID가 같은 티어표 선수에 잇는다(이미 이어진 줄은 건드리지 않는다). 이후엔 아래 트리거가 한다
update public.members m
set tier_member_id = t.id
from (select distinct on (lower(btrim(soop_id))) id, lower(btrim(soop_id)) as k
      from public.tier_members where coalesce(btrim(soop_id), '') <> '' order by lower(btrim(soop_id)), id) t
where m.tier_member_id is null and coalesce(btrim(m.soop_id), '') <> '' and lower(btrim(m.soop_id)) = t.k;

-- 티어표에 비어 있고 멤버 표에만 있던 생년월일·성별은 티어표로 옮겨 둔다(원본을 한 곳으로)
update public.tier_members t
set birth_date = coalesce(t.birth_date, m.birth_date),
    gender = coalesce(nullif(btrim(t.gender), ''), m.gender)
from (select distinct on (tier_member_id) tier_member_id, birth_date, nullif(btrim(gender), '') as gender
      from public.members where tier_member_id is not null
      order by tier_member_id, (birth_date is null), source_order) m
where t.id = m.tier_member_id
  and ((t.birth_date is null and m.birth_date is not null)
       or (coalesce(btrim(t.gender), '') = '' and m.gender is not null));

-- 연동 기준은 SOOP ID: 멤버 줄에 SOOP ID를 적으면 SOOP ID가 같은 티어표 선수에 자동으로 이어진다
-- (새로 넣을 때, 아직 안 이어진 줄, SOOP ID를 다른 값으로 고칠 때). 이어진 뒤에는 사람 정보를 티어표 값으로 채운다.
create or replace function public.members_fill_from_tier()
returns trigger
language plpgsql
set search_path = public
as $$
declare t public.tier_members%rowtype;
begin
  if coalesce(btrim(new.soop_id), '') <> ''
     and (new.tier_member_id is null
          or (tg_op = 'UPDATE' and lower(btrim(new.soop_id)) is distinct from lower(btrim(coalesce(old.soop_id, ''))))) then
    select id into new.tier_member_id from public.tier_members
    where lower(btrim(soop_id)) = lower(btrim(new.soop_id)) order by id limit 1;
  end if;
  if new.tier_member_id is null then return new; end if;
  select * into t from public.tier_members where id = new.tier_member_id;
  if not found then return new; end if;
  new.soop_id := coalesce(nullif(btrim(t.soop_id), ''), new.soop_id);
  new.birth_date := coalesce(t.birth_date, new.birth_date);
  new.gender := coalesce(nullif(btrim(t.gender), ''), new.gender);
  new.tier := coalesce(nullif(btrim(t.tier), ''), new.tier);
  return new;
end;
$$;
drop trigger if exists members_fill_from_tier on public.members;
create trigger members_fill_from_tier before insert or update on public.members
  for each row execute function public.members_fill_from_tier();

-- 티어표에서 사람 정보가 바뀌면(티어표 갱신·선수 수정) 연결된 멤버 줄에도 바로 반영한다
create or replace function public.tier_members_sync_members()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  update public.members set tier_member_id = tier_member_id   -- 위 트리거가 새 값으로 채운다
  where tier_member_id = new.id;
  return null;
end;
$$;
drop trigger if exists tier_members_sync_members on public.tier_members;
create trigger tier_members_sync_members after update of soop_id, birth_date, gender, tier on public.tier_members
  for each row execute function public.tier_members_sync_members();

-- 처음 한 번 전체 맞추기(연결된 줄만)
update public.members set tier_member_id = tier_member_id where tier_member_id is not null;
