-- StarUniv Supabase 전체 설정. SQL 편집기에 통째로 붙여 넣고 실행한다. 여러 번 실행해도 되고 운영 데이터는 건드리지 않는다.
-- 파이프라인(ELO·영상·방송 통계) 스키마는 ststat 저장소 supabase/ststat.sql이 맡는다(이 파일 다음에 실행).
--
-- 처음 한 번만 필요한 준비:
--   1) Authentication > Users에서 관리자 계정을 만든 뒤 등록:
--        insert into public.admin_users (user_id, role)
--        select id, 'owner' from auth.users where email = '관리자 이메일'
--        on conflict (user_id) do update set role = excluded.role, is_active = true;
--   2) GitHub 토큰(ststats/staruniv만, Actions = Read and write)을 Vault에 넣는다(토큰 값은 이 파일에 적지 말 것):
--        select vault.create_secret('<토큰>', 'github_actions_token');
--      바꿀 때: select vault.update_secret((select id from vault.secrets where name = 'github_actions_token'), '<새 토큰>');
--
-- 구성: 1 기본 스키마 → 2 공개 읽기 → 3 어드민 편집 보조 → 4 사이트 빌드 → 5 티어표 갱신 → 6 대학 로고
--       → 7 다른 ELO 계정 → 8 멤버 ↔ 티어표 연동 → 9 성별 → 10 종족 → 11 티어 표기 통일


-- ############################################################################
-- 1. 기본 스키마 · 관리자 권한 · 영상 · 도구
-- ############################################################################

-- ============================================================================
-- 기본 스키마
-- ============================================================================

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  source_order integer not null unique,
  team_name text not null,
  founders text,
  founded_date date,
  disbanded_date date,
  note text,
  championship text,
  logo_path text,
  -- 현황판(펨코 티어표)에 아직 없는 대학: 티어표 갱신이 이 대학 선수를 FA·휴면으로 바꾸지 않는다.
  off_board boolean not null default false
);
create index if not exists teams_team_name_idx on public.teams (team_name);

create table if not exists public.members (
  -- 내부 행 식별자. 외부 서비스 ID와 섞지 않는다.
  id bigint generated by default as identity primary key,
  source_order integer not null unique,
  -- 같은 사람의 기준 이름(예: 진땅콩)
  name text not null,
  -- 이 입단 기록에서 쓴 표시 닉네임(예: 진땅콩 T)
  nickname text not null,
  soop_id text,
  -- EloBoard 선수 ID(ELO 원본 players 객체의 key)
  elo_id integer,
  birth_date date,
  gender text,
  race text,
  join_tier text,
  tier text,
  role text,
  joined_date date,
  left_date date,
  mbti text,
  avatar_path text,
  youtube_url text,
  -- 대표 사진·영상(방송통계 TOP 칸). 저장소 파일(media/members/<SOOP ID>.mp4)을 가리킬 수도 있다.
  photo_path text
);
create index if not exists members_name_idx on public.members (name);
create index if not exists members_nickname_idx on public.members (nickname);
create index if not exists members_soop_id_idx on public.members (soop_id);
create index if not exists members_elo_id_idx on public.members (elo_id);

create table if not exists public.matches (
  match_no integer primary key,
  source_order integer not null unique,
  match_date date not null,
  opponent_team text not null,
  match_format text,
  method text,
  final_result text,
  set_result text,
  score_diff text,
  funding text,
  support_amount text,
  personal_amount text,
  challenge_mission text
);
create index if not exists matches_date_idx on public.matches (match_date desc);
create index if not exists matches_opponent_idx on public.matches (opponent_team);

create table if not exists public.rounds (
  id bigint generated by default as identity primary key,
  source_order integer not null unique,
  match_no integer not null references public.matches(match_no) on update cascade on delete cascade,
  match_date date not null,
  opponent_team text,
  match_format text,
  set_name text,
  round_name text,
  our_player text,
  our_race text,
  our_tier text,
  result text,
  opponent_player text,
  opponent_race text,
  opponent_tier text,
  map_name text
);
create index if not exists rounds_match_no_idx on public.rounds (match_no);
create index if not exists rounds_date_idx on public.rounds (match_date desc);
create index if not exists rounds_our_player_idx on public.rounds (our_player);
create index if not exists rounds_opponent_player_idx on public.rounds (opponent_player);

create table if not exists public.tier_members (
  id bigint generated by default as identity primary key,
  source_order integer not null unique,
  name text,
  nickname text not null,
  soop_id text,
  elo_id integer,
  birth_date date,
  gender text,
  race text,
  tier text,
  affiliation text,
  role text,
  modified_at text,
  history text,
  started_on text,
  elo_registered text,
  tier_table_registered text,
  promoted_tier_8 text,
  promoted_tier_7 text,
  promoted_tier_6 text,
  promoted_tier_5 text,
  promoted_tier_4 text,
  promoted_tier_3 text,
  promoted_tier_2 text,
  promoted_tier_1 text,
  promoted_tier_0 text
);
create unique index if not exists tier_members_elo_id_uq
  on public.tier_members (elo_id) where elo_id is not null;
create index if not exists tier_members_nickname_idx on public.tier_members (nickname);
create index if not exists tier_members_soop_id_idx on public.tier_members (soop_id);
create index if not exists tier_members_affiliation_idx on public.tier_members (affiliation);

-- ELO 원본. Actions가 외부 최신분을 증분 저장한다.
create table if not exists public.elo_categories (
  category_id smallint primary key,
  name text not null
);

create table if not exists public.elo_maps (
  map_id integer primary key,
  name text not null
);

create table if not exists public.elo_players (
  elo_id integer primary key,
  name text not null,
  race text
);
create index if not exists elo_players_name_idx on public.elo_players (name);

create table if not exists public.elo_matches (
  elo_match_id bigint primary key,
  match_date date not null,
  winner_elo_id integer references public.elo_players(elo_id),
  loser_elo_id integer references public.elo_players(elo_id),
  map_id integer references public.elo_maps(map_id),
  category_id smallint not null references public.elo_categories(category_id)
);
create index if not exists elo_matches_date_idx on public.elo_matches (match_date desc);
create index if not exists elo_matches_winner_idx on public.elo_matches (winner_elo_id);
create index if not exists elo_matches_loser_idx on public.elo_matches (loser_elo_id);
create index if not exists elo_matches_map_idx on public.elo_matches (map_id);
create index if not exists elo_matches_category_idx on public.elo_matches (category_id);

alter table public.teams enable row level security;
alter table public.members enable row level security;
alter table public.matches enable row level security;
alter table public.rounds enable row level security;
alter table public.tier_members enable row level security;
alter table public.elo_categories enable row level security;
alter table public.elo_maps enable row level security;
alter table public.elo_players enable row level security;
alter table public.elo_matches enable row level security;

create table if not exists public.calendar_events (
  id bigint primary key,
  source_order integer not null unique,
  start_date date not null,
  end_date date not null,
  event_time text,
  person text not null default '',
  description text,
  detail text,
  color text
);
create index if not exists calendar_events_date_idx on public.calendar_events (start_date, end_date);

create table if not exists public.calendar_off_air (
  off_date date not null,
  soop_id text not null,
  source_order integer not null default 0,
  primary key (off_date, soop_id)
);
create index if not exists calendar_off_air_date_idx on public.calendar_off_air (off_date, source_order);

create table if not exists public.site_config (
  config_key text primary key,
  config_value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.calendar_events enable row level security;
alter table public.calendar_off_air enable row level security;
alter table public.site_config enable row level security;
-- 연혁 사진은 Storage(staruniv-media)에 두고 image_path만 저장한다.
create table if not exists public.history_entries (
  id text primary key,
  entry_kind text not null default 'manual' check (entry_kind in ('manual','override')),
  event_date date,
  event_type text,
  title text,
  description text,
  members jsonb not null default '[]'::jsonb,
  youtube_url text,
  image_path text,
  sort_order integer,
  hidden boolean not null default false,
  updated_at timestamptz not null default now()
);
create index if not exists history_entries_date_idx on public.history_entries (event_date desc);

alter table public.history_entries enable row level security;

-- ============================================================================
-- 관리자 인증/RLS
-- ============================================================================

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'admin' check (role in ('owner', 'admin')),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

-- security definer라 admin_users 자체의 RLS 순환을 피한다.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users a
    where a.user_id = auth.uid()
      and a.is_active = true
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

drop policy if exists "admin_users_read_self" on public.admin_users;
create policy "admin_users_read_self"
on public.admin_users
for select
to authenticated
using (user_id = (select auth.uid()));

grant select on public.admin_users to authenticated;

do $$
declare
  t text;
begin
  foreach t in array array['teams','members','matches','rounds','tier_members','calendar_events','calendar_off_air','site_config','history_entries']
  loop
    execute format('drop policy if exists %I on public.%I', 'admins_all_' || t, t);
    execute format(
      'create policy %I on public.%I for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()))',
      'admins_all_' || t,
      t
    );
  end loop;
end $$;

grant select, insert, update, delete on public.teams, public.members,
  public.matches, public.rounds, public.tier_members, public.calendar_events, public.calendar_off_air, public.site_config, public.history_entries to authenticated;
grant usage, select on all sequences in schema public to authenticated;

do $$
declare
  t text;
begin
  foreach t in array array['elo_categories','elo_maps','elo_players','elo_matches']
  loop
    execute format('drop policy if exists %I on public.%I', 'admins_read_' || t, t);
    execute format(
      'create policy %I on public.%I for select to authenticated using ((select public.is_admin()))',
      'admins_read_' || t,
      t
    );
  end loop;
end $$;

grant select on public.elo_categories, public.elo_maps, public.elo_players, public.elo_matches to authenticated;

-- 경기와 세트를 한 트랜잭션으로 저장한다. 수정 때는 source_order를 지키고 세트 목록은 통째로 바꾼다.
create or replace function public.admin_save_match(p_match jsonb, p_rounds jsonb default '[]'::jsonb)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_match_no integer;
  v_source_order integer;
  v_round_source integer;
  r jsonb;
begin
  if not public.is_admin() then
    raise exception 'admin only';
  end if;

  v_match_no := nullif(p_match->>'match_no', '')::integer;
  if v_match_no is null then
    select coalesce(max(match_no), 0) + 1 into v_match_no from public.matches;
  end if;

  v_source_order := nullif(p_match->>'source_order', '')::integer;
  if v_source_order is null then
    select coalesce(max(source_order), 0) + 1 into v_source_order from public.matches;
  end if;

  insert into public.matches (
    match_no, source_order, match_date, opponent_team, match_format, method,
    final_result, set_result, score_diff, funding, support_amount, personal_amount, challenge_mission
  ) values (
    v_match_no,
    v_source_order,
    nullif(p_match->>'match_date','')::date,
    nullif(p_match->>'opponent_team',''),
    nullif(p_match->>'match_format',''),
    nullif(p_match->>'method',''),
    nullif(p_match->>'final_result',''),
    nullif(p_match->>'set_result',''),
    nullif(p_match->>'score_diff',''),
    nullif(p_match->>'funding',''),
    nullif(p_match->>'support_amount',''),
    nullif(p_match->>'personal_amount',''),
    nullif(p_match->>'challenge_mission','')
  )
  on conflict (match_no) do update set
    source_order = excluded.source_order,
    match_date = excluded.match_date,
    opponent_team = excluded.opponent_team,
    match_format = excluded.match_format,
    method = excluded.method,
    final_result = excluded.final_result,
    set_result = excluded.set_result,
    score_diff = excluded.score_diff,
    funding = excluded.funding,
    support_amount = excluded.support_amount,
    personal_amount = excluded.personal_amount,
    challenge_mission = excluded.challenge_mission;

  delete from public.rounds where match_no = v_match_no;
  select coalesce(max(source_order), 0) into v_round_source from public.rounds;

  for r in select value from jsonb_array_elements(coalesce(p_rounds, '[]'::jsonb))
  loop
    v_round_source := v_round_source + 1;
    insert into public.rounds (
      source_order, match_no, match_date, opponent_team, match_format,
      set_name, round_name, our_player, our_race, our_tier, result,
      opponent_player, opponent_race, opponent_tier, map_name
    ) values (
      v_round_source,
      v_match_no,
      nullif(coalesce(r->>'match_date', p_match->>'match_date'),'')::date,
      nullif(coalesce(r->>'opponent_team', p_match->>'opponent_team'),''),
      nullif(coalesce(r->>'match_format', p_match->>'match_format'),''),
      nullif(r->>'set_name',''),
      nullif(r->>'round_name',''),
      nullif(r->>'our_player',''),
      nullif(r->>'our_race',''),
      nullif(r->>'our_tier',''),
      nullif(r->>'result',''),
      nullif(r->>'opponent_player',''),
      nullif(r->>'opponent_race',''),
      nullif(r->>'opponent_tier',''),
      nullif(r->>'map_name','')
    );
  end loop;

  return v_match_no;
end;
$$;

revoke all on function public.admin_save_match(jsonb, jsonb) from public;
grant execute on function public.admin_save_match(jsonb, jsonb) to authenticated;


-- ============================================================================
-- 운영 이미지 Storage (연혁 사진/팀 로고/커스텀 프로필)
-- ============================================================================

-- 공개 버킷: URL은 공개지만 쓰기·삭제는 관리자만.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('staruniv-media','staruniv-media',true,10485760,array['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/webm'])
on conflict (id) do update set public=excluded.public, file_size_limit=excluded.file_size_limit, allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "staruniv_media_public_read" on storage.objects;
create policy "staruniv_media_public_read" on storage.objects for select to public using (bucket_id='staruniv-media');
drop policy if exists "staruniv_media_admin_insert" on storage.objects;
create policy "staruniv_media_admin_insert" on storage.objects for insert to authenticated with check (bucket_id='staruniv-media' and (select public.is_admin()));
drop policy if exists "staruniv_media_admin_update" on storage.objects;
create policy "staruniv_media_admin_update" on storage.objects for update to authenticated using (bucket_id='staruniv-media' and (select public.is_admin())) with check (bucket_id='staruniv-media' and (select public.is_admin()));
drop policy if exists "staruniv_media_admin_delete" on storage.objects;
create policy "staruniv_media_admin_delete" on storage.objects for delete to authenticated using (bucket_id='staruniv-media' and (select public.is_admin()));


-- ============================================================================
-- 별도 영상 탭 (팬튜브 + 보자)
-- ============================================================================
create table if not exists public.video_channels (
  channel_url text primary key, channel_id text, title text, display_name text, thumb text, uploads text,
  source_order integer not null unique, active boolean not null default true, updated_at timestamptz not null default now()
);
create table if not exists public.videos (
  id text primary key, channel_url text, title text not null, published timestamptz, thumb text,
  views bigint not null default 0, short boolean not null default false, hidden boolean not null default false,
  updated_at timestamptz not null default now()
);
create index if not exists videos_published_idx on public.videos (published desc);
create index if not exists videos_channel_idx on public.videos (channel_url);
create table if not exists public.video_picks (
  id text primary key, kind text not null default 'youtube' check (kind in ('youtube','soop')), title text not null, note text,
  group_name text, group_en text, author text, thumb text, short boolean not null default false,
  hidden boolean not null default false, source_order integer not null unique, updated_at timestamptz not null default now()
);
alter table public.video_channels enable row level security;
alter table public.videos enable row level security;
alter table public.video_picks enable row level security;

do $$ declare t text; begin
  foreach t in array array['video_channels','videos','video_picks'] loop
    execute format('drop policy if exists %I on public.%I', 'admins_all_' || t, t);
    execute format('create policy %I on public.%I for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()))', 'admins_all_' || t, t);
  end loop;
end $$;
grant select,insert,update,delete on public.video_channels,public.videos,public.video_picks to authenticated;

-- ============================================================================
-- 도구 > 외부도구(외부 링크만. 멀티뷰어 등 자체 기능은 Git에 있다)
-- ============================================================================
create table if not exists public.external_tools (
  id bigint generated by default as identity primary key,
  category text not null check (category in ('extTools','extSites')),
  name text not null,
  url text not null,
  favicon text,
  source_order integer not null unique,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);
create index if not exists external_tools_category_order_idx on public.external_tools(category, source_order);
alter table public.external_tools enable row level security;

drop policy if exists admins_all_external_tools on public.external_tools;
create policy admins_all_external_tools on public.external_tools for all to authenticated
using ((select public.is_admin())) with check ((select public.is_admin()));
grant select,insert,update,delete on public.external_tools to authenticated;
grant usage,select on sequence public.external_tools_id_seq to authenticated;


-- ############################################################################
-- 2. 공개 사이트 읽기 권한
-- ############################################################################

-- anon은 표를 하나도 읽지 않고 공개 읽기 함수(api_*)만 부른다. 무엇을 내보낼지는 각 함수의 거르기 조건이 정한다.
-- 새 데이터가 필요하면 표 권한이 아니라 함수를 더한다(방송·통계·공지·ELO 함수는 ststat.sql 14번).
--   · 생일·성별은 공개 정보다(운영 결정 2026-09-26). 티어표 명단(api_tier_members)에는 넣지 않는다.
--   · 휴면 선수는 사이트에 안 나오므로 SOOP ID 등도 공개하지 않는다(운영 결정 2026-09-27).

revoke all on public.members, public.teams, public.matches, public.rounds, public.tier_members,
  public.admin_users, public.calendar_events, public.calendar_off_air, public.site_config, public.history_entries,
  public.video_channels, public.videos, public.video_picks, public.external_tools from anon;

-- 공휴일. 정기 빌드(scripts/sync_holidays.py)가 source='auto' 행을 맞추고 'manual' 행은 남긴다.
create table if not exists public.holidays (
  day date primary key,
  name text,
  source text not null default 'manual' check (source in ('auto', 'manual')),
  updated_at timestamptz not null default now()
);
alter table public.holidays enable row level security;
drop policy if exists admins_all_holidays on public.holidays;
create policy admins_all_holidays on public.holidays for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
revoke all on public.holidays from anon;
grant select, insert, update, delete on public.holidays to authenticated;

-- 공개 읽기 함수(/api/v1): 함수 하나가 api/openapi.yaml의 주소 하나다. 화면이 그리는 열만 JSON으로 돌려준다.
create or replace function public.api_site_nav() returns jsonb
language sql stable security definer set search_path = public as $$
  select coalesce((select config_value from public.site_config where config_key = 'nav'), '{}'::jsonb);
$$;

create or replace function public.api_schedule() returns json
language sql stable security definer set search_path = public as $$
  select json_build_object(
    'events', coalesce((select json_agg(json_build_object('id', id, 'start_date', start_date, 'end_date', end_date,
        'event_time', event_time, 'person', person, 'description', description, 'detail', detail, 'color', color)
        order by source_order) from public.calendar_events), '[]'::json),
    'offAir', coalesce((select json_agg(json_build_object('off_date', off_date, 'soop_id', soop_id)
        order by off_date, source_order) from public.calendar_off_air), '[]'::json));
$$;

create or replace function public.api_schedule_on(p_date date) returns json
language sql stable security definer set search_path = public as $$
  select coalesce(json_agg(json_build_object('start_date', start_date, 'end_date', end_date, 'event_time', event_time,
      'person', person, 'description', description) order by source_order), '[]'::json)
  from public.calendar_events where start_date <= p_date and end_date >= p_date;
$$;

-- 자동 항목을 숨기는 override 행은 준다(페이지가 무엇을 숨길지 알아야 한다)
create or replace function public.api_history() returns json
language sql stable security definer set search_path = public as $$
  select coalesce(json_agg(json_build_object('id', id, 'entry_kind', entry_kind, 'event_date', event_date,
      'event_type', event_type, 'title', title, 'description', description, 'members', members,
      'youtube_url', youtube_url, 'image_path', image_path, 'sort_order', sort_order, 'hidden', hidden)
      order by event_date desc nulls last), '[]'::json)
  from public.history_entries where not hidden or entry_kind = 'override';
$$;

create or replace function public.api_tier_members() returns json
language sql stable security definer set search_path = public as $$
  select coalesce(json_agg(json_build_object('nickname', nickname, 'soop_id', soop_id, 'race', race, 'tier', tier,
      'affiliation', affiliation, 'modified_at', modified_at) order by source_order, soop_id), '[]'::json)
  from public.tier_members where coalesce(affiliation, '') <> '휴면';
$$;

-- 관리자도 같은 함수를 쓰고, 숨긴 항목을 달라고 하면 여기서 권한을 확인한다.
drop function if exists public.api_videos();
create or replace function public.api_videos(
  p_channel text default null,
  p_before timestamptz default null,
  p_before_id text default null,
  p_limit integer default 20,
  p_admin boolean default false
) returns jsonb
language plpgsql stable security definer set search_path = public as $$
declare v_limit integer := greatest(1, least(coalesce(p_limit,20),100)); v_result jsonb;
begin
  if p_admin and not coalesce(public.is_admin(),false) then raise exception 'admin only'; end if;
  with channels as (
    select channel_url,channel_id,title,display_name,thumb,uploads,source_order,active
    from public.video_channels where p_admin or active
  ), eligible as (
    select v.id,v.channel_url,v.title,v.published,v.thumb,v.views,v.short,v.hidden
    from public.videos v join channels c using(channel_url)
    where (p_admin or not v.hidden) and v.id ~ '^[A-Za-z0-9_-]{11}$'
  ), selected as (
    select * from eligible where p_channel is null or channel_url=p_channel
  ), page as (
    select * from selected where not short and
      (p_before_id is null or (coalesce(published,'-infinity'::timestamptz),id)
        < (coalesce(p_before,'-infinity'::timestamptz),p_before_id))
    order by published desc nulls last,id desc limit v_limit+1
  ), shown as (
    select * from page order by published desc nulls last,id desc limit v_limit
  )
  select jsonb_build_object(
    'videos',coalesce((select jsonb_agg(to_jsonb(v) order by published desc nulls last,id desc) from shown v),'[]'::jsonb),
    'next',case when (select count(*) from page)>v_limit then
      (select jsonb_build_object('published',published,'id',id) from shown
       order by published asc nulls first,id asc limit 1) else null end,
    'summary',case when p_before_id is null then jsonb_build_object(
      'channels',coalesce((select jsonb_agg(to_jsonb(c)||jsonb_build_object('count',
        (select count(*) from eligible e where e.channel_url=c.channel_url)) order by source_order) from channels c),'[]'::jsonb),
      'total',(select count(*) from selected where not short),
      'top',coalesce((select jsonb_agg(to_jsonb(v) order by views desc,published desc,id desc) from
        (select * from selected where not short and published>=now()-interval '30 days'
         order by views desc,published desc,id desc limit 3) v),'[]'::jsonb),
      'shorts',coalesce((select jsonb_agg(to_jsonb(v) order by published desc nulls last,id desc) from
        (select * from selected where short order by published desc nulls last,id desc limit 24) v),'[]'::jsonb),
      'picks',coalesce((select jsonb_agg(to_jsonb(v) order by source_order) from (
        select id,kind,title,note,group_name,group_en,author,thumb,short,hidden,source_order
        from public.video_picks where (p_admin or not hidden)
          and id ~ '^([A-Za-z0-9_-]{11}|soop:[0-9]{1,20})$') v),'[]'::jsonb)
    ) else null end
  ) into v_result;
  return v_result;
end;
$$;

create or replace function public.api_tools() returns json
language sql stable security definer set search_path = public as $$
  select coalesce(json_agg(json_build_object('id', id, 'category', category, 'name', name, 'url', url,
      'favicon', favicon) order by source_order), '[]'::json)
  from public.external_tools where active;
$$;

-- 멤버 목록. 순서 목록은 core.js SITE_ORDER와 같아야 한다(npm test가 확인).
-- _id는 프로필 칸(api_member_profiles)을 붙이는 열쇠다.
create or replace function public.api_site_members() returns json
language sql stable security definer set search_path = public as $$
  with o as (
    select array['감독','코치','선수'] as roles,
           array['갓','킹','잭','조커','스페이드','0','1','2','3','4','5','6','7','8','베이비'] as tiers
  )
  select json_build_object(
    'members', coalesce((select json_agg(json_build_object(
        '_id', m.id,
        '이름', coalesce(m.nickname, ''),
        'SOOP ID', case when btrim(m.soop_id) ~ '^-?[0-9]+$' then to_json(btrim(m.soop_id)::numeric) else to_json(coalesce(m.soop_id, '')) end,
        '성별', case when btrim(m.gender) in ('남', '남성', '남자') or upper(btrim(m.gender)) in ('M', 'MALE') then '남자'
                     when btrim(m.gender) in ('여', '여성', '여자') or upper(btrim(m.gender)) in ('F', 'FEMALE') then '여자'
                     else coalesce(m.gender, '') end,
        '종족', coalesce(m.race, ''),
        '티어', case when btrim(m.tier) ~ '^-?[0-9]+$' then to_json(btrim(m.tier)::numeric) else to_json(coalesce(m.tier, '')) end,
        '직책', coalesce(m.role, ''),
        '입단일', coalesce(m.joined_date::text, ''),
        '퇴단일', coalesce(m.left_date::text, ''),
        '대표 사진', coalesce(m.photo_path, ''))
      order by coalesce(array_position(o.roles, coalesce(nullif(m.role, ''), '선수')), 99),
               coalesce(array_position(o.tiers, regexp_replace(btrim(coalesce(m.tier, '')), '티어$', '')), 99),
               coalesce(m.joined_date::text, '9999'), coalesce(m.nickname, '') collate "C", m.source_order)
      from public.members m, o), '[]'::json),
    'matchCount', (select count(*) from public.matches),
    'roundCount', (select count(*) from public.rounds));
$$;

-- 멤버 프로필 창에서만 보이는 칸(멤버 페이지만 받는다)
create or replace function public.api_member_profiles() returns json
language sql stable security definer set search_path = public as $$
  select json_build_object('profiles', coalesce(json_object_agg(m.id, json_build_object(
      '생년월일', coalesce(m.birth_date::text, ''),
      'MBTI', coalesce(m.mbti, ''),
      'YouTube', coalesce(m.youtube_url, ''),
      'ELO ID', coalesce(to_json(m.elo_id), to_json(''::text)),
      '입단 티어', case when btrim(m.join_tier) ~ '^-?[0-9]+$' then to_json(btrim(m.join_tier)::numeric) else to_json(coalesce(m.join_tier, '')) end)),
    '{}'::json))
  from public.members m;
$$;

create or replace function public.api_team_order() returns json
language sql stable security definer set search_path = public as $$
  select coalesce(json_agg(team_name order by founded_date nulls last, source_order), '[]'::json) from public.teams;
$$;

create or replace function public.api_holidays() returns json
language sql stable security definer set search_path = public as $$
  select coalesce(json_object_agg(day::text, true order by day), '{}'::json) from public.holidays;
$$;

revoke all on function public.api_site_nav(), public.api_schedule(), public.api_schedule_on(date),
  public.api_history(), public.api_tier_members(), public.api_videos(text,timestamptz,text,integer,boolean), public.api_tools(),
  public.api_site_members(), public.api_member_profiles(), public.api_holidays(),
  public.api_team_order() from public;
grant execute on function public.api_site_nav(), public.api_schedule(), public.api_schedule_on(date),
  public.api_history(), public.api_tier_members(), public.api_videos(text,timestamptz,text,integer,boolean), public.api_tools(),
  public.api_site_members(), public.api_member_profiles(), public.api_holidays(),
  public.api_team_order() to anon, authenticated;


-- ############################################################################
-- 3. 어드민 편집 보조(일정 색·감사 기록·일괄 수정)
-- ############################################################################

-- calendar.js CAL_COLOR_PALETTE와 같은 8가지
alter table public.calendar_events
  drop constraint if exists calendar_events_color_key_check;
alter table public.calendar_events
  add constraint calendar_events_color_key_check
  check (color is null or color in ('red','orange','yellow','green','blue','indigo','purple','light_gray'));

-- 삭제·일괄 수정 감사 기록
create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid references auth.users(id),
  action text not null,
  entity text not null,
  entity_id text,
  details jsonb not null default '{}'::jsonb
);
alter table public.admin_audit_log enable row level security;

drop policy if exists admins_read_audit_log on public.admin_audit_log;
create policy admins_read_audit_log
on public.admin_audit_log for select to authenticated
using ((select public.is_admin()));

revoke all on public.admin_audit_log from public, anon;
grant select on public.admin_audit_log to authenticated;
revoke all on sequence public.admin_audit_log_id_seq from anon, authenticated;   -- 기록은 admin_write_audit로만

create or replace function public.admin_write_audit(
  p_action text,
  p_entity text,
  p_entity_id text default null,
  p_details jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare v_id bigint;
begin
  if not public.is_admin() then raise exception 'admin only'; end if;
  insert into public.admin_audit_log(user_id,action,entity,entity_id,details)
  values(auth.uid(),p_action,p_entity,p_entity_id,coalesce(p_details,'{}'::jsonb))
  returning id into v_id;
  return v_id;
end;
$$;
revoke all on function public.admin_write_audit(text,text,text,jsonb) from public;
grant execute on function public.admin_write_audit(text,text,text,jsonb) to authenticated;

-- 티어 일괄 수정(감사 기록과 한 트랜잭션)
create or replace function public.admin_bulk_update_tier_members(
  p_ids bigint[],
  p_affiliation text default null,
  p_tier text default null
)
returns integer
language plpgsql
security definer
set search_path=public
as $$
declare v_count integer;
begin
  if not public.is_admin() then raise exception 'admin only'; end if;
  if coalesce(array_length(p_ids,1),0)=0 then return 0; end if;
  if p_affiliation is null and p_tier is null then raise exception 'nothing to update'; end if;

  update public.tier_members
  set affiliation=coalesce(p_affiliation,affiliation),
      tier=coalesce(p_tier,tier),
      modified_at=to_char(timezone('Asia/Seoul',now()),'YYYY-MM-DD HH24:MI:SS')
  where id=any(p_ids);
  get diagnostics v_count = row_count;

  perform public.admin_write_audit(
    'bulk_update','tier_members',array_to_string(p_ids,','),
    jsonb_build_object('affiliation',p_affiliation,'tier',p_tier,'count',v_count)
  );
  return v_count;
end;
$$;
revoke all on function public.admin_bulk_update_tier_members(bigint[],text,text) from public;
grant execute on function public.admin_bulk_update_tier_members(bigint[],text,text) to authenticated;

insert into public.site_config(config_key,config_value,updated_at)
values (
  'nav',
  jsonb_build_object(
    'hidden','[]'::jsonb,
    'order','["schedule","members","records","tier","video","stats","tools"]'::jsonb,
    'subtabs','{}'::jsonb,
    'heroDescriptions','{}'::jsonb,
    'homeCarousel','{}'::jsonb,
    'homeSections','{"live":true,"notices":true}'::jsonb
  ),
  now()
)
-- 빠진 값만 채우고 운영자가 저장한 값은 그대로 둔다
on conflict (config_key) do update
set config_value = jsonb_build_object(
      'hidden','[]'::jsonb,
      'order','["schedule","members","records","tier","video","stats","tools"]'::jsonb,
      'subtabs','{}'::jsonb,
      'heroDescriptions','{}'::jsonb,
      'homeCarousel','{}'::jsonb,
      'homeSections','{"live":true,"notices":true}'::jsonb,
      'statsTabs','[]'::jsonb
    ) || site_config.config_value,
    updated_at=site_config.updated_at;


-- ############################################################################
-- 4. 사이트 빌드 버튼
-- ############################################################################

-- 어드민 '사이트 빌드' 버튼: build.yml을 실행한다(함수 이름 calendar_capture는 달력 사진(docs/data/calendar.png)도 만들어서).
-- GitHub 토큰은 브라우저에 두지 않고 Vault에서 꺼낸다. 여러 번 눌러도 워크플로 concurrency로 쌓이지 않는다.

create extension if not exists pg_net with schema extensions;

create or replace function public.admin_request_calendar_capture()
returns bigint
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  token text;
  request_id bigint;
begin
  if not public.is_admin() then
    raise exception '관리자만 실행할 수 있습니다.';
  end if;
  select decrypted_secret into token
  from vault.decrypted_secrets
  where name = 'github_actions_token'
  limit 1;
  if token is null or token = '' then
    raise exception 'GitHub 토큰(github_actions_token)이 Vault에 없습니다.';
  end if;

  select net.http_post(
    url := 'https://api.github.com/repos/ststats/staruniv/actions/workflows/build.yml/dispatches',
    body := jsonb_build_object('ref', 'main'),
    headers := jsonb_build_object(
      'Authorization', 'Bearer ' || token,
      'Accept', 'application/vnd.github+json',
      'X-GitHub-Api-Version', '2022-11-28',
      'User-Agent', 'staruniv-supabase'
    )
  ) into request_id;
  return request_id;
end;
$$;

-- GitHub 응답 코드(204면 성공). 아직 응답이 없으면 null.
create or replace function public.admin_calendar_capture_status(p_request_id bigint)
returns table (status_code integer, error text)
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if not public.is_admin() then
    raise exception '관리자만 실행할 수 있습니다.';
  end if;
  return query
    select r.status_code, coalesce(r.error_msg, case when r.status_code >= 300 then left(r.content::text, 300) end)
    from net._http_response r
    where r.id = p_request_id;
end;
$$;

revoke all on function public.admin_request_calendar_capture() from public, anon;
revoke all on function public.admin_calendar_capture_status(bigint) from public, anon;
grant execute on function public.admin_request_calendar_capture() to authenticated;
grant execute on function public.admin_calendar_capture_status(bigint) to authenticated;


-- ############################################################################
-- 5. 티어표 갱신(반자동)
-- ############################################################################

-- 티어표 이미지 + FA 명단 글을 Actions(scripts/tier_table.py)가 DB와 비교해 tier_update_jobs.result에 넣고,
-- 관리자가 골라 반영한다. 4번과 같은 GitHub 토큰을 쓴다.

create extension if not exists pg_net with schema extensions;

create table if not exists public.tier_update_jobs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid(),
  image_url text not null,
  fa_text text,
  status text not null default 'queued'
    check (status in ('queued', 'running', 'done', 'failed', 'applied')),
  result jsonb,
  error text,
  started_at timestamptz,
  finished_at timestamptz,
  applied_at timestamptz,
  applied jsonb,
  learned_at timestamptz,
  dispatch_request bigint
);
-- 실행권은 워크플로 제한(15분)보다 긴 20분
alter table public.tier_update_jobs add column if not exists run_token uuid;
alter table public.tier_update_jobs add column if not exists lease_expires_at timestamptz;
update public.tier_update_jobs
set lease_expires_at = coalesce(started_at, created_at) + interval '20 minutes'
where status = 'running' and lease_expires_at is null;

-- 실행마다 토큰을 바꿔 앞선 분석기 프로세스가 결과를 덮어쓰지 못하게 한다.
create or replace function public.claim_tier_analysis(p_job_id bigint)
returns table (image_url text, fa_text text, run_token uuid)
language sql
set search_path = public
as $$
  update public.tier_update_jobs j
  set status = 'running', started_at = now(), finished_at = null, error = null, result = null,
      run_token = gen_random_uuid(), lease_expires_at = now() + interval '20 minutes'
  where j.id = p_job_id and (j.status in ('queued', 'failed')
      or (j.status = 'running' and j.lease_expires_at <= now()))
  returning j.image_url, j.fa_text, j.run_token;
$$;
revoke all on function public.claim_tier_analysis(bigint) from public, anon, authenticated;

create or replace function public.finish_tier_analysis(
  p_job_id bigint, p_run_token uuid, p_result jsonb, p_error text
) returns boolean
language plpgsql
set search_path = public
as $$
begin
  update public.tier_update_jobs
  set status = case when p_error is null then 'done' else 'failed' end,
      result = p_result, error = p_error, finished_at = now(), lease_expires_at = null
  where id = p_job_id and status = 'running' and run_token = p_run_token and lease_expires_at > now();
  return found;
end;
$$;
revoke all on function public.finish_tier_analysis(bigint, uuid, jsonb, text) from public, anon, authenticated;

-- 관리자 조회 때 실행권이 만료된 작업을 회수한다.
create or replace function public.admin_recover_tier_jobs() returns integer
language plpgsql security definer
set search_path = public
as $$
declare recovered integer;
begin
  if not coalesce(public.is_admin(), false) then
    raise exception '관리자만 실행할 수 있습니다.';
  end if;
  update public.tier_update_jobs
  set status = 'failed', error = '분석 실행 시간이 만료되었습니다. 분석을 다시 요청해 주세요.',
      finished_at = now(), lease_expires_at = null
  where status = 'running' and lease_expires_at <= now();
  get diagnostics recovered = row_count;
  return recovered;
end;
$$;
revoke all on function public.admin_recover_tier_jobs() from public, anon;
grant execute on function public.admin_recover_tier_jobs() to authenticated;

alter table public.tier_update_jobs enable row level security;
drop policy if exists tier_update_jobs_admin_read on public.tier_update_jobs;
create policy tier_update_jobs_admin_read on public.tier_update_jobs
  for select to authenticated using ((select public.is_admin()));
revoke all on public.tier_update_jobs from anon;
grant select on public.tier_update_jobs to authenticated;

-- 학습 기억: 확인된 카드의 글씨·사진 지문. 분석기만 쓴다.
create table if not exists public.tier_memory_glyphs (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('tier', 'race')),
  value text not null,
  feat text not null,
  bg text,
  created_at timestamptz not null default now()
);
create table if not exists public.tier_memory_photos (
  id bigint generated by default as identity primary key,
  soop_id text,
  nickname text not null,
  hash text not null,
  tier text,
  race text,
  tier_feat text,
  race_feat text,
  -- 늘 틀리게 읽히는 닉네임도 같은 카드면 '변경'으로 띄우지 않게
  name_read text,
  name_feat text,
  updated_at timestamptz not null default now()
);
create index if not exists tier_memory_photos_soop_idx on public.tier_memory_photos (soop_id);
alter table public.tier_memory_glyphs enable row level security;
alter table public.tier_memory_photos enable row level security;
revoke all on public.tier_memory_glyphs, public.tier_memory_photos from anon, authenticated;
-- 1번의 '모든 시퀀스 사용 허용'이 이 표들까지 넓히지 않게(함수로만 쓴다)
revoke all on sequence public.tier_update_jobs_id_seq, public.tier_memory_glyphs_id_seq,
  public.tier_memory_photos_id_seq from anon, authenticated;

-- 작업을 만들고 tier-analysis.yml을 실행한다. 반환값은 작업 번호.
create or replace function public.admin_request_tier_analysis(p_image_url text, p_fa_text text default null)
returns bigint
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  token text;
  job_id bigint;
  req bigint;
begin
  if not coalesce(public.is_admin(), false) then
    raise exception '관리자만 실행할 수 있습니다.';
  end if;
  -- 다른 주소를 Actions가 내려받지 않게
  if p_image_url is null or p_image_url !~ '^https://image\.fmkorea\.com/' then
    raise exception '티어표 이미지 주소는 https://image.fmkorea.com/ 으로 시작해야 합니다.';
  end if;
  select decrypted_secret into token
  from vault.decrypted_secrets where name = 'github_actions_token' limit 1;
  if token is null or token = '' then
    raise exception 'GitHub 토큰(github_actions_token)이 Vault에 없습니다.';
  end if;

  insert into public.tier_update_jobs (image_url, fa_text)
  values (p_image_url, nullif(btrim(coalesce(p_fa_text, '')), ''))
  returning id into job_id;

  select net.http_post(
    url := 'https://api.github.com/repos/ststats/staruniv/actions/workflows/tier-analysis.yml/dispatches',
    body := jsonb_build_object('ref', 'main', 'inputs', jsonb_build_object('job_id', job_id::text)),
    headers := jsonb_build_object(
      'Authorization', 'Bearer ' || token,
      'Accept', 'application/vnd.github+json',
      'X-GitHub-Api-Version', '2022-11-28',
      'User-Agent', 'staruniv-supabase'
    )
  ) into req;
  update public.tier_update_jobs set dispatch_request = req where id = job_id;
  return job_id;
end;
$$;

revoke all on function public.admin_request_tier_analysis(text, text) from public, anon;
grant execute on function public.admin_request_tier_analysis(text, text) to authenticated;

-- 작업이 '대기'에 오래 머물 때 관리자 화면이 원인을 보여 준다.
create or replace function public.admin_tier_job_dispatch_status(p_job_id bigint)
returns table (status_code integer, error text)
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if not coalesce(public.is_admin(), false) then
    raise exception '관리자만 실행할 수 있습니다.';
  end if;
  return query
    select r.status_code, coalesce(r.error_msg, case when r.status_code >= 300 then left(r.content::text, 300) end)
    from public.tier_update_jobs j join net._http_response r on r.id = j.dispatch_request
    where j.id = p_job_id;
end;
$$;
revoke all on function public.admin_tier_job_dispatch_status(bigint) from public, anon;
grant execute on function public.admin_tier_job_dispatch_status(bigint) to authenticated;

-- 고른 변동을 tier_members에 한 번에 적용한다.
--   p_updates   [{id, affiliation?, tier?, race?, nickname?}]  바뀌는 칸만
--   p_inserts   [{nickname, tier, race, affiliation, soop_id?, elo_id?}]
--   p_confirmed [{ref:[구역,카드], id} 또는 {ref, insert:새 선수 순번(0부터)}]  학습용
--   p_date      승급일(보통 티어표 글 날짜)
create or replace function public.admin_apply_tier_update(
  p_job_id bigint, p_updates jsonb, p_inserts jsonb, p_confirmed jsonb, p_date date default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  ladder constant text[] := array['갓','킹','잭','조커','스페이드','0','1','2','3','4','5','6','7','8','베이비'];
  d text := to_char(coalesce(p_date, timezone('Asia/Seoul', now())::date), 'YYYY-MM-DD');
  -- 수정일 = 승급일: ststat이 이 날짜부터 방송통계 일별 기록의 티어·소속을 고친다.
  stamp text := d || ' ' || to_char(timezone('Asia/Seoul', now()), 'HH24:MI:SS');
  job_status text;
  u jsonb;
  r public.tier_members;
  new_aff text;
  new_tier text;
  hist text;
  col text;
  cur text;
  next_order integer;
  new_id bigint;
  ins_ids bigint[] := '{}';
  conf jsonb := '[]'::jsonb;
  pid bigint;
  n_upd integer := 0;
  log jsonb := '[]'::jsonb;   -- 관리자 화면의 '반영 내역'
  promoted text;
begin
  if not coalesce(public.is_admin(), false) then
    raise exception '관리자만 실행할 수 있습니다.';
  end if;
  select status into job_status from public.tier_update_jobs where id = p_job_id for update;
  if job_status is null then
    raise exception '작업 %이 없습니다.', p_job_id;
  end if;
  if job_status <> 'done' then
    raise exception '분석이 끝난 작업만 반영할 수 있습니다(지금: %).', job_status;
  end if;

  if exists (
    select 1 from jsonb_array_elements(coalesce(p_updates, '[]'::jsonb)) item
    group by (item->>'id')::bigint having count(*) > 1
  ) then
    raise exception '같은 선수의 변경안이 중복되어 있습니다.';
  end if;

  for u in select * from jsonb_array_elements(coalesce(p_updates, '[]'::jsonb)) loop
    select * into r from public.tier_members where id = (u->>'id')::bigint for update;
    if not found then
      raise exception '선수 번호 %이 없습니다.', u->>'id';
    end if;
    new_aff := coalesce(nullif(btrim(u->>'affiliation'), ''), r.affiliation);
    new_tier := coalesce(nullif(btrim(u->>'tier'), ''), r.tier);
    hist := r.history;
    promoted := null;
    if new_aff is distinct from r.affiliation and new_aff not in ('FA', '휴면')
       and btrim(regexp_replace(coalesce(hist, ''), '^.*,', '')) is distinct from new_aff then
      hist := case when coalesce(btrim(hist), '') = '' then new_aff else hist || ', ' || new_aff end;
    end if;
    -- 'N티어 승급' 칸 = 그 티어가 된 날. 강등으로 내려간 날도 그 티어 칸에 적는다(이미 있으면 쉼표로 잇는다).
    if new_tier is distinct from r.tier and new_tier ~ '^[0-8]$' then
      col := 'promoted_tier_' || new_tier;
      execute format('select %I from public.tier_members where id = $1', col) into cur using r.id;
      if array_position(ladder, new_tier) < coalesce(array_position(ladder, r.tier), 999) then
        promoted := new_tier;
      end if;
      if coalesce(cur, '') not like '%' || d || '%' then
        execute format('update public.tier_members set %I = $1 where id = $2', col)
          using case when coalesce(btrim(cur), '') = '' then d else cur || ', ' || d end, r.id;
      end if;
    end if;
    update public.tier_members set
      affiliation = new_aff,
      tier = new_tier,
      -- 빈 값('-' = 종족미정)으로도 바꾼다(normalize_race가 null로 적는다)
      race = case when u ? 'race' then nullif(btrim(u->>'race'), '') else race end,
      nickname = coalesce(nullif(btrim(u->>'nickname'), ''), nickname),
      history = hist,
      modified_at = stamp
    where id = r.id;
    n_upd := n_upd + 1;
    log := log || jsonb_build_object('id', r.id, 'nickname', r.nickname,
      'before', jsonb_build_object('nickname', r.nickname, 'affiliation', r.affiliation, 'tier', r.tier, 'race', r.race),
      'after', jsonb_build_object('nickname', coalesce(nullif(btrim(u->>'nickname'), ''), r.nickname),
                                  'affiliation', new_aff, 'tier', new_tier,
                                  'race', case when u ? 'race' then nullif(btrim(u->>'race'), '') else r.race end),
      'promoted', promoted);
  end loop;

  select coalesce(max(source_order), 0) into next_order from public.tier_members;
  for u in select * from jsonb_array_elements(coalesce(p_inserts, '[]'::jsonb)) loop
    if coalesce(btrim(u->>'nickname'), '') = '' then
      raise exception '새 선수 닉네임이 비었습니다.';
    end if;
    next_order := next_order + 1;
    insert into public.tier_members (source_order, nickname, soop_id, elo_id, tier, race, affiliation, history,
                                     modified_at, tier_table_registered, gender)
    values (next_order, btrim(u->>'nickname'), nullif(btrim(u->>'soop_id'), ''),
            case when coalesce(u->>'elo_id', '') ~ '^[0-9]+$' then (u->>'elo_id')::int end,
            nullif(u->>'tier', ''),
            nullif(u->>'race', ''), nullif(u->>'affiliation', ''),
            case when u->>'affiliation' in ('FA', '휴면') then null else nullif(u->>'affiliation', '') end,
            stamp, d, case when u->>'gender' in ('남자', '여자') then u->>'gender' end)
    returning id into new_id;
    ins_ids := ins_ids || new_id;
    log := log || jsonb_build_object('id', new_id, 'nickname', btrim(u->>'nickname'), 'new', true,
      'after', jsonb_build_object('nickname', btrim(u->>'nickname'), 'affiliation', nullif(u->>'affiliation', ''),
                                  'tier', nullif(u->>'tier', ''), 'race', nullif(u->>'race', '')));
  end loop;

  -- 확인된 카드는 반영 뒤 값으로 적는다(다음 분석이 이 값으로 기억한다)
  for u in select * from jsonb_array_elements(coalesce(p_confirmed, '[]'::jsonb)) loop
    pid := case when u ? 'insert' then ins_ids[(u->>'insert')::int + 1] else (u->>'id')::bigint end;
    select * into r from public.tier_members where id = pid;
    if found then
      if exists (select 1 from jsonb_array_elements(conf) item where (item->>'id')::bigint = pid) then
        raise exception '같은 선수를 여러 카드에서 학습할 수 없습니다.';
      end if;
      conf := conf || jsonb_build_object('ref', u->'ref', 'id', r.id, 'soop_id', r.soop_id,
                                         'nickname', r.nickname, 'tier', r.tier, 'race', r.race);
    end if;
  end loop;

  update public.tier_update_jobs set status = 'applied', applied_at = now(),
    applied = jsonb_build_object('date', d, 'updates', coalesce(p_updates, '[]'::jsonb),
                                 'inserts', coalesce(p_inserts, '[]'::jsonb), 'confirmed', conf, 'log', log)
  where id = p_job_id;
  perform public.admin_write_audit('tier_table_update', 'tier_members', p_job_id::text,
    jsonb_build_object('updated', n_upd, 'inserted', coalesce(array_length(ins_ids, 1), 0)));
  return jsonb_build_object('updated', n_upd, 'inserted', coalesce(array_length(ins_ids, 1), 0));
end;
$$;
revoke all on function public.admin_apply_tier_update(bigint, jsonb, jsonb, jsonb, date) from public, anon;
grant execute on function public.admin_apply_tier_update(bigint, jsonb, jsonb, jsonb, date) to authenticated;


-- ############################################################################
-- 6. 대학 로고(스타유니브·시너지 공용)
-- ############################################################################

-- 로고 파일은 Storage(staruniv-media/logos/), 대표 색은 시너지 카드 윗줄에 쓴다.
create table if not exists public.university_logos (
  name text primary key,
  path text not null,
  color text check (color is null or color ~ '^#[0-9a-f]{6}$'),
  updated_at timestamptz not null default now()
);
alter table public.university_logos enable row level security;
-- 공개 읽기는 시너지 표가 필요해서 ststat.sql 14번(api_university_logos)에 있다.
drop policy if exists university_logos_admin_read on public.university_logos;
create policy university_logos_admin_read on public.university_logos for select to authenticated using (true);
drop policy if exists university_logos_admin_write on public.university_logos;
create policy university_logos_admin_write on public.university_logos for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
revoke all on public.university_logos from anon;
grant select, insert, update, delete on public.university_logos to authenticated;

-- ############################################################################
-- 7. 한 선수의 다른 ELO 계정(종족 변경 등)
-- ############################################################################

-- EloBoard는 종족마다 ELO ID가 따로다. tier_members.elo_id는 메인 계정이고 다른 계정은 여기에 연결만 한다
-- (신규 인원에 다시 뜨지 않게. 전적·방송통계는 계정별 그대로).
create table if not exists public.tier_member_elo_links (
  elo_id integer primary key,
  tier_member_id bigint not null references public.tier_members(id) on delete cascade,
  elo_name text,
  race text,
  created_at timestamptz not null default now()
);
create index if not exists tier_member_elo_links_member_idx on public.tier_member_elo_links (tier_member_id);
alter table public.tier_member_elo_links enable row level security;
drop policy if exists tier_member_elo_links_admin on public.tier_member_elo_links;
create policy tier_member_elo_links_admin on public.tier_member_elo_links for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
revoke all on public.tier_member_elo_links from anon, authenticated;
grant select, insert, update, delete on public.tier_member_elo_links to authenticated;

-- 같은 ELO ID가 메인·연결 계정에 동시에 있으면 안 된다. 같은 SOOP ID가 두 선수에 있으면 방송통계 일일 저장이
-- 통째로 멈춘다(SOOP ID가 키). 그 칸을 바꿀 때만 검사해 이 파일을 다시 실행해도 기존 행 때문에 실패하지 않는다.
create or replace function public.tier_members_guard_ids()
returns trigger
language plpgsql
set search_path = public
as $$
declare other text;
begin
  if new.soop_id is not null and btrim(new.soop_id) <> ''
     and (tg_op = 'INSERT' or lower(btrim(new.soop_id)) is distinct from lower(btrim(coalesce(old.soop_id, '')))) then
    select nickname into other from public.tier_members
    where lower(btrim(soop_id)) = lower(btrim(new.soop_id)) and id <> coalesce(new.id, -1) limit 1;
    if found then
      raise exception 'SOOP ID %는 이미 % 선수가 쓰고 있습니다(같은 사람이면 새 선수를 만들지 말고 기존 선수를 고치세요)', new.soop_id, other;
    end if;
  end if;
  if new.elo_id is not null and (tg_op = 'INSERT' or new.elo_id is distinct from old.elo_id) then
    select m.nickname into other from public.tier_member_elo_links l join public.tier_members m on m.id = l.tier_member_id
    where l.elo_id = new.elo_id and l.tier_member_id <> coalesce(new.id, -1) limit 1;
    if found then
      raise exception 'ELO ID %는 % 선수의 연결 계정입니다', new.elo_id, other;
    end if;
    delete from public.tier_member_elo_links where elo_id = new.elo_id and tier_member_id = new.id;
  end if;
  return new;
end;
$$;
drop trigger if exists tier_members_guard_ids on public.tier_members;
create trigger tier_members_guard_ids before insert or update of soop_id, elo_id on public.tier_members
  for each row execute function public.tier_members_guard_ids();

create or replace function public.tier_member_elo_links_guard()
returns trigger
language plpgsql
set search_path = public
as $$
declare other text;
begin
  select nickname into other from public.tier_members where elo_id = new.elo_id limit 1;
  if found then
    raise exception 'ELO ID %는 이미 % 선수의 메인 계정입니다', new.elo_id, other;
  end if;
  return new;
end;
$$;
drop trigger if exists tier_member_elo_links_guard on public.tier_member_elo_links;
create trigger tier_member_elo_links_guard before insert or update of elo_id on public.tier_member_elo_links
  for each row execute function public.tier_member_elo_links_guard();

-- 연결 계정을 메인으로 올리고 옛 메인은 연결로 내린다(한 번에 해야 옛 계정이 신규 인원에 다시 뜨지 않는다).
-- 수정일은 오늘: 그날부터 방송통계가 새 계정으로 센다. 종족 칸은 바꾸지 않는다.
create or replace function public.admin_set_main_elo(p_member_id bigint, p_elo_id integer)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare m public.tier_members%rowtype;
begin
  if not public.is_admin() then raise exception 'admin only'; end if;
  select * into m from public.tier_members where id = p_member_id for update;
  if not found then raise exception '선수 번호 %이 없습니다', p_member_id; end if;
  if not exists (select 1 from public.tier_member_elo_links where elo_id = p_elo_id and tier_member_id = p_member_id) then
    raise exception 'ELO ID %는 이 선수의 연결 계정이 아닙니다', p_elo_id;
  end if;
  -- 새 메인은 트리거가 연결 목록에서 뺀다
  update public.tier_members
  set elo_id = p_elo_id,
      modified_at = to_char(timezone('Asia/Seoul', now()), 'YYYY-MM-DD HH24:MI:SS')
  where id = p_member_id;
  if m.elo_id is not null then
    insert into public.tier_member_elo_links (elo_id, tier_member_id, elo_name, race)
    select m.elo_id, p_member_id, p.name, p.race
    from (select 1) one left join public.elo_players p on p.elo_id = m.elo_id
    on conflict (elo_id) do nothing;
  end if;
  perform public.admin_write_audit('set_main_elo', 'tier_members', p_member_id::text,
    jsonb_build_object('from', m.elo_id, 'to', p_elo_id, 'nickname', m.nickname));
end;
$$;
revoke all on function public.admin_set_main_elo(bigint, integer) from public, anon;
grant execute on function public.admin_set_main_elo(bigint, integer) to authenticated;

-- ############################################################################
-- 8. 멤버 ↔ 티어표 선수 연동
-- ############################################################################

-- 멤버 줄 하나 = 입단 기록 하나. 사람 정보(SOOP ID·생년월일·성별·지금 티어)는 tier_members가 원본이고
-- 이어진 멤버 줄의 같은 칸은 DB가 맞춘다(읽는 쪽은 members 칸만 보면 된다).
alter table public.members
  add column if not exists tier_member_id bigint references public.tier_members(id) on delete set null;
create index if not exists members_tier_member_idx on public.members (tier_member_id);

create or replace function public.members_fill_from_tier()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  t public.tier_members%rowtype;
  linking boolean;
begin
  if coalesce(btrim(new.soop_id), '') <> ''
     and (new.tier_member_id is null
          or (tg_op = 'UPDATE' and lower(btrim(new.soop_id)) is distinct from lower(btrim(coalesce(old.soop_id, ''))))) then
    select id into new.tier_member_id from public.tier_members
    where lower(btrim(soop_id)) = lower(btrim(new.soop_id)) order by id limit 1;
  end if;
  if new.tier_member_id is null then return new; end if;
  select * into t from public.tier_members where id = new.tier_member_id;
  if not found then return new; end if;
  linking := tg_op = 'INSERT' or old.tier_member_id is distinct from new.tier_member_id;
  new.soop_id := coalesce(nullif(btrim(t.soop_id), ''), new.soop_id);
  new.tier := coalesce(nullif(btrim(t.tier), ''), new.tier);
  -- 생년월일·성별은 티어표 값을 따른다(지우면 여기서도 지워진다). 티어표가 비어 있을 때만 멤버 값을 남기고
  -- 아래 트리거가 티어표로 올린다.
  if linking or (tg_op = 'UPDATE' and new.birth_date is distinct from old.birth_date) then
    new.birth_date := coalesce(t.birth_date, new.birth_date);
  else
    new.birth_date := t.birth_date;
  end if;
  if linking or (tg_op = 'UPDATE' and new.gender is distinct from old.gender) then
    new.gender := coalesce(nullif(btrim(t.gender), ''), new.gender);
  else
    new.gender := nullif(btrim(t.gender), '');
  end if;
  return new;
end;
$$;
drop trigger if exists members_fill_from_tier on public.members;
create trigger members_fill_from_tier before insert or update on public.members
  for each row execute function public.members_fill_from_tier();

-- 멤버 쪽에만 남은 생년월일·성별을 티어표로 올린다(원본을 한 곳으로).
create or replace function public.members_push_to_tier()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.tier_member_id is null then return null; end if;
  update public.tier_members
     set birth_date = coalesce(birth_date, new.birth_date),
         gender = coalesce(nullif(btrim(gender), ''), nullif(btrim(new.gender), ''))
   where id = new.tier_member_id
     and ((birth_date is null and new.birth_date is not null)
          or (coalesce(btrim(gender), '') = '' and coalesce(btrim(new.gender), '') <> ''));
  return null;
end;
$$;
drop trigger if exists members_push_to_tier on public.members;
create trigger members_push_to_tier after insert or update of birth_date, gender, tier_member_id on public.members
  for each row execute function public.members_push_to_tier();

create or replace function public.tier_members_sync_members()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  update public.members set tier_member_id = tier_member_id   -- 위 트리거가 새 값으로 채운다
  where tier_member_id = new.id;
  return null;
end;
$$;
drop trigger if exists tier_members_sync_members on public.tier_members;
create trigger tier_members_sync_members after update of soop_id, birth_date, gender, tier on public.tier_members
  for each row execute function public.tier_members_sync_members();


-- ############################################################################
-- 9. 성별 표기 통일('남자' / '여자')
-- ############################################################################
-- 공개 화면·시너지가 '남자'/'여자'로 비교한다. 모르는 값은 지우지 않고 그대로 둔다.
create or replace function public.normalize_gender(p text)
returns text
language sql
immutable
as $$
  select case
    when p is null or btrim(p) = '' then null
    when btrim(p) in ('남', '남성', '남자') or upper(btrim(p)) in ('M', 'MALE') then '남자'
    when btrim(p) in ('여', '여성', '여자') or upper(btrim(p)) in ('F', 'FEMALE') then '여자'
    else btrim(p)
  end
$$;

create or replace function public.normalize_gender_column()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.gender := public.normalize_gender(new.gender);
  return new;
end;
$$;

-- before 트리거는 이름 순서로 돌아 members_fill_from_tier 다음에 맞춘다
drop trigger if exists tier_members_normalize_gender on public.tier_members;
create trigger tier_members_normalize_gender before insert or update of gender on public.tier_members
  for each row execute function public.normalize_gender_column();
drop trigger if exists members_normalize_gender on public.members;
create trigger members_normalize_gender before insert or update on public.members
  for each row execute function public.normalize_gender_column();


-- ############################################################################
-- 10. 종족 표기 통일('테란' / '저그' / '프로토스')
-- ############################################################################
-- EloBoard는 T/Z/P, 티어표·멤버는 '테란'처럼 적어서 섞이면 같은 종족끼리 묶이지 않는다.
-- 모르는 값은 앞뒤 공백만 지우고 그대로 둔다(빈 값은 null).
create or replace function public.normalize_race(v text)
returns text
language sql
immutable
set search_path = public
as $$
  select case
    when nullif(btrim(v), '') is null then null
    when upper(btrim(v)) in ('T', 'TERRAN', '테란', '테') then '테란'
    when upper(btrim(v)) in ('Z', 'ZERG', '저그', '저') then '저그'
    when upper(btrim(v)) in ('P', 'PROTOSS', '프로토스', '토스', '프') then '프로토스'
    when upper(btrim(v)) in ('R', 'RANDOM', '랜덤') then '랜덤'
    else btrim(v)
  end
$$;

create or replace function public.normalize_race_columns()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if tg_table_name = 'rounds' then
    new.our_race := public.normalize_race(new.our_race);
    new.opponent_race := public.normalize_race(new.opponent_race);
  else
    new.race := public.normalize_race(new.race);
  end if;
  return new;
end;
$$;

drop trigger if exists tier_members_normalize_race on public.tier_members;
create trigger tier_members_normalize_race before insert or update of race on public.tier_members
  for each row execute function public.normalize_race_columns();
drop trigger if exists members_normalize_race on public.members;
create trigger members_normalize_race before insert or update of race on public.members
  for each row execute function public.normalize_race_columns();
drop trigger if exists rounds_normalize_race on public.rounds;
create trigger rounds_normalize_race before insert or update of our_race, opponent_race on public.rounds
  for each row execute function public.normalize_race_columns();
drop trigger if exists tier_member_elo_links_normalize_race on public.tier_member_elo_links;
create trigger tier_member_elo_links_normalize_race before insert or update of race on public.tier_member_elo_links
  for each row execute function public.normalize_race_columns();
-- ststat.sql의 upsert_elo_batch도 같은 함수로 맞춘 값을 비교한다.
drop trigger if exists elo_players_normalize_race on public.elo_players;
create trigger elo_players_normalize_race before insert or update of race on public.elo_players
  for each row execute function public.normalize_race_columns();


-- ############################################################################
-- 11. 티어 표기 통일(갓 킹 잭 조커 스페이드 0~8 베이비, 미분류는 체크)
-- ############################################################################
-- core.js SITE_ORDER.tiers와 같은 값으로 저장한다('5티어'·god·스페 같은 표기는 묶이지 않아서).
-- 모르는 값은 앞뒤 공백만 지우고 그대로 둔다.
create or replace function public.normalize_tier(v text)
returns text
language sql
immutable
set search_path = public
as $$
  select case
    when t is null then null
    when upper(t) in ('GOD', '갓') then '갓'
    when upper(t) in ('KING', '킹') then '킹'
    when upper(t) in ('JACK', '잭') then '잭'
    when upper(t) in ('JOKER', '조커', '조커요') then '조커'
    when upper(t) in ('SPADE', '스페이드', '스페') then '스페이드'
    when upper(t) in ('BABY', '베이비') then '베이비'
    when upper(t) in ('CHECK', '체크', '체', '미분류') then '체크'
    else t
  end
  from (select nullif(btrim(regexp_replace(btrim(coalesce(v, '')), '\s*티어$', '')), '') as t) x
$$;

create or replace function public.normalize_tier_columns()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if tg_table_name = 'rounds' then
    new.our_tier := public.normalize_tier(new.our_tier);
    new.opponent_tier := public.normalize_tier(new.opponent_tier);
  elsif tg_table_name = 'members' then
    new.tier := public.normalize_tier(new.tier);
    new.join_tier := public.normalize_tier(new.join_tier);
  else
    new.tier := public.normalize_tier(new.tier);
  end if;
  return new;
end;
$$;

drop trigger if exists tier_members_normalize_tier on public.tier_members;
create trigger tier_members_normalize_tier before insert or update of tier on public.tier_members
  for each row execute function public.normalize_tier_columns();
drop trigger if exists members_normalize_tier on public.members;
create trigger members_normalize_tier before insert or update of tier, join_tier on public.members
  for each row execute function public.normalize_tier_columns();
drop trigger if exists rounds_normalize_tier on public.rounds;
create trigger rounds_normalize_tier before insert or update of our_tier, opponent_tier on public.rounds
  for each row execute function public.normalize_tier_columns();

-- 관리자 삭제는 감사 기록과 한 트랜잭션이라 기록이 실패하면 삭제도 롤백된다. 로그인 없는 수집 작업은 건너뛴다.
create or replace function public.audit_admin_delete()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row jsonb := to_jsonb(old);
  v_key text;
begin
  if auth.uid() is null then return old; end if;
  if not public.is_admin() then raise exception 'admin only'; end if;
  v_key := v_row ->> tg_argv[0];
  if tg_nargs = 2 then v_key := v_key || ':' || (v_row ->> tg_argv[1]); end if;
  perform public.admin_write_audit('delete', tg_table_name, v_key, v_row);
  return old;
end;
$$;
revoke all on function public.audit_admin_delete() from public, anon, authenticated;

do $$
declare v_table text; v_key text;
begin
  for v_table, v_key in
    select * from (values
      ('members','id'), ('teams','id'), ('history_entries','id'),
      ('calendar_events','id'), ('holidays','day'), ('matches','match_no'),
      ('university_logos','name'), ('tier_members','id'),
      ('tier_member_elo_links','elo_id'), ('tier_member_candidates','id'),
      ('video_picks','id'), ('external_tools','id')
    ) as targets(table_name, key_column)
  loop
    -- 후보 표는 이 파일 다음에 실행하는 ststat.sql이 만든다
    if v_table = 'tier_member_candidates' and to_regclass('public.tier_member_candidates') is null then
      continue;
    end if;
    execute format('drop trigger if exists admin_delete_audit on public.%I', v_table);
    execute format('create trigger admin_delete_audit after delete on public.%I for each row execute function public.audit_admin_delete(%L)', v_table, v_key);
  end loop;
end;
$$;
drop trigger if exists admin_delete_audit on public.calendar_off_air;
create trigger admin_delete_audit after delete on public.calendar_off_air
  for each row execute function public.audit_admin_delete('off_date', 'soop_id');
