-- 티어표 갱신(반자동): 펨코 티어표 이미지 주소 + FA 명단 글을 넣으면 GitHub Actions가
-- scripts/tier_table.py로 읽어 DB와 비교하고, 결과를 tier_update_jobs.result에 넣는다.
-- 관리자는 결과를 보고 반영할 것만 골라 반영한다(반영 함수는 이 파일 아래쪽).
--
-- 준비: '달력 사진 갱신'과 같은 GitHub 토큰(Vault의 github_actions_token)을 쓴다. 토큰 권한은
--       Actions = Read and write 그대로면 된다. 이 파일 전체를 SQL 편집기에서 한 번 실행한다.
-- 여러 번 실행해도 된다(있는 표·함수는 그대로 두거나 바꿔 쓴다).

create extension if not exists pg_net with schema extensions;

-- 분석 요청과 결과
create table if not exists public.tier_update_jobs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid(),
  image_url text not null,
  fa_text text,
  status text not null default 'queued'
    check (status in ('queued', 'running', 'done', 'failed', 'applied')),
  result jsonb,
  error text,
  started_at timestamptz,
  finished_at timestamptz,
  applied_at timestamptz
);
alter table public.tier_update_jobs enable row level security;
drop policy if exists tier_update_jobs_admin_read on public.tier_update_jobs;
create policy tier_update_jobs_admin_read on public.tier_update_jobs
  for select to authenticated using (public.is_admin());
revoke all on public.tier_update_jobs from anon;
grant select on public.tier_update_jobs to authenticated;

-- 기억(학습): 확인된 카드의 티어·종족 글씨와 선수 사진 지문. 분석기만 쓴다(브라우저에서는 못 읽음).
create table if not exists public.tier_memory_glyphs (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('tier', 'race')),
  value text not null,
  feat text not null,
  bg text,
  created_at timestamptz not null default now()
);
create table if not exists public.tier_memory_photos (
  id bigint generated by default as identity primary key,
  soop_id text,
  nickname text not null,
  hash text not null,
  tier text,
  race text,
  tier_feat text,
  race_feat text,
  updated_at timestamptz not null default now()
);
create index if not exists tier_memory_photos_soop_idx on public.tier_memory_photos (soop_id);
alter table public.tier_memory_glyphs enable row level security;
alter table public.tier_memory_photos enable row level security;
revoke all on public.tier_memory_glyphs, public.tier_memory_photos from anon, authenticated;

-- 분석 요청: 작업을 만들고 GitHub Actions(tier-analysis.yml)를 실행한다. 반환값: 작업 번호.
create or replace function public.admin_request_tier_analysis(p_image_url text, p_fa_text text default null)
returns bigint
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  token text;
  job_id bigint;
begin
  if not coalesce(public.is_admin(), false) then
    raise exception '관리자만 실행할 수 있습니다.';
  end if;
  -- 펨코 이미지 서버 주소만 받는다(다른 주소를 Actions가 내려받지 않게)
  if p_image_url is null or p_image_url !~ '^https://image\.fmkorea\.com/' then
    raise exception '티어표 이미지 주소는 https://image.fmkorea.com/ 으로 시작해야 합니다.';
  end if;
  select decrypted_secret into token
  from vault.decrypted_secrets where name = 'github_actions_token' limit 1;
  if token is null or token = '' then
    raise exception 'GitHub 토큰(github_actions_token)이 Vault에 없습니다.';
  end if;

  insert into public.tier_update_jobs (image_url, fa_text)
  values (p_image_url, nullif(btrim(coalesce(p_fa_text, '')), ''))
  returning id into job_id;

  perform net.http_post(
    url := 'https://api.github.com/repos/ststats/staruniv/actions/workflows/tier-analysis.yml/dispatches',
    body := jsonb_build_object('ref', 'main', 'inputs', jsonb_build_object('job_id', job_id::text)),
    headers := jsonb_build_object(
      'Authorization', 'Bearer ' || token,
      'Accept', 'application/vnd.github+json',
      'X-GitHub-Api-Version', '2022-11-28',
      'User-Agent', 'staruniv-supabase'
    )
  );
  return job_id;
end;
$$;

revoke all on function public.admin_request_tier_analysis(text, text) from public, anon;
grant execute on function public.admin_request_tier_analysis(text, text) to authenticated;
