-- StarUniv correction: standalone video tab + tools/external links


-- ============================================================================
-- 별도 영상 탭 (팬튜브 + 보자)
-- ============================================================================
create table if not exists public.video_channels (
  channel_url text primary key, channel_id text, title text, display_name text, thumb text, uploads text,
  source_order integer not null unique, active boolean not null default true, updated_at timestamptz not null default now()
);
create table if not exists public.videos (
  id text primary key, channel_url text, title text not null, published timestamptz, thumb text,
  views bigint not null default 0, short boolean not null default false, hidden boolean not null default false,
  updated_at timestamptz not null default now()
);
create index if not exists videos_published_idx on public.videos (published desc);
create index if not exists videos_channel_idx on public.videos (channel_url);
create table if not exists public.video_picks (
  id text primary key, kind text not null default 'youtube' check (kind in ('youtube','soop')), title text not null, note text,
  group_name text, group_en text, added_at date, author text, thumb text, short boolean not null default false,
  hidden boolean not null default false, source_order integer not null unique, updated_at timestamptz not null default now()
);
alter table public.video_channels enable row level security;
alter table public.videos enable row level security;
alter table public.video_picks enable row level security;
insert into public.video_channels(channel_url,channel_id,title,display_name,thumb,uploads,source_order,active) values ('https://www.youtube.com/@캄몬장난감만들기','UCcEKr3U4RuuC97lVwajKs7A','캄몬 장난감','캄몬 장난감','https://yt3.ggpht.com/7eEqK-6H5ulsoblx-qVYLC-A3myDxZ8lWa26N9U9Y4KN-h5q-SsVRPA9Clw3y47mXwFyMnNgDZw=s800-c-k-c0x00ffffff-no-rj','UUcEKr3U4RuuC97lVwajKs7A',1,true) on conflict (channel_url) do nothing;
insert into public.video_channels(channel_url,channel_id,title,display_name,thumb,uploads,source_order,active) values ('https://www.youtube.com/@MonstarzFantube','UCScT2Alywz14zjs9vsyiEzg','캄몬팬튜브 Monstarz Fantube','캄몬팬튜브','https://yt3.ggpht.com/-ehDJgbLso5Y1uSIj2Gy1zNXpMvxnL8AStC_OlbHyEtEt4Wki51gfeYPNrVTffFxBlTqjWtoGA=s800-c-k-c0x00ffffff-no-rj','UUScT2Alywz14zjs9vsyiEzg',2,true) on conflict (channel_url) do nothing;
insert into public.video_channels(channel_url,channel_id,title,display_name,thumb,uploads,source_order,active) values ('https://www.youtube.com/@캄냥이','UCA2fElM1yTQdMJr_b_Sj8Bg','캄냥이','캄냥이','https://yt3.ggpht.com/PKTe2ArHkcUufDHyJ4STXLhtRs5MhMzgA_HbPOdc5s_yWO4nPYcdczTeqI_Ilf-nUmmECEUCTA=s800-c-k-c0x00ffffff-no-rj','UUA2fElM1yTQdMJr_b_Sj8Bg',3,true) on conflict (channel_url) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('ApPcCLJ868o','https://www.youtube.com/@캄몬장난감만들기','캄몬 동료 파는 김윤암 (덕몽)','2026-09-18T15:03:38+00'::timestamptz,'https://i.ytimg.com/vi/ApPcCLJ868o/mqdefault.jpg',17431,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('W0GJrn7goXA','https://www.youtube.com/@MonstarzFantube','월간 캄몬(26년8월)','2026-09-03T17:29:33+00'::timestamptz,'https://i.ytimg.com/vi/W0GJrn7goXA/mqdefault.jpg',4974,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('ll50uTz1Vbs','https://www.youtube.com/@캄몬장난감만들기','캄몬 음지덕몽의 정석','2026-09-01T12:35:01+00'::timestamptz,'https://i.ytimg.com/vi/ll50uTz1Vbs/mqdefault.jpg',16543,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('MkHCZPh2Tcc','https://www.youtube.com/@캄몬장난감만들기','캄몬 3점슛을 위하여 (덕몽)','2026-08-22T16:56:47+00'::timestamptz,'https://i.ytimg.com/vi/MkHCZPh2Tcc/mqdefault.jpg',12488,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('7IOngFbjUYk','https://www.youtube.com/@캄몬장난감만들기','캄몬 때론 날카로운 검 (주하랑)','2026-08-12T10:29:04+00'::timestamptz,'https://i.ytimg.com/vi/7IOngFbjUYk/mqdefault.jpg',9940,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('OneX3eq4SxA','https://www.youtube.com/@캄몬장난감만들기','캄몬 이가 없다면 잇몸으로 (남덕선)','2026-08-09T12:27:50+00'::timestamptz,'https://i.ytimg.com/vi/OneX3eq4SxA/mqdefault.jpg',8548,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('ShSTFAHyvsA','https://www.youtube.com/@MonstarzFantube','암주양 마지막 이야기','2026-08-08T04:44:42+00'::timestamptz,'https://i.ytimg.com/vi/ShSTFAHyvsA/mqdefault.jpg',3321,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('IepgesS-3FY','https://www.youtube.com/@캄몬장난감만들기','캄몬 문제아 특집 3회차','2026-08-07T10:31:34+00'::timestamptz,'https://i.ytimg.com/vi/IepgesS-3FY/mqdefault.jpg',12255,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('QqJwyGMl7qs','https://www.youtube.com/@캄몬장난감만들기','캄몬 문제아 특집 2회차-완-','2026-08-04T09:01:37+00'::timestamptz,'https://i.ytimg.com/vi/QqJwyGMl7qs/mqdefault.jpg',10960,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('SrpmBzJ5an0','https://www.youtube.com/@캄몬장난감만들기','캄몬 문제아 특집 2회차(1)','2026-08-01T08:14:56+00'::timestamptz,'https://i.ytimg.com/vi/SrpmBzJ5an0/mqdefault.jpg',16534,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('YLli6Ox2zVg','https://www.youtube.com/@캄몬장난감만들기','캄몬 소싸움하러 갑니다 (덕몽)','2026-07-29T13:29:37+00'::timestamptz,'https://i.ytimg.com/vi/YLli6Ox2zVg/mqdefault.jpg',12109,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('MgXGjte0dNY','https://www.youtube.com/@MonstarzFantube','먼진의 나홀로가챠 여행','2026-07-28T18:08:28+00'::timestamptz,'https://i.ytimg.com/vi/MgXGjte0dNY/mqdefault.jpg',1641,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('jbIkovcG9E8','https://www.youtube.com/@캄몬장난감만들기','캄몬 투표 독려 영상(2화)','2026-07-28T11:32:59+00'::timestamptz,'https://i.ytimg.com/vi/jbIkovcG9E8/mqdefault.jpg',13441,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('pMaa4ghUUQA','https://www.youtube.com/@캄몬장난감만들기','캄몬 투표 독려 영상(27.~30.)','2026-07-26T16:20:36+00'::timestamptz,'https://i.ytimg.com/vi/pMaa4ghUUQA/mqdefault.jpg',6544,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('bj2I_q46nH8','https://www.youtube.com/@캄몬장난감만들기','캄몬 김윤환 생일 축하','2026-07-25T05:51:18+00'::timestamptz,'https://i.ytimg.com/vi/bj2I_q46nH8/mqdefault.jpg',5885,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('rqzKXyc_yNs','https://www.youtube.com/@MonstarzFantube','월간 캄몬(26년5월)','2026-07-24T09:10:32+00'::timestamptz,'https://i.ytimg.com/vi/rqzKXyc_yNs/mqdefault.jpg',3977,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('f68fklhrKqY','https://www.youtube.com/@캄몬장난감만들기','츠캄몬스타즈 민심 방어전(씨나인 트레일러)','2026-07-24T07:42:40+00'::timestamptz,'https://i.ytimg.com/vi/f68fklhrKqY/mqdefault.jpg',4810,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('Ur3SidfH5gM','https://www.youtube.com/@캄몬장난감만들기','츠캄몬스타즈 임조이','2026-07-24T07:42:38+00'::timestamptz,'https://i.ytimg.com/vi/Ur3SidfH5gM/mqdefault.jpg',9033,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('o_ER_xZmJKI','https://www.youtube.com/@캄몬장난감만들기','츠캄몬스타즈 MB대전 트레일러','2026-07-24T07:42:36+00'::timestamptz,'https://i.ytimg.com/vi/o_ER_xZmJKI/mqdefault.jpg',4376,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('8URYGATqa54','https://www.youtube.com/@캄몬장난감만들기','츠캄 MB대전 하이라이트','2026-07-24T07:42:34+00'::timestamptz,'https://i.ytimg.com/vi/8URYGATqa54/mqdefault.jpg',4458,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('z-e4TxTICDw','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 YB전 트레일러','2026-07-24T07:42:31+00'::timestamptz,'https://i.ytimg.com/vi/z-e4TxTICDw/mqdefault.jpg',3201,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('VU8plAi3snE','https://www.youtube.com/@캄몬장난감만들기','츠캄 씨나인 JPL 트레일러','2026-07-24T07:42:29+00'::timestamptz,'https://i.ytimg.com/vi/VU8plAi3snE/mqdefault.jpg',589,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('roY8FS8f-uE','https://www.youtube.com/@캄몬장난감만들기','츠캄몬스타즈 JPL 반격의 서막','2026-07-24T07:42:26+00'::timestamptz,'https://i.ytimg.com/vi/roY8FS8f-uE/mqdefault.jpg',4871,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('QJ0DwKlVlJI','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 JPL 흑카전','2026-07-24T07:42:24+00'::timestamptz,'https://i.ytimg.com/vi/QJ0DwKlVlJI/mqdefault.jpg',4131,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('l4ZVe2bASyw','https://www.youtube.com/@캄몬장난감만들기','우리는 전프로','2026-07-24T07:42:21+00'::timestamptz,'https://i.ytimg.com/vi/l4ZVe2bASyw/mqdefault.jpg',6936,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('xFlSzZ6mnpM','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 JPL 이노대전','2026-07-24T07:42:18+00'::timestamptz,'https://i.ytimg.com/vi/xFlSzZ6mnpM/mqdefault.jpg',4069,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('G-_aVuplUbw','https://www.youtube.com/@캄몬장난감만들기','츠캄몬스타즈 JPL 케이대전','2026-07-24T07:42:15+00'::timestamptz,'https://i.ytimg.com/vi/G-_aVuplUbw/mqdefault.jpg',5453,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('qFZpDiXc8Hs','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 엔딩 모음(~ing)','2026-07-24T07:42:13+00'::timestamptz,'https://i.ytimg.com/vi/qFZpDiXc8Hs/mqdefault.jpg',5585,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('XBO4sSjWRXk','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 JPLVS 정선대','2026-07-24T07:42:11+00'::timestamptz,'https://i.ytimg.com/vi/XBO4sSjWRXk/mqdefault.jpg',5723,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('eWseMdD8cVs','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 JPLVS 장독대','2026-07-24T07:42:09+00'::timestamptz,'https://i.ytimg.com/vi/eWseMdD8cVs/mqdefault.jpg',4661,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('FLvswNDr3jM','https://www.youtube.com/@캄몬장난감만들기','JPL 시즌2 막내현진','2026-07-24T07:41:54+00'::timestamptz,'https://i.ytimg.com/vi/FLvswNDr3jM/mqdefault.jpg',5078,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('JmdKQTr37WQ','https://www.youtube.com/@캄몬장난감만들기','JPL 시즌2 졈니','2026-07-24T07:41:50+00'::timestamptz,'https://i.ytimg.com/vi/JmdKQTr37WQ/mqdefault.jpg',6834,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('pDsFjx8AD3o','https://www.youtube.com/@캄몬장난감만들기','JPL 시즌2 츠캄 종료','2026-07-24T07:41:45+00'::timestamptz,'https://i.ytimg.com/vi/pDsFjx8AD3o/mqdefault.jpg',1850,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('U8Cae1HGD9A','https://www.youtube.com/@캄몬장난감만들기','츠캄몬스타즈 경기종료 세나 승','2026-07-24T07:41:30+00'::timestamptz,'https://i.ytimg.com/vi/U8Cae1HGD9A/mqdefault.jpg',236,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('VcjerR4bzsY','https://www.youtube.com/@캄몬장난감만들기','GOOD BYE 멤버 마지막','2026-07-24T07:12:18+00'::timestamptz,'https://i.ytimg.com/vi/VcjerR4bzsY/mqdefault.jpg',9326,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('xO_2zBS2J-E','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 정윤종 생일축하','2026-07-24T07:11:49+00'::timestamptz,'https://i.ytimg.com/vi/xO_2zBS2J-E/mqdefault.jpg',1450,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('zU8wI-cboJs','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 김윤환 휴게소 매드무비','2026-07-24T07:11:47+00'::timestamptz,'https://i.ytimg.com/vi/zU8wI-cboJs/mqdefault.jpg',5764,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('aZudQBdk01Q','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 NEW BEGINNING','2026-07-24T07:11:45+00'::timestamptz,'https://i.ytimg.com/vi/aZudQBdk01Q/mqdefault.jpg',9700,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('KbZBRbliBII','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 그녀석이 복귀합니다','2026-07-24T07:11:43+00'::timestamptz,'https://i.ytimg.com/vi/KbZBRbliBII/mqdefault.jpg',5380,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('leCvpRO_8r8','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 빠지 여행','2026-07-24T07:11:40+00'::timestamptz,'https://i.ytimg.com/vi/leCvpRO_8r8/mqdefault.jpg',4038,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('kflMud16XyM','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 흉가에서 생긴일','2026-07-24T07:11:39+00'::timestamptz,'https://i.ytimg.com/vi/kflMud16XyM/mqdefault.jpg',4064,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('MCHmvnTN2Yc','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 WELCOME 소주양','2026-07-24T07:11:36+00'::timestamptz,'https://i.ytimg.com/vi/MCHmvnTN2Yc/mqdefault.jpg',5182,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('xWHxdypSBhw','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 보여줄게 토스반','2026-07-24T07:11:32+00'::timestamptz,'https://i.ytimg.com/vi/xWHxdypSBhw/mqdefault.jpg',2190,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('7aeNGTKtvOw','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 벼랑끝','2026-07-24T07:11:30+00'::timestamptz,'https://i.ytimg.com/vi/7aeNGTKtvOw/mqdefault.jpg',2817,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('zwqSLEyZ0Fc','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 유잼? 주하랑','2026-07-24T07:11:28+00'::timestamptz,'https://i.ytimg.com/vi/zwqSLEyZ0Fc/mqdefault.jpg',5696,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('BNMhlxIsQME','https://www.youtube.com/@캄몬장난감만들기','츠캄몬스타즈 새로운 시작 2025','2026-07-24T07:11:25+00'::timestamptz,'https://i.ytimg.com/vi/BNMhlxIsQME/mqdefault.jpg',148,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('ZKMSiZaGCmg','https://www.youtube.com/@캄몬장난감만들기','츠캄몬스타즈 퇴학고사 한쪼니','2026-07-24T07:11:22+00'::timestamptz,'https://i.ytimg.com/vi/ZKMSiZaGCmg/mqdefault.jpg',184,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('s4hvEewoaqA','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 72시간 재밌었던 부분','2026-07-24T07:11:20+00'::timestamptz,'https://i.ytimg.com/vi/s4hvEewoaqA/mqdefault.jpg',6107,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('NCWWERc-_rc','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 GOOD-BYE 정윤종','2026-07-24T07:11:15+00'::timestamptz,'https://i.ytimg.com/vi/NCWWERc-_rc/mqdefault.jpg',4608,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('qBL13Ui8Ryg','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 나쟈나소주양','2026-07-24T07:11:10+00'::timestamptz,'https://i.ytimg.com/vi/qBL13Ui8Ryg/mqdefault.jpg',6898,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('dAFmYd5RSgo','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 두뇌 풀가동(김윤환)','2026-07-24T07:11:07+00'::timestamptz,'https://i.ytimg.com/vi/dAFmYd5RSgo/mqdefault.jpg',6397,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('LwdsK-YMQhw','https://www.youtube.com/@캄몬장난감만들기','츠캄몬스타즈 땅콩이 패기','2026-07-24T07:11:05+00'::timestamptz,'https://i.ytimg.com/vi/LwdsK-YMQhw/mqdefault.jpg',4185,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('lPzCn_-_-cg','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 ''우리는''','2026-07-24T07:11:03+00'::timestamptz,'https://i.ytimg.com/vi/lPzCn_-_-cg/mqdefault.jpg',5094,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('mcrYGWDIOKw','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 단두대 매치','2026-07-24T07:11:01+00'::timestamptz,'https://i.ytimg.com/vi/mcrYGWDIOKw/mqdefault.jpg',2911,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('s0oOwNAULFg','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 암흠의 봄날노래방','2026-07-24T07:10:58+00'::timestamptz,'https://i.ytimg.com/vi/s0oOwNAULFg/mqdefault.jpg',4539,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('sibmcdqlPfY','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 짤로 보는 MT편','2026-07-24T07:10:56+00'::timestamptz,'https://i.ytimg.com/vi/sibmcdqlPfY/mqdefault.jpg',3798,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('9oco0trgbrM','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 GOOD BYE 경민','2026-07-24T07:10:54+00'::timestamptz,'https://i.ytimg.com/vi/9oco0trgbrM/mqdefault.jpg',4070,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('ZbZC8pNkD4M','https://www.youtube.com/@캄몬장난감만들기','츠캄몬스타즈 시즌1 멤버 트레일러','2026-07-24T07:08:38+00'::timestamptz,'https://i.ytimg.com/vi/ZbZC8pNkD4M/mqdefault.jpg',565,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('C-Do0BUccVw','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 민심정벌(vs우끼끼즈)','2026-07-24T07:08:35+00'::timestamptz,'https://i.ytimg.com/vi/C-Do0BUccVw/mqdefault.jpg',128,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('VRth6KEsotc','https://www.youtube.com/@캄몬장난감만들기','츠캄몬스타즈 개노답 국토 삼형제 1편','2026-07-24T07:08:31+00'::timestamptz,'https://i.ytimg.com/vi/VRth6KEsotc/mqdefault.jpg',165,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('eqo2WNJ875I','https://www.youtube.com/@캄몬장난감만들기','츠캄몬스타즈 개노답 국토 삼형제 마지막편','2026-07-24T07:08:28+00'::timestamptz,'https://i.ytimg.com/vi/eqo2WNJ875I/mqdefault.jpg',156,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('7pSUZa28KYc','https://www.youtube.com/@캄몬장난감만들기','츠캄몬스타즈 몽펜하이머','2026-07-24T07:08:24+00'::timestamptz,'https://i.ytimg.com/vi/7pSUZa28KYc/mqdefault.jpg',143,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('FNTm_Y6USdM','https://www.youtube.com/@캄몬장난감만들기','츠캄 미니대전 트레일러 vs정선대','2026-07-24T07:08:22+00'::timestamptz,'https://i.ytimg.com/vi/FNTm_Y6USdM/mqdefault.jpg',104,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('wMiREFY0FZc','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 임조이 유스편','2026-07-24T07:08:20+00'::timestamptz,'https://i.ytimg.com/vi/wMiREFY0FZc/mqdefault.jpg',3277,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('fdW11ge5RIE','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 츠캄의 부장들','2026-07-24T07:08:17+00'::timestamptz,'https://i.ytimg.com/vi/fdW11ge5RIE/mqdefault.jpg',207,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('v3CyFQD8LjY','https://www.youtube.com/@캄몬장난감만들기','츠캄몬스타즈 WELCOME 정윤종','2026-07-24T07:08:15+00'::timestamptz,'https://i.ytimg.com/vi/v3CyFQD8LjY/mqdefault.jpg',174,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('ogwIB1_jJHU','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 MT 라면 테러리스트 디임편','2026-07-24T07:08:12+00'::timestamptz,'https://i.ytimg.com/vi/ogwIB1_jJHU/mqdefault.jpg',166,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('qwm5YbXghbc','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 1등 기관사 제자버전(앵지)','2026-07-24T07:08:07+00'::timestamptz,'https://i.ytimg.com/vi/qwm5YbXghbc/mqdefault.jpg',315,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('9QR3na_Tm04','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 시즌1 저그 오프교육  w.깨성근','2026-07-24T07:08:05+00'::timestamptz,'https://i.ytimg.com/vi/9QR3na_Tm04/mqdefault.jpg',177,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('mcISTcdv9XE','https://www.youtube.com/@캄몬장난감만들기','8연패에 빠진 동생을 구출한 김윤환','2026-07-24T07:08:03+00'::timestamptz,'https://i.ytimg.com/vi/mcISTcdv9XE/mqdefault.jpg',191,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('PijB9NVBWIQ','https://www.youtube.com/@캄몬장난감만들기','동생을 구하기 위해 뛰어든 또 다른 형 이경민','2026-07-24T07:08:01+00'::timestamptz,'https://i.ytimg.com/vi/PijB9NVBWIQ/mqdefault.jpg',204,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('2-1ItNzov1w','https://www.youtube.com/@캄몬장난감만들기','츠캄몬스타즈 침몰대전 VS케이대','2026-07-24T07:07:59+00'::timestamptz,'https://i.ytimg.com/vi/2-1ItNzov1w/mqdefault.jpg',598,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('Fb16K_DWWwY','https://www.youtube.com/@캄몬장난감만들기','츠캄몬스타즈 침몰대전 2차 VS정선대','2026-07-24T07:07:57+00'::timestamptz,'https://i.ytimg.com/vi/Fb16K_DWWwY/mqdefault.jpg',222,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('PoLTUpTb0OQ','https://www.youtube.com/@캄몬장난감만들기','츠캄몬스타즈 소림대첩','2026-07-24T07:07:55+00'::timestamptz,'https://i.ytimg.com/vi/PoLTUpTb0OQ/mqdefault.jpg',171,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('jJi8osHSXXc','https://www.youtube.com/@캄몬장난감만들기','츠캄몬스타즈 케이재란 결승진출','2026-07-24T07:07:53+00'::timestamptz,'https://i.ytimg.com/vi/jJi8osHSXXc/mqdefault.jpg',383,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('RXiKxeoAISI','https://www.youtube.com/@캄몬장난감만들기','츠캄몬스타즈 츠캄위의 성','2026-07-24T07:07:51+00'::timestamptz,'https://i.ytimg.com/vi/RXiKxeoAISI/mqdefault.jpg',274,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('5nMgH1Y3xbE','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 2022년도의 약속','2026-07-24T07:07:49+00'::timestamptz,'https://i.ytimg.com/vi/5nMgH1Y3xbE/mqdefault.jpg',226,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('VApniJImjLk','https://www.youtube.com/@캄몬장난감만들기','츠캄 말할 수 없었던 비밀들','2026-07-24T07:07:46+00'::timestamptz,'https://i.ytimg.com/vi/VApniJImjLk/mqdefault.jpg',2368,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('2noHEhweK8g','https://www.youtube.com/@캄몬장난감만들기','1등 기관사코빅리그 김윤환','2026-07-24T07:07:45+00'::timestamptz,'https://i.ytimg.com/vi/2noHEhweK8g/mqdefault.jpg',221,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('RgucmxFz0_4','https://www.youtube.com/@캄몬장난감만들기','츠캄x케이대 앵과늑 뚜껑열기','2026-07-24T07:07:42+00'::timestamptz,'https://i.ytimg.com/vi/RgucmxFz0_4/mqdefault.jpg',3084,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('-HOsBGz-brQ','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 김윤환의 덕몽어스','2026-07-24T07:07:18+00'::timestamptz,'https://i.ytimg.com/vi/-HOsBGz-brQ/mqdefault.jpg',13873,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('tSJIz_MJYTA','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 톤믈리에 븅X환','2026-07-24T07:07:16+00'::timestamptz,'https://i.ytimg.com/vi/tSJIz_MJYTA/mqdefault.jpg',8663,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('fcw5snIN_1c','https://www.youtube.com/@캄몬장난감만들기','몬스타즈 김윤환이 덕몽 즐기는 방법','2026-07-24T07:07:13+00'::timestamptz,'https://i.ytimg.com/vi/fcw5snIN_1c/mqdefault.jpg',10244,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('d1kKpo2kBOc','https://www.youtube.com/@캄몬장난감만들기','캄몬스타즈 부패 보안관 김윤암','2026-07-24T07:07:11+00'::timestamptz,'https://i.ytimg.com/vi/d1kKpo2kBOc/mqdefault.jpg',8674,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('yaQZOSnypBA','https://www.youtube.com/@캄몬장난감만들기','캄몬 육알이 나르샤 (덕몽어스)','2026-07-24T07:07:08+00'::timestamptz,'https://i.ytimg.com/vi/yaQZOSnypBA/mqdefault.jpg',9652,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('t9XbCBh-6Wk','https://www.youtube.com/@캄몬장난감만들기','캄몬 김윤환은 배가 고픕니다 (덕몽어스)','2026-07-24T07:07:06+00'::timestamptz,'https://i.ytimg.com/vi/t9XbCBh-6Wk/mqdefault.jpg',9640,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('6iyeonqpzNc','https://www.youtube.com/@캄몬장난감만들기','캄몬 국밥을 낚는 그녀석들','2026-07-24T07:07:04+00'::timestamptz,'https://i.ytimg.com/vi/6iyeonqpzNc/mqdefault.jpg',11382,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('YB7QyVlt0Is','https://www.youtube.com/@캄몬장난감만들기','캄몬 음지덕몽을 빛내는 자들','2026-07-24T07:07:01+00'::timestamptz,'https://i.ytimg.com/vi/YB7QyVlt0Is/mqdefault.jpg',16079,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('3nbRcyeP6co','https://www.youtube.com/@캄몬장난감만들기','캄몬 트롤은 못말려 (덕몽어스)','2026-07-24T07:06:59+00'::timestamptz,'https://i.ytimg.com/vi/3nbRcyeP6co/mqdefault.jpg',11847,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('e9wJ44u20xU','https://www.youtube.com/@캄몬장난감만들기','캄몬 두두의 최고의한판(덕몽)','2026-07-24T07:06:57+00'::timestamptz,'https://i.ytimg.com/vi/e9wJ44u20xU/mqdefault.jpg',12025,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('yKLgCvPlht8','https://www.youtube.com/@캄몬장난감만들기','캄몬 눈에는 눈 이에는 이(덕몽)','2026-07-24T07:06:55+00'::timestamptz,'https://i.ytimg.com/vi/yKLgCvPlht8/mqdefault.jpg',14005,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('6vOn3ZYc2nc','https://www.youtube.com/@캄몬장난감만들기','캄몬 돌 굴러가유','2026-07-24T07:06:53+00'::timestamptz,'https://i.ytimg.com/vi/6vOn3ZYc2nc/mqdefault.jpg',10721,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('gZ5hkQiVHOo','https://www.youtube.com/@캄몬장난감만들기','캄몬 덕몽어스 트롤편 1화','2026-07-24T07:06:51+00'::timestamptz,'https://i.ytimg.com/vi/gZ5hkQiVHOo/mqdefault.jpg',9442,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('aqnyjnlSb24','https://www.youtube.com/@캄몬장난감만들기','캄몬 덕몽어스 트롤편 2화','2026-07-24T07:06:49+00'::timestamptz,'https://i.ytimg.com/vi/aqnyjnlSb24/mqdefault.jpg',10973,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('QMoShxhicl8','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 빌드 실명제 재판(김윤환)','2026-07-24T07:06:02+00'::timestamptz,'https://i.ytimg.com/vi/QMoShxhicl8/mqdefault.jpg',4252,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('DKwDeLWQHzs','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 김윤환의 뚱보 컬렉션','2026-07-24T07:05:59+00'::timestamptz,'https://i.ytimg.com/vi/DKwDeLWQHzs/mqdefault.jpg',5693,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('z3zS5NBmY5Y','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 초년생 비타밍(W.토&두 부장님)','2026-07-24T07:05:55+00'::timestamptz,'https://i.ytimg.com/vi/z3zS5NBmY5Y/mqdefault.jpg',5551,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('WJw6SjYV9os','https://www.youtube.com/@캄몬장난감만들기','츠캄몬스타즈 권석두의 일기 -화장실편-','2026-07-24T07:05:52+00'::timestamptz,'https://i.ytimg.com/vi/WJw6SjYV9os/mqdefault.jpg',4229,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('BSpiFxepgCk','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 밀리에서 생긴 일','2026-07-24T07:05:45+00'::timestamptz,'https://i.ytimg.com/vi/BSpiFxepgCk/mqdefault.jpg',12577,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('i8VoDiCHF50','https://www.youtube.com/@캄몬장난감만들기','츠캄X흑카데미 수장체인지','2026-07-24T07:05:25+00'::timestamptz,'https://i.ytimg.com/vi/i8VoDiCHF50/mqdefault.jpg',2896,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('Ph_uAxCTyPg','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 햇살 잔혹사','2026-07-24T07:05:22+00'::timestamptz,'https://i.ytimg.com/vi/Ph_uAxCTyPg/mqdefault.jpg',4042,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('8zzCXzQIhxU','https://www.youtube.com/@캄몬장난감만들기','츠캄 몬스타즈 김윤환 수상 리메이크버전','2026-07-24T07:05:19+00'::timestamptz,'https://i.ytimg.com/vi/8zzCXzQIhxU/mqdefault.jpg',6177,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('G7kpUoljdrA','https://www.youtube.com/@캄몬장난감만들기','캄몬 문제아 특집 지두두편(1화)','2026-07-24T07:05:09+00'::timestamptz,'https://i.ytimg.com/vi/G7kpUoljdrA/mqdefault.jpg',17070,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('aawBCCzpgZ8','https://www.youtube.com/@캄몬장난감만들기','캄몬X씨나인 갯벌스타 벌칙모음','2026-07-24T07:05:06+00'::timestamptz,'https://i.ytimg.com/vi/aawBCCzpgZ8/mqdefault.jpg',2520,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('qUu2s_v08vQ','https://www.youtube.com/@캄몬장난감만들기','캄몬 문제아 특집 지두두편(2화)','2026-07-24T07:05:02+00'::timestamptz,'https://i.ytimg.com/vi/qUu2s_v08vQ/mqdefault.jpg',17932,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('x3mFhewD80A','https://www.youtube.com/@캄몬장난감만들기','캄몬 문제아 특집 마지막편','2026-07-24T07:04:58+00'::timestamptz,'https://i.ytimg.com/vi/x3mFhewD80A/mqdefault.jpg',11629,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('4EnDMJurETE','https://www.youtube.com/@캄몬장난감만들기','캄몬 훈수는 집에서 둬라(변현제편)','2026-07-24T07:04:54+00'::timestamptz,'https://i.ytimg.com/vi/4EnDMJurETE/mqdefault.jpg',5550,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('61CZ9xiXM4U','https://www.youtube.com/@캄냥이','김윤환 윷놀이 레전드','2026-07-09T02:55:22+00'::timestamptz,'https://i.ytimg.com/vi/61CZ9xiXM4U/mqdefault.jpg',1462,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('AxBBYD11W_M','https://www.youtube.com/@캄냥이','개똥벌레 김윤환','2026-07-02T08:50:50+00'::timestamptz,'https://i.ytimg.com/vi/AxBBYD11W_M/mqdefault.jpg',241,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('hZ1giWJ1LNg','https://www.youtube.com/@캄냥이','스잘알 택시기사님','2026-07-01T10:32:13+00'::timestamptz,'https://i.ytimg.com/vi/hZ1giWJ1LNg/mqdefault.jpg',24831,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('HE3z-LW2HP4','https://www.youtube.com/@MonstarzFantube','암주양 뮤비2','2026-06-30T12:55:57+00'::timestamptz,'https://i.ytimg.com/vi/HE3z-LW2HP4/mqdefault.jpg',5134,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('XB6YLMp-IO0','https://www.youtube.com/@캄냥이','포켓몬 카드깡 처음 하는 사람','2026-06-28T15:15:28+00'::timestamptz,'https://i.ytimg.com/vi/XB6YLMp-IO0/mqdefault.jpg',362,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('pBcJkx6NI9w','https://www.youtube.com/@캄냥이','아재특징) 노래 흥얼거림','2026-06-27T13:17:57+00'::timestamptz,'https://i.ytimg.com/vi/pBcJkx6NI9w/mqdefault.jpg',2787,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('SpsVDKwJH-Q','https://www.youtube.com/@캄냥이','포토 리버밭 뚫는 법','2026-06-27T08:22:53+00'::timestamptz,'https://i.ytimg.com/vi/SpsVDKwJH-Q/mqdefault.jpg',5831,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('j-CN4QYXhFo','https://www.youtube.com/@캄냥이','멧돼지 떴다니까','2026-06-26T10:35:14+00'::timestamptz,'https://i.ytimg.com/vi/j-CN4QYXhFo/mqdefault.jpg',3460,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('z6HinB-Sjog','https://www.youtube.com/@캄냥이','빨대시야 김윤환','2026-06-26T03:05:05+00'::timestamptz,'https://i.ytimg.com/vi/z6HinB-Sjog/mqdefault.jpg',25866,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('oHXwnJdnVK8','https://www.youtube.com/@캄냥이','브레인 저그 김윤환','2026-06-24T15:16:29+00'::timestamptz,'https://i.ytimg.com/vi/oHXwnJdnVK8/mqdefault.jpg',9301,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('PTv9U5WKZnQ','https://www.youtube.com/@캄냥이','쇼츠 저그 임조이','2026-06-24T08:01:25+00'::timestamptz,'https://i.ytimg.com/vi/PTv9U5WKZnQ/mqdefault.jpg',11534,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('XYCzRFgQGuU','https://www.youtube.com/@캄냥이','만약 스타크래프트유닛으로 다시 태어난다면','2026-06-23T09:22:33+00'::timestamptz,'https://i.ytimg.com/vi/XYCzRFgQGuU/mqdefault.jpg',10999,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('rgsn7w86094','https://www.youtube.com/@캄냥이','전프로게이머 모데궁 대처 매드무비','2026-06-23T03:00:17+00'::timestamptz,'https://i.ytimg.com/vi/rgsn7w86094/mqdefault.jpg',18191,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('WBNKd4PC_7Q','https://www.youtube.com/@캄냥이','고요속의 외침 레전드 ㅋㅋㅋ','2026-06-22T03:00:01+00'::timestamptz,'https://i.ytimg.com/vi/WBNKd4PC_7Q/mqdefault.jpg',2222,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('jNOPoPu5Ovk','https://www.youtube.com/@캄냥이','제자보고 흐뭇해하는 프로게이머','2026-06-21T14:44:59+00'::timestamptz,'https://i.ytimg.com/vi/jNOPoPu5Ovk/mqdefault.jpg',7978,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('gHmKnt2F1CY','https://www.youtube.com/@캄냥이','블루베리스무디 지역별 발음','2026-06-21T03:32:03+00'::timestamptz,'https://i.ytimg.com/vi/gHmKnt2F1CY/mqdefault.jpg',12066,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('kf_1eQXh8aI','https://www.youtube.com/@캄냥이','김윤환 뒷담하다가 걸린 지동원','2026-06-20T12:21:34+00'::timestamptz,'https://i.ytimg.com/vi/kf_1eQXh8aI/mqdefault.jpg',10857,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('aLjsmTkCtfI','https://www.youtube.com/@캄냥이','김윤환 vs 치리 입스타 대결','2026-06-20T06:10:26+00'::timestamptz,'https://i.ytimg.com/vi/aLjsmTkCtfI/mqdefault.jpg',7977,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('cUY8fA4EVHs','https://www.youtube.com/@캄냥이','89년생한테 거제야호 알려주기','2026-06-19T13:17:21+00'::timestamptz,'https://i.ytimg.com/vi/cUY8fA4EVHs/mqdefault.jpg',8411,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('Y2RV4_mdZHk','https://www.youtube.com/@캄냥이','조이야 왜그래','2026-06-19T11:28:23+00'::timestamptz,'https://i.ytimg.com/vi/Y2RV4_mdZHk/mqdefault.jpg',1607,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('IPjfgWcIhc0','https://www.youtube.com/@캄냥이','매국 스트리머한테 일침날리기','2026-06-19T11:03:20+00'::timestamptz,'https://i.ytimg.com/vi/IPjfgWcIhc0/mqdefault.jpg',3532,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('w1zPMvayMv4','https://www.youtube.com/@캄냥이','슬램덩크 보다가 기습 커까하는 지동원','2026-06-18T13:25:20+00'::timestamptz,'https://i.ytimg.com/vi/w1zPMvayMv4/mqdefault.jpg',1106,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('mKnZe09Tr6Y','https://www.youtube.com/@캄냥이','정상까지 직진 - 캄몬','2026-06-18T12:58:45+00'::timestamptz,'https://i.ytimg.com/vi/mKnZe09Tr6Y/mqdefault.jpg',1817,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('j2bVzuS3oXc','https://www.youtube.com/@캄냥이','아이스맨 (배성흠)','2026-06-18T12:58:43+00'::timestamptz,'https://i.ytimg.com/vi/j2bVzuS3oXc/mqdefault.jpg',354,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('EN8stDxt-Mc','https://www.youtube.com/@캄냥이','구슬동자 토마토','2026-06-18T12:58:29+00'::timestamptz,'https://i.ytimg.com/vi/EN8stDxt-Mc/mqdefault.jpg',1073,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('4meAvkfrOV4','https://www.youtube.com/@캄냥이','두비두 - 김민철','2026-06-18T12:52:00+00'::timestamptz,'https://i.ytimg.com/vi/4meAvkfrOV4/mqdefault.jpg',885,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('XpJ6CMh-8bE','https://www.youtube.com/@캄냥이','김윤환 숨바꼭질','2026-06-18T12:49:48+00'::timestamptz,'https://i.ytimg.com/vi/XpJ6CMh-8bE/mqdefault.jpg',1393,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('nnIPu8_FsYU','https://www.youtube.com/@캄냥이','캄몬 합숙소','2026-06-18T12:49:41+00'::timestamptz,'https://i.ytimg.com/vi/nnIPu8_FsYU/mqdefault.jpg',1238,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('VIBcipA4YXI','https://www.youtube.com/@캄냥이','낭니 - unwelcome school','2026-06-18T12:49:30+00'::timestamptz,'https://i.ytimg.com/vi/VIBcipA4YXI/mqdefault.jpg',872,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('NCY6GkDZ1iM','https://www.youtube.com/@캄냥이','바보 아니에요 - 먼진','2026-06-18T12:46:34+00'::timestamptz,'https://i.ytimg.com/vi/NCY6GkDZ1iM/mqdefault.jpg',1432,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('rA3cmWVsOuE','https://www.youtube.com/@캄냥이','honeypie - 소주양','2026-06-18T12:46:14+00'::timestamptz,'https://i.ytimg.com/vi/rA3cmWVsOuE/mqdefault.jpg',713,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('mSfglFpUkrs','https://www.youtube.com/@캄냥이','암날두','2026-06-18T12:46:05+00'::timestamptz,'https://i.ytimg.com/vi/mSfglFpUkrs/mqdefault.jpg',916,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('yIR6_vWNG4k','https://www.youtube.com/@캄냥이','Hollywood action (비타밍)','2026-06-18T12:45:57+00'::timestamptz,'https://i.ytimg.com/vi/yIR6_vWNG4k/mqdefault.jpg',860,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('hh67bUjjwrQ','https://www.youtube.com/@캄냥이','RED RED (임조이)','2026-06-18T12:42:45+00'::timestamptz,'https://i.ytimg.com/vi/hh67bUjjwrQ/mqdefault.jpg',1244,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('INWqX6d4p3k','https://www.youtube.com/@캄냥이','귀엽기만 하면 안되나요? (치리)','2026-06-18T12:42:30+00'::timestamptz,'https://i.ytimg.com/vi/INWqX6d4p3k/mqdefault.jpg',763,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('iYRzUiHWLWc','https://www.youtube.com/@캄냥이','모시모시 (치리)','2026-06-18T12:42:15+00'::timestamptz,'https://i.ytimg.com/vi/iYRzUiHWLWc/mqdefault.jpg',752,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('3CkLr401l7M','https://www.youtube.com/@캄냥이','임조이 - 비상사태 (공습경보)','2026-06-18T12:42:01+00'::timestamptz,'https://i.ytimg.com/vi/3CkLr401l7M/mqdefault.jpg',1380,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('XDsQ8B_RAdA','https://www.youtube.com/@캄냥이','챱츄 챱챱츄 (치리)','2026-06-18T12:40:30+00'::timestamptz,'https://i.ytimg.com/vi/XDsQ8B_RAdA/mqdefault.jpg',2303,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('1RsqDYeWz3g','https://www.youtube.com/@MonstarzFantube','월간 캄몬(26년4월)','2026-06-08T23:47:07+00'::timestamptz,'https://i.ytimg.com/vi/1RsqDYeWz3g/mqdefault.jpg',5800,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('f5hLDNimDrI','https://www.youtube.com/@MonstarzFantube','먼진의 도시락 쿡방','2026-06-06T03:03:50+00'::timestamptz,'https://i.ytimg.com/vi/f5hLDNimDrI/mqdefault.jpg',2980,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('y_BzWrhgT14','https://www.youtube.com/@MonstarzFantube','월간 캄몬(26년3월)','2026-06-03T04:53:00+00'::timestamptz,'https://i.ytimg.com/vi/y_BzWrhgT14/mqdefault.jpg',3656,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('iYO9iQe6MmA','https://www.youtube.com/@MonstarzFantube','루돌프 임조이의 선물 배달','2026-05-22T01:49:13+00'::timestamptz,'https://i.ytimg.com/vi/iYO9iQe6MmA/mqdefault.jpg',4045,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('OTzNQfL5Fwg','https://www.youtube.com/@MonstarzFantube','암주양 뮤비','2026-04-23T16:24:29+00'::timestamptz,'https://i.ytimg.com/vi/OTzNQfL5Fwg/mqdefault.jpg',9627,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('d0e02gthfWs','https://www.youtube.com/@MonstarzFantube','월간 츠캄(26년2월)','2026-04-17T09:03:51+00'::timestamptz,'https://i.ytimg.com/vi/d0e02gthfWs/mqdefault.jpg',6028,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('FyxrJ8RqKyM','https://www.youtube.com/@MonstarzFantube','갈통폰','2026-04-08T17:17:14+00'::timestamptz,'https://i.ytimg.com/vi/FyxrJ8RqKyM/mqdefault.jpg',5520,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('sZvkycQ8-I8','https://www.youtube.com/@MonstarzFantube','의도치 않은 저격','2026-04-08T16:07:27+00'::timestamptz,'https://i.ytimg.com/vi/sZvkycQ8-I8/mqdefault.jpg',5625,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('CycUQ5syxWI','https://www.youtube.com/@MonstarzFantube','주하랑의 술냄새나는 방송','2026-03-29T07:58:52+00'::timestamptz,'https://i.ytimg.com/vi/CycUQ5syxWI/mqdefault.jpg',7979,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('wZRTJtRw5dY','https://www.youtube.com/@MonstarzFantube','자존심을 건 1:1 스나대결(주하랑 vs 김윤환)','2026-03-27T17:51:51+00'::timestamptz,'https://i.ytimg.com/vi/wZRTJtRw5dY/mqdefault.jpg',7077,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('vYinWEI9JR4','https://www.youtube.com/@MonstarzFantube','븅자매의 윷놀이 한 판2','2026-03-26T15:24:19+00'::timestamptz,'https://i.ytimg.com/vi/vYinWEI9JR4/mqdefault.jpg',2987,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('FUqMZYSl8HE','https://www.youtube.com/@MonstarzFantube','븅자매의 윷놀이 한 판','2026-03-20T17:26:45+00'::timestamptz,'https://i.ytimg.com/vi/FUqMZYSl8HE/mqdefault.jpg',5019,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('IOSNIeoCZAo','https://www.youtube.com/@MonstarzFantube','상대 여캠에게 귓속말하면 생기는 일','2026-02-27T08:18:09+00'::timestamptz,'https://i.ytimg.com/vi/IOSNIeoCZAo/mqdefault.jpg',10813,true,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('O5SvTB7idMY','https://www.youtube.com/@MonstarzFantube','월간 츠캄(25년11월)','2026-02-14T02:14:55+00'::timestamptz,'https://i.ytimg.com/vi/O5SvTB7idMY/mqdefault.jpg',5370,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('2YiodQRFnZo','https://www.youtube.com/@MonstarzFantube','츠캄의 마토','2026-02-09T17:20:51+00'::timestamptz,'https://i.ytimg.com/vi/2YiodQRFnZo/mqdefault.jpg',3188,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('DgrBKIJBpSA','https://www.youtube.com/@MonstarzFantube','월간 츠캄(26년1월)','2026-02-06T16:11:46+00'::timestamptz,'https://i.ytimg.com/vi/DgrBKIJBpSA/mqdefault.jpg',7601,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('6vUNoB55thc','https://www.youtube.com/@MonstarzFantube','주하랑 서든 매드무비','2026-02-02T11:09:38+00'::timestamptz,'https://i.ytimg.com/vi/6vUNoB55thc/mqdefault.jpg',2741,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('d032xSmiWgg','https://www.youtube.com/@MonstarzFantube','대학대전 츠캄vs늪지대','2026-01-30T18:45:38+00'::timestamptz,'https://i.ytimg.com/vi/d032xSmiWgg/mqdefault.jpg',1128,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('XB4ZfAFqkXI','https://www.youtube.com/@MonstarzFantube','김윤환 디시트 (Deceit)','2026-01-30T06:39:00+00'::timestamptz,'https://i.ytimg.com/vi/XB4ZfAFqkXI/mqdefault.jpg',996,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('UxVFeGjOoXw','https://www.youtube.com/@MonstarzFantube','하랑햇살 공포게임','2026-01-22T22:46:01+00'::timestamptz,'https://i.ytimg.com/vi/UxVFeGjOoXw/mqdefault.jpg',1304,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('hTY95QDCKZ8','https://www.youtube.com/@MonstarzFantube','소주양 이름 실종사건','2026-01-19T12:00:56+00'::timestamptz,'https://i.ytimg.com/vi/hTY95QDCKZ8/mqdefault.jpg',3062,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('INoGOLF4MeA','https://www.youtube.com/@MonstarzFantube','진땅콩 짜파게티 먹방','2026-01-16T08:14:48+00'::timestamptz,'https://i.ytimg.com/vi/INoGOLF4MeA/mqdefault.jpg',2465,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('ityO22cUoj0','https://www.youtube.com/@MonstarzFantube','츠캄 술먹방 대참사','2026-01-16T07:12:12+00'::timestamptz,'https://i.ytimg.com/vi/ityO22cUoj0/mqdefault.jpg',3524,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('WpGzO40A9V0','https://www.youtube.com/@MonstarzFantube','진땅콩 메운디','2026-01-09T13:22:52+00'::timestamptz,'https://i.ytimg.com/vi/WpGzO40A9V0/mqdefault.jpg',3214,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('Yf7EqQXB2uc','https://www.youtube.com/@MonstarzFantube','종연하 뮤비 part2','2026-01-03T10:15:59+00'::timestamptz,'https://i.ytimg.com/vi/Yf7EqQXB2uc/mqdefault.jpg',1842,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('CvCpPFG5xZs','https://www.youtube.com/@MonstarzFantube','종연하 뮤비 part1','2026-01-02T14:12:07+00'::timestamptz,'https://i.ytimg.com/vi/CvCpPFG5xZs/mqdefault.jpg',1283,false,false) on conflict (id) do nothing;
insert into public.videos(id,channel_url,title,published,thumb,views,short,hidden) values ('4gQHhD040Mw','https://www.youtube.com/@MonstarzFantube','츠캄 꽃다발 잔혹사','2025-12-29T16:41:04+00'::timestamptz,'https://i.ytimg.com/vi/4gQHhD040Mw/mqdefault.jpg',16605,false,false) on conflict (id) do nothing;
insert into public.video_picks(id,kind,title,note,group_name,group_en,added_at,author,thumb,short,hidden,source_order) values ('6ahN19lIHaA','youtube','왜 09김윤환인가','','김윤환','KIM YOONHWAN','2026-09-18'::date,'김윤환TV','https://i.ytimg.com/vi/6ahN19lIHaA/hqdefault.jpg',false,false,1) on conflict (id) do nothing;
insert into public.video_picks(id,kind,title,note,group_name,group_en,added_at,author,thumb,short,hidden,source_order) values ('D2Z1YL_nrgU','youtube','인생이 구라인 남자','','김윤환','KIM YOONHWAN','2026-09-18'::date,'김윤환TV','https://i.ytimg.com/vi/D2Z1YL_nrgU/hqdefault.jpg',false,false,2) on conflict (id) do nothing;
insert into public.video_picks(id,kind,title,note,group_name,group_en,added_at,author,thumb,short,hidden,source_order) values ('6mO-BiXHqfY','youtube','이 남자를 찾습니다','','김윤환','KIM YOONHWAN','2026-09-18'::date,'김윤환TV','https://i.ytimg.com/vi/6mO-BiXHqfY/hqdefault.jpg',false,false,3) on conflict (id) do nothing;
insert into public.video_picks(id,kind,title,note,group_name,group_en,added_at,author,thumb,short,hidden,source_order) values ('3KtNJxoYyX4','youtube','권석두의 일기','','김윤환','KIM YOONHWAN','2026-09-18'::date,'김윤환TV','https://i.ytimg.com/vi/3KtNJxoYyX4/hqdefault.jpg',false,false,4) on conflict (id) do nothing;
insert into public.video_picks(id,kind,title,note,group_name,group_en,added_at,author,thumb,short,hidden,source_order) values ('soop:146974661','soop','[MV] 최강스타','','몬스타즈','MONSTARZ','2026-09-18'::date,'숲 VOD','https://iflv14.sooplive.com/save/afreeca/station/2025/0109/19/thumb/1736417904748682_R_7.jpg',false,false,5) on conflict (id) do nothing;
insert into public.video_picks(id,kind,title,note,group_name,group_en,added_at,author,thumb,short,hidden,source_order) values ('soop:144331057','soop','[MV] We are','','몬스타즈','MONSTARZ','2026-09-18'::date,'숲 VOD','https://iflv14.sooplive.com/save/afreeca/station/2024/1206/09/thumb/1733446718892060_R_7.jpg',false,false,6) on conflict (id) do nothing;
insert into public.video_picks(id,kind,title,note,group_name,group_en,added_at,author,thumb,short,hidden,source_order) values ('soop:145640549','soop','[MV] 완전감각Dreamer','','몬스타즈','MONSTARZ','2026-09-18'::date,'숲 VOD','https://iflv14.sooplive.com/save/afreeca/station/2024/1220/00/thumb/1734623614276694_R_7.jpg',false,false,7) on conflict (id) do nothing;
insert into public.video_picks(id,kind,title,note,group_name,group_en,added_at,author,thumb,short,hidden,source_order) values ('soop:146040651','soop','[MV] 100 Bad Days','','몬스타즈','MONSTARZ','2026-09-18'::date,'숲 VOD','https://iflv14.sooplive.com/save/afreeca/station/2024/1224/10/thumb/1735005069327003_R_7.jpg',false,false,8) on conflict (id) do nothing;
insert into public.video_picks(id,kind,title,note,group_name,group_en,added_at,author,thumb,short,hidden,source_order) values ('aZudQBdk01Q','youtube','츠캄 몬스타즈 NEW BEGINNING','','몬스타즈','MONSTARZ','2026-09-18'::date,'캄몬 장난감','https://i.ytimg.com/vi/aZudQBdk01Q/hqdefault.jpg',false,false,9) on conflict (id) do nothing;
insert into public.video_picks(id,kind,title,note,group_name,group_en,added_at,author,thumb,short,hidden,source_order) values ('leCvpRO_8r8','youtube','츠캄 몬스타즈 빠지 여행','','몬스타즈','MONSTARZ','2026-09-18'::date,'캄몬 장난감','https://i.ytimg.com/vi/leCvpRO_8r8/hqdefault.jpg',false,false,10) on conflict (id) do nothing;
insert into public.video_picks(id,kind,title,note,group_name,group_en,added_at,author,thumb,short,hidden,source_order) values ('9oco0trgbrM','youtube','츠캄 몬스타즈 GOOD BYE 경민','','몬스타즈','MONSTARZ','2026-09-18'::date,'캄몬 장난감','https://i.ytimg.com/vi/9oco0trgbrM/hqdefault.jpg',false,false,11) on conflict (id) do nothing;

-- 관리자 CRUD
do $$ declare t text; begin
  foreach t in array array['video_channels','videos','video_picks'] loop
    execute format('drop policy if exists %I on public.%I', 'admins_all_' || t, t);
    execute format('create policy %I on public.%I for all to authenticated using (public.is_admin()) with check (public.is_admin())', 'admins_all_' || t, t);
  end loop;
end $$;
grant select,insert,update,delete on public.video_channels,public.videos,public.video_picks to authenticated;

-- 공개 영상 탭 읽기
revoke all on public.video_channels,public.videos,public.video_picks from anon;
grant select (channel_url,channel_id,title,display_name,thumb,uploads,source_order,active) on public.video_channels to anon;
grant select (id,channel_url,title,published,thumb,views,short,hidden) on public.videos to anon;
grant select (id,kind,title,note,group_name,group_en,added_at,author,thumb,short,hidden,source_order) on public.video_picks to anon;
drop policy if exists public_read_video_channels on public.video_channels;
create policy public_read_video_channels on public.video_channels for select to anon using (active=true);
drop policy if exists public_read_videos on public.videos;
create policy public_read_videos on public.videos for select to anon using (true);
drop policy if exists public_read_video_picks on public.video_picks;
create policy public_read_video_picks on public.video_picks for select to anon using (true);

-- ============================================================================
-- 도구 > 외부도구 (기존 어드민 관리 링크)
-- 멀티뷰어/엔트리/캄몬라이더 자체 기능은 Git에 남고, 여기에는 외부 링크만 저장한다.
-- ============================================================================
create table if not exists public.external_tools (
  id bigint generated by default as identity primary key,
  category text not null check (category in ('extTools','extSites')),
  name text not null,
  url text not null,
  favicon text,
  source_order integer not null unique,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);
create index if not exists external_tools_category_order_idx on public.external_tools(category, source_order);
alter table public.external_tools enable row level security;

-- 현재 docs/data/tools.json 최초 시드. 이미 같은 URL이 있으면 건드리지 않는다.
insert into public.external_tools(category,name,url,favicon,source_order,active)
select 'extTools','혹시','https://calm-hoxy.vercel.app/',null,1,true
where not exists (select 1 from public.external_tools where url='https://calm-hoxy.vercel.app/');
insert into public.external_tools(category,name,url,favicon,source_order,active)
select 'extTools','암다리','https://prena.io/brain/',null,2,true
where not exists (select 1 from public.external_tools where url='https://prena.io/brain/');
insert into public.external_tools(category,name,url,favicon,source_order,active)
select 'extTools','핀볼','https://lazygyu.github.io/roulette/',null,3,true
where not exists (select 1 from public.external_tools where url='https://lazygyu.github.io/roulette/');
insert into public.external_tools(category,name,url,favicon,source_order,active)
select 'extTools','네이버 사다리','https://search.naver.com/search.naver?where=nexearch&query=%EC%82%AC%EB%8B%A4%EB%A6%AC%EA%B2%8C%EC%9E%84','https://naver.com/favicon.ico',4,true
where not exists (select 1 from public.external_tools where url='https://search.naver.com/search.naver?where=nexearch&query=%EC%82%AC%EB%8B%A4%EB%A6%AC%EA%B2%8C%EC%9E%84');
insert into public.external_tools(category,name,url,favicon,source_order,active)
select 'extSites','EloBoard','https://eloboard.com/',null,5,true
where not exists (select 1 from public.external_tools where url='https://eloboard.com/');

-- 관리자 CRUD
drop policy if exists admins_all_external_tools on public.external_tools;
create policy admins_all_external_tools on public.external_tools for all to authenticated
using (public.is_admin()) with check (public.is_admin());
grant select,insert,update,delete on public.external_tools to authenticated;
grant usage,select on sequence public.external_tools_id_seq to authenticated;

-- 공개 사이트 읽기
revoke all on public.external_tools from anon;
grant select (id,category,name,url,favicon,source_order,active) on public.external_tools to anon;
drop policy if exists public_read_external_tools on public.external_tools;
create policy public_read_external_tools on public.external_tools for select to anon using (active=true);
